### ISSUE TITLE
[BUG]打开run-mirai.bat文件并成功登录后，打开run-bot.bat文件显示无法连接到 mirai问题

### ISSUE THREAD

**Issue by Aki-kia** [RockChinQ/QChatGPT#102]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    WIN 10
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
打开run-mirai.bat文件并成功登录后，打开run-bot.bat文件显示无法连接到 mirai，请检查 mirai-api-http 是否启动，地址与端口是否正确。无法登录主程序。
已经尝试过重启run-bot.bat文件、重新安装mirai、删除所有文件重新解压重新部署和安装，但是都会重复同样的报错。

**完整报错信息**  
```
2023-01-14 20:41:38 - ERROR    无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。
[2023-01-14 20:41:38.231] base.py (40) - [ERROR] : 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确 。
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "asyncio\tasks.py", line 445, in wait_for
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\websockets\legacy\client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "asyncio\base_events.py", line 1075, in create_connection
  File "asyncio\base_events.py", line 1054, in create_connection
  File "asyncio\base_events.py", line 963, in _connect_sock
  File "asyncio\proactor_events.py", line 709, in sock_connect
  File "asyncio\windows_events.py", line 821, in _poll
  File "asyncio\windows_events.py", line 608, in finish_connect
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "E:\Program Files\QQbot\bot\python\lib\site-packages\mirai\adapters\base.py", line 41, in wrapped
    raise err from e
mirai.exceptions.NetworkError: 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。

```

**Comment by Aki-kia** [comment]
补充：mirai没有任何问题，正常运行！

**Comment by RockChinQ** [comment]
检查防火墙是否阻拦端口，或根据 #22 更换端口

**Comment by Aki-kia** [comment]
> 检查防火墙是否阻拦端口，或根据 #22 更换端口

已经确认，是一键部署的文件中QChatGPT文件夹下config.py文件里会将mirai端口设置成8081端口，修改成与mirai相同的8080端口后可正常使用。

**Comment by 46fafa** [comment]
![屏幕截图 2023-01-30 162009](https://user-images.githubusercontent.com/92380602/215424444-431de082-0593-4788-82ec-e92c78282800.png)
![屏幕截图 2023-01-30 162032](https://user-images.githubusercontent.com/92380602/215424451-fca20231-b227-48f5-842d-7063d2cc222f.png)
我的端口没有是8080,出现报错的只有base.py和main.py两个文件夹,请问这是什么问题

**Comment by RockChinQ** [comment]
> ![屏幕截图 2023-01-30 162009](https://user-images.githubusercontent.com/92380602/215424444-431de082-0593-4788-82ec-e92c78282800.png) ![Inked屏幕截图 2023-01-30 162032](https://user-images.githubusercontent.com/92380602/215424930-e3435d5d-048e-492a-b6d6-d9b55130c5ad.jpg)
> 
> 我的端口没有是8080,出现报错的只有base.py和main.py两个文件夹,请问这是什么问题

检查mirai是否启动，mirai-api-http设置的地址和端口是否正确

**Comment by 46fafa** [comment]
![屏幕截图 2023-01-30 162853](https://user-images.githubusercontent.com/92380602/215425889-963f83f4-63db-49b8-a08a-e97e84a9687f.png)
mirai应该是启动了,其中有一些报错没有影响最终结果,我应该怎么检查mirai-api-http设置的地址和端口是否正确呢

**Comment by 46fafa** [comment]
自动化部署

**Comment by RockChinQ** [comment]
> 自动化部署

检查一下目录`mirai/config`下是否包含`net.mamoe.mirai-api-http`目录

**Comment by 46fafa** [comment]
没有

**Comment by RockChinQ** [comment]
> 没有

尝试本仓库文档的[手动部署](https://github.com/RockChinQ/QChatGPT#--%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2)流程完善一下组件吧，按照此链接指向的章节一步一步来：mirai环节你可以直接跳转到那个文章中的mirai-api-http部署环节；QChatGPT源码你已经下载了，不需要重新克隆。  
之后遇到的问题请以关键词查找此仓库issue

**Comment by 46fafa** [comment]
好的,谢谢

**Comment by 46fafa** [comment]
![image](https://user-images.githubusercontent.com/92380602/215437936-9e7ca262-6fc5-43f6-851f-95028366d7ee.png)
你好大佬,我在手动部署第一步就遇到了问题,请问这是什么情况

**Comment by RockChinQ** [comment]
> ![image](https://user-images.githubusercontent.com/92380602/215437936-9e7ca262-6fc5-43f6-851f-95028366d7ee.png) 你好大佬,我在手动部署第一步就遇到了问题,请问这是什么情况
关掉网络代理重试，若下载速度太慢可尝试使用国内镜像 [教程](https://blog.csdn.net/weixin_39334709/article/details/105265951)

**Comment by 46fafa** [comment]
> > ![image](https://user-images.githubusercontent.com/92380602/215437936-9e7ca262-6fc5-43f6-851f-95028366d7ee.png) 你好大佬,我在手动部署第一步就遇到了问题,请问这是什么情况
> 
> 关掉网络代理重试，若下载速度太慢可尝试使用国内镜像 [教程](https://blog.csdn.net/weixin_39334709/article/details/105265951)

感谢大佬,配置成功了

**Comment by Ren-Boo** [comment]
大佬看看我这是什么原因？

2023-02-11 22:29:32 - ERROR    无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。
[2023-02-11 22:29:32.880] base.py (40) - [ERROR] : 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确 。
[2023-02-11 22:29:32.885] main.py (165) - [ERROR] : 连接mirai-api-http失败:无法连接到 mirai。请检查 mirai-api-http 是否 启动，地址与端口是否正确。, 请检查是否已按照文档启动mirai

D:\liulin\ChatGPT_QQ\QChatGPT>pause
请按任意键继续. . .

**Comment by RockChinQ** [comment]
> 大佬看看我这是什么原因？
> 
> 2023-02-11 22:29:32 - ERROR 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。 [2023-02-11 22:29:32.880] base.py (40) - [ERROR] : 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确 。 [2023-02-11 22:29:32.885] main.py (165) - [ERROR] : 连接mirai-api-http失败:无法连接到 mirai。请检查 mirai-api-http 是否 启动，地址与端口是否正确。, 请检查是否已按照文档启动mirai
> 
> D:\liulin\ChatGPT_QQ\QChatGPT>pause 请按任意键继续. . .

检查是否启动了mirai

**Comment by Ren-Boo** [comment]
> 
![VGKHPF36{6} 76Q$GEYAE](https://user-images.githubusercontent.com/63947664/218266788-c5b24887-c4a6-44bd-8c2c-1a1f30a994d4.png)
这个报错怎么解决？
