### ISSUE TITLE
运行 python3 main.py 时报错：cannot import name dataclass_transform

### ISSUE THREAD

**Issue by dfvips** [RockChinQ/QChatGPT#11]
系统版本：Linux ip-172-31-0-40.ap-east-1.compute.internal 5.10.118-111.515.amzn2.x86_64 #1 SMP Wed May 25 22:12:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
python版本： 3.7.15-1.amzn2.0.2 
截图：
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/21048630/206861493-1e76091b-469f-425a-9e01-518a86bef914.png">

报错提示：
Traceback (most recent call last):
  File "main.py", line 97, in <module>
    main()
  File "main.py", line 52, in main
    import pkg.qqbot.manager
  File "/root/qchatgpt/QChatGPT/pkg/qqbot/manager.py", line 5, in <module>
    from mirai import At, GroupMessage, MessageEvent, Mirai, Plain, StrangerMessage, WebSocketAdapter, FriendMessage, Image
  File "/usr/local/lib/python3.7/site-packages/mirai/__init__.py", line 19, in <module>
    from mirai.adapters import Adapter
  File "/usr/local/lib/python3.7/site-packages/mirai/adapters/__init__.py", line 9, in <module>
    from .base import Adapter
  File "/usr/local/lib/python3.7/site-packages/mirai/adapters/base.py", line 12, in <module>
    from mirai import exceptions
  File "/usr/local/lib/python3.7/site-packages/mirai/exceptions.py", line 9, in <module>
    from pydantic import ValidationError
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 52, in init pydantic.dataclasses
    #   |
ImportError: cannot import name dataclass_transform

**Comment by dfvips** [comment]
成功安装记录：
python版本：3.9.8
按照文档的配置安装：
```
wget https://www.python.org/ftp/python/3.9.8/Python-3.9.8.tgz
tar -zxvf Python-3.9.8.tgz
cd Python-3.9.8/
./configure --prefix=/usr/local/python398
make&make install
ln -sf /usr/local/python398/bin/python3 /usr/bin/python398
ln -sf /usr/local/python398/bin/pip3 /usr/bin/pip398
git clone https://github.com/RockChinQ/QChatGPT
pip398 install pymysql yiri-mirai openai colorlog func_timeout
cd /QChatGPT
python398 main.py init_db
```
编辑一下配置config.py
```
python398 main.py
vim main.py 
```
最后运行
```
python398 main.py
```
完成。
