### ISSUE TITLE
[BUG]运行main.py报错

### ISSUE THREAD

**Issue by via-2** [RockChinQ/QChatGPT#110]
**运行环境**
- 部署方式：
    手动部署
- 系统环境：
     Centos x64
- Python环境（仅手动部署填写）：
    python 3.9

**描述漏洞**  
运行main.py报错

**完整报错信息**  
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/threading.py", line 950, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.9/threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/qqbot/QChatGPT-master/main.py", line 185, in run_bot_wrapper
    raise e
  File "/usr/qqbot/QChatGPT-master/main.py", line 147, in run_bot_wrapper
    qqbot.bot.run()
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/usr/local/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/python3/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/python3/lib/python3.9/asyncio/tasks.py", line 476, in wait_for
    return fut.result()
  File "/usr/local/python3/lib/python3.9/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/local/python3/lib/python3.9/asyncio/base_events.py", line 1064, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
```

**Comment by RockChinQ** [comment]
检查mirai是否启动、8080端口是否被防火墙拦截

**Comment by via-2** [comment]
> 检查mirai是否启动、8080端口是否被防火墙拦截

检查了，开启状态，已关闭防火墙

**Comment by RockChinQ** [comment]
问题还没解决是吗？

**Comment by via-2** [comment]
> 问题还没解决是吗？

是的

**Comment by via-2** [comment]
> 问题还没解决是吗？

还没解决

**Comment by q123458384** [comment]
端口是不是被占用了，改个端口试试

**Comment by RockChinQ** [comment]
重复issue，查看 #68
