### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'mirai'

### ISSUE THREAD

**Issue by Nana1337mi** [RockChinQ/QChatGPT#112]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署
- 系统环境：
    例如： Centos 8
- Python环境（仅手动部署填写）：
    例如： Python 3.9.5

**描述漏洞**  
在使用python3 main.py运行时，开始并未有任何提示，之后弹出一堆。以下信息都是同一瞬间出现的，在那之前只有光标闪烁

**完整报错信息**  
```
[root@rjdwqre9bakr2qxa QChatGPT]# python3 main.py
[2023-02-01 13:18:37.179] main.py (189) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
Traceback (most recent call last):
  File "/root/QChatGPT/main.py", line 275, in <module>
    main(True)
  File "/root/QChatGPT/main.py", line 113, in main
    import pkg.openai.manager
  File "/root/QChatGPT/pkg/openai/manager.py", line 5, in <module>
    import pkg.openai.keymgr
  File "/root/QChatGPT/pkg/openai/keymgr.py", line 5, in <module>
    import pkg.plugin.host as plugin_host
  File "/root/QChatGPT/pkg/plugin/host.py", line 13, in <module>
    from mirai import Mirai
ModuleNotFoundError: No module named 'mirai'
```

**Comment by RockChinQ** [comment]
用python3命令行交互方式尝试执行指令`import mirai`看看输出什么

**Comment by RockChinQ** [comment]
python环境问题，请删除已安装的所有库文件，并重新安装主机上所有python
