### ISSUE TITLE
setting.yml设置后报错

### ISSUE THREAD

**Issue by Yukon51** [RockChinQ/QChatGPT#119]
**运行环境**
- 部署方式：
    手动部署
- 系统环境：Macos
   
- Python环境（仅手动部署填写）：3.10
    

**描述漏洞**  
在进行配置 mirai-api-http一步时，修改setting.yml后重新启动./mcl报错（有没有可能是因为我之前装过一次没有成功就直接删除文件夹导致），求解决方案

**完整报错信息**  
2023-02-08 10:41:27 I/Mirai HTTP API: ********************************************************
2023-02-08 10:41:28 E/net.mamoe.mirai-api-http: kotlinx.coroutines.JobCancellationException: LazyStandaloneCoroutine is cancelling; job=LazyStandaloneCoroutine{Cancelling}@56826a75
kotlinx.coroutines.JobCancellationException: LazyStandaloneCoroutine is cancelling; job=LazyStandaloneCoroutine{Cancelling}@56826a75
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
	at mirai-api-http-v2.2.0.mirai.jar//io.ktor.network.sockets.ConnectUtils

2023-02-08 10:41:28 E/MahKtorAdapter[ws]: java.net.BindException: Address already in use

**Comment by RockChinQ** [comment]
mirai-api-http的端口被其他程序占用，参考 #22 修改端口
