### ISSUE TITLE
依赖包mirai安装异常，报错NameError: name 'execfile' is not defined

### ISSUE THREAD

**Issue by dfvips** [RockChinQ/QChatGPT#12]
系统版本：Linux ip-172-31-0-40.ap-east-1.compute.internal 5.10.118-111.515.amzn2.x86_64 https://github.com/RockChinQ/QChatGPT/issues/1 SMP Wed May 25 22:12:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
python版本： 3.9.8 和 3.11.1
截图：
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/21048630/206867099-84c5fc3f-afec-46a6-8a32-bdc2c2a301a8.png">
异常：
Collecting mirai
  Using cached mirai-0.1.5.tar.gz (12 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4odfkf1h/mirai_a12ce1acd10f46d5ba7f8f474cadfc17/setup.py", line 16, in <module>
          version           = version('mirai'),
        File "/tmp/pip-install-4odfkf1h/mirai_a12ce1acd10f46d5ba7f8f474cadfc17/setup.py", line 9, in version
          execfile(_version, env)
      NameError: name 'execfile' is not defined
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by dfvips** [comment]
参见：<a href="https://github.com/RockChinQ/QChatGPT/issues/11">https://github.com/RockChinQ/QChatGPT/issues/11</a>
