### ISSUE TITLE
[BUG]主程序容器无法正常运行，容器自动退出

### ISSUE THREAD

**Issue by narwhrl** [RockChinQ/QChatGPT#127]
**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    Ubuntu 18.04 64 Bit

**描述漏洞**  
我自己排查了很久也没找到问题，config.py只改了模板中的必要选项。
Mirai容器正常启动并运行，用`docker logs`看日志也是正常登录了的。
报错提示我`捕捉到未知异常`，所以我只能来提Issue了TAT

**完整报错信息**  
报错内容如下
```
[2023-02-09 15:32:04.122] host.py (60) - [INFO] : 加载插件
[2023-02-09 15:32:04.125] host.py (72) - [INFO] : 初始化插件
2023-02-09 15:32:04 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
WARNING: 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-09 15:32:04.128] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2023-02-09 15:32:14 - ERROR    
ERROR: 
[2023-02-09 15:32:14.146] base.py (43) - [ERROR] : 
ERROR: 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
[2023-02-09 15:32:14.152] main.py (182) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/main.py", line 185, in run_bot_wrapper
    raise e
  File "/bot/main.py", line 147, in run_bot_wrapper
    qqbot.bot.run()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by RockChinQ** [comment]
这一个是由于mirai-api-http的监听端口被占用导致的，建议更换端口，同时修改docker容器的端口映射，mirai-api-http的端口可以在`mirai/config/net.mamoe.mirai-api-http/setting.yml`找到，主程序连接的端口可以在`config.py`找到；但由于步骤较多，建议使用本仓库文档中的手动部署步骤进行部署。

**Comment by narwhrl** [comment]
> 这一个是由于mirai-api-http的监听端口被占用导致的，建议更换端口，同时修改docker容器的端口映射，mirai-api-http的端口可以在`mirai/config/net.mamoe.mirai-api-http/setting.yml`找到，主程序连接的端口可以在`config.py`找到；但由于步骤较多，建议使用本仓库文档中的手动部署步骤进行部署。

非常感谢！已成功解决

**Comment by Jiaheliu137** [comment]
> 这一个是由于mirai-api-http的监听端口被占用导致的，建议更换端口，同时修改docker容器的端口映射，mirai-api-http的端口可以在`mirai/config/net.mamoe.mirai-api-http/setting.yml`找到，主程序连接的端口可以在`config.py`找到；但由于步骤较多，建议使用本仓库文档中的手动部署步骤进行部署。

更换端口是什么意思？改成什么样的？

**Comment by RockChinQ** [comment]
> > 这一个是由于mirai-api-http的监听端口被占用导致的，建议更换端口，同时修改docker容器的端口映射，mirai-api-http的端口可以在`mirai/config/net.mamoe.mirai-api-http/setting.yml`找到，主程序连接的端口可以在`config.py`找到；但由于步骤较多，建议使用本仓库文档中的手动部署步骤进行部署。
> 
> 更换端口是什么意思？改成什么样的？

随便换个端口，但是建议你手动部署

**Comment by Jiaheliu137** [comment]
> > > 这一个是由于mirai-api-http的监听端口被占用导致的，建议更换端口，同时修改docker容器的端口映射，mirai-api-http的端口可以在`mirai/config/net.mamoe.mirai-api-http/setting.yml`找到，主程序连接的端口可以在`config.py`找到；但由于步骤较多，建议使用本仓库文档中的手动部署步骤进行部署。
> > 
> > 
> > 更换端口是什么意思？改成什么样的？
> 
> 随便换个端口，但是建议你手动部署

就是手动部署的，现在已经将mirai和本项目的端口改成了8088
效果如下，出现新的报错：
File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1073, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 8088, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8088)
<img width="731" alt="截屏2023-02-14 01 04 44" src="https://user-images.githubusercontent.com/52644185/218509991-b4f586a4-e0dc-4386-8e1a-947dbcb38986.png">

**Comment by xionghaizhi** [comment]
> > 这一个是由于mirai-api-http的监听端口被占用导致的，建议更换端口，同时修改docker容器的端口映射，mirai-api-http的端口可以在`mirai/config/net.mamoe.mirai-api-http/setting.yml`找到，主程序连接的端口可以在`config.py`找到；但由于步骤较多，建议使用本仓库文档中的手动部署步骤进行部署。
> 
> 非常感谢！已成功解决

怎么改？/setting.yml 和config.py 中的两个端口不能一致？

**Comment by RockChinQ** [comment]
> > > 这一个是由于mirai-api-http的监听端口被占用导致的，建议更换端口，同时修改docker容器的端口映射，mirai-api-http的端口可以在`mirai/config/net.mamoe.mirai-api-http/setting.yml`找到，主程序连接的端口可以在`config.py`找到；但由于步骤较多，建议使用本仓库文档中的手动部署步骤进行部署。
> > 
> > 
> > 非常感谢！已成功解决
> 
> 怎么改？/setting.yml 和config.py 中的两个端口不能一致？

要求一致

**Comment by xionghaizhi** [comment]
> > > > 这一个是由于mirai-api-http的监听端口被占用导致的，建议更换端口，同时修改docker容器的端口映射，mirai-api-http的端口可以在`mirai/config/net.mamoe.mirai-api-http/setting.yml`找到，主程序连接的端口可以在`config.py`找到；但由于步骤较多，建议使用本仓库文档中的手动部署步骤进行部署。
> > > 
> > > 
> > > 非常感谢！已成功解决
> > 
> > 
> > 怎么改？/setting.yml 和config.py 中的两个端口不能一致？
> 
> 要求一致

好的 谢谢
