### ISSUE TITLE
[BUG]插件报错ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by Akinpzx** [RockChinQ/QChatGPT#131]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
   自动部署
- 系统环境：
    win11

**描述漏洞**  
导入了您推荐的插件QChatPlugin之后运行run-bot会出现no module named “yaml”且用powershell但应该是安装了yaml的
且安装插件时出现报错
**完整报错信息** 
yaml报错：
```
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\qqbot\QChatGPT\.\pkg\qqbot\command.py", line 281, in reload_task
    pkg.utils.reloader.reload_all()
  File "D:\qqbot\QChatGPT\.\pkg\utils\reloader.py", line 40, in reload_all
    walk(plugins)
  File "D:\qqbot\QChatGPT\.\pkg\utils\reloader.py", line 14, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.')
  File "D:\qqbot\QChatGPT\.\pkg\utils\reloader.py", line 14, in walk
    walk(__import__(module.__name__ + '.' + item.name, fromlist=['']), prefix + item.name + '.')
  File "D:\qqbot\QChatGPT\.\pkg\utils\reloader.py", line 17, in walk
    importlib.reload(__import__(module.__name__ + '.' + item.name, fromlist=['']))
  File "D:\qqbot\QChatGPT\.\plugins\QchatPlugins\BanMassage\main.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

```

安装插件报错
```
ERROR: Could not install packages due to an OSError: [WinError 5] 拒绝访问。: 'D:\\qqbot\\python\\Lib\\site-packages\\~~bsockets\\speedups.cp310-win_amd64.pyd'
Consider using the `--user` option or check the permissions.
```

**Comment by Akinpzx** [comment]
补充一下，我安装时使用了管理员打开那两个程序

**Comment by RockChinQ** [comment]
请到插件仓库反馈

**Comment by Akinpzx** [comment]
有可能不能用您那个自动安装的方法，需要手动安装，我先试试
