### ISSUE TITLE
[BUG]received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

### ISSUE THREAD

**Issue by 3205675095** [RockChinQ/QChatGPT#134]
怎么办怎么办
```
H:\下载\新建文件夹\QQbot\bot>cd QChatGPT

H:\下载\新建文件夹\QQbot\bot\QChatGPT>..\python\python.exe main.py
Database initialized.
[2023-02-11 21:47:29.949] keymgr.py (56) - [INFO] : 使用api-key:default
[2023-02-11 21:47:29.981] manager.py (74) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790]
2023-02-11 21:47:29 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-11 21:47:29.984] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-11 21:47:41.984] main.py (168) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息, 请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-02-11 21:47:47.399] manager.py (239) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新
Exception in thread Thread-2 (run):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 383, in set
    return await self._call_api(
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 232, in call_api
    await self.connection.send(json_dumps(content))
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在
```

**Comment by 3205675095** [comment]
再开几次就这样了 按什么键都直接闪退

H:\下载\新建文件夹\QQbot\bot>cd QChatGPT

H:\下载\新建文件夹\QQbot\bot\QChatGPT>..\python\python.exe main.py
Database initialized.
[2023-02-11 21:54:56.497] keymgr.py (56) - [INFO] : 使用api-key:default
[2023-02-11 21:54:56.529] manager.py (74) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790]
2023-02-11 21:54:56 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-11 21:54:56.532] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2023-02-11 21:55:00 - ERROR    无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。
[2023-02-11 21:55:00.543] base.py (40) - [ERROR] : 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确 。
[2023-02-11 21:55:00.547] main.py (143) - [ERROR] : 连接mirai-api-http失败:无法连接到 mirai。请检查 mirai-api-http 是否 启动，地址与端口是否正确。, 请检查是否已按照文档启动mirai

H:\下载\新建文件夹\QQbot\bot\QChatGPT>pause
请按任意键继续. . .

**Comment by RockChinQ** [comment]
请按照文档正确配置mirai并启动mirai

**Comment by 3205675095** [comment]
全部按照视频做了 是还有什么东西没下吗
大佬感谢了 本人小白

**Comment by RockChinQ** [comment]
启动了mirai了吗

**Comment by 3205675095** [comment]
启动了

**Comment by RockChinQ** [comment]
那么就检查`mirai/config/net.../settings.yml`写的端口和`QChatGPT/config.py`中`mirai_http_api_config`的端口是否一致，同时检查防火墙是否拦截此端口

**Comment by WchuiNi** [comment]
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2023-02-15 02:27:26.705] manager.py (28) - [INFO] : 文字总使用量：0
[2023-02-15 02:27:26.705] manager.py (77) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790]
[2023-02-15 02:27:26.706] host.py (60) - [INFO] : 加载插件
[2023-02-15 02:27:26.707] host.py (72) - [INFO] : 初始化插件
2023-02-15 02:27:26 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
WARNING: 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-15 02:27:26.708] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-15 02:27:38.716] main.py (194) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-02-15 02:27:44.110] manager.py (295) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 430, in __call__
    return await self.set(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 398, in set
    return await self._call_api(
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 386, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 318, in call
    raw_response = await self._call(api_provider, method)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 304, in _call
    return await api_provider.call_api(
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 320, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 232, in call_api
    await self.connection.send(json_dumps(content))
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

> 那么就检查`mirai/config/net.../settings.yml`写的端口和`QChatGPT/config.py`中`mirai_http_api_config`的端口是否一致，同时检查防火墙是否拦截此端口

我也遇到了这个问题，我是在linux中使用docker部署的，配置我看了都是一致的

**Comment by RockChinQ** [comment]
请确保mirai已登录机器人QQ，且config.py中mirai_http_api_config中的qq与mirai中登录的QQ相同

**Comment by RockChinQ** [comment]
> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv [2023-02-15 02:27:26.705] manager.py (28) - [INFO] : 文字总使用量：0 [2023-02-15 02:27:26.705] manager.py (77) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790] [2023-02-15 02:27:26.706] host.py (60) - [INFO] : 加载插件 [2023-02-15 02:27:26.707] host.py (72) - [INFO] : 初始化插件 2023-02-15 02:27:26 - WARNING 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn WARNING: 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn [2023-02-15 02:27:26.708] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn [2023-02-15 02:27:38.716] main.py (194) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 #37 [2023-02-15 02:27:44.110] manager.py (295) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新 Exception in thread Thread-3: Traceback (most recent call last): File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner self.run() File "/usr/local/lib/python3.9/threading.py", line 917, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 430, in **call** return await self.set(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 398, in set return await self._call_api( File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 386, in _call_api return await api.call(self.api_provider, method, response_type) File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 318, in call raw_response = await self._call(api_provider, method) File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 304, in _call return await api_provider.call_api( File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 320, in call_api return await self._adapter.call_api(api, *args, **kwargs) File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 232, in call_api await self.connection.send(json_dumps(content)) File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 635, in send await self.ensure_open() File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open raise self.connection_closed_exc() websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在
> 
> > 那么就检查`mirai/config/net.../settings.yml`写的端口和`QChatGPT/config.py`中`mirai_http_api_config`的端口是否一致，同时检查防火墙是否拦截此端口
> 
> 我也遇到了这个问题，我是在linux中使用docker部署的，配置我看了都是一致的

确保机器人已经把管理员账户加为好友

**Comment by WchuiNi** [comment]
> > WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv [2023-02-15 02:27:26.705] manager.py (28) - [INFO] : 文字总使用量：0 [2023-02-15 02:27:26.705] manager.py (77) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790] [2023-02-15 02:27:26.706] host.py (60) - [INFO] : 加载插件 [2023-02-15 02:27:26.707] host.py (72) - [INFO] : 初始化插件 2023-02-15 02:27:26 - WARNING 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn WARNING: 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn [2023-02-15 02:27:26.708] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn [2023-02-15 02:27:38.716] main.py (194) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 #37 [2023-02-15 02:27:44.110] manager.py (295) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新 Exception in thread Thread-3: Traceback (most recent call last): File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner self.run() File "/usr/local/lib/python3.9/threading.py", line 917, in run self._target(*self._args, **self._kwargs) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 430, in **call** return await self.set(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 398, in set return await self._call_api( File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 386, in _call_api return await api.call(self.api_provider, method, response_type) File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 318, in call raw_response = await self._call(api_provider, method) File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 304, in _call return await api_provider.call_api( File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 320, in call_api return await self._adapter.call_api(api, *args, **kwargs) File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 232, in call_api await self.connection.send(json_dumps(content)) File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 635, in send await self.ensure_open() File "/usr/local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open raise self.connection_closed_exc() websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在
> > > 那么就检查`mirai/config/net.../settings.yml`写的端口和`QChatGPT/config.py`中`mirai_http_api_config`的端口是否一致，同时检查防火墙是否拦截此端口
> > 
> > 
> > 我也遇到了这个问题，我是在linux中使用docker部署的，配置我看了都是一致的
> 
> 确保机器人已经把管理员账户加为好友

谢谢大佬，我发现我忘了登录mirai了

**Comment by drakhao** [comment]
我已经登录了，这怎么回事
![image](https://user-images.githubusercontent.com/125847557/220216439-b3b6b2f1-d608-4ae9-9cee-016805f5ef75.png)
