### ISSUE TITLE
Did not receive a valid HTTP response

### ISSUE THREAD

**Issue by DCPro-35** [RockChinQ/QChatGPT#15]
```
(base) [root@iZwz9clns9fhh6rwn6zeqgZ QChatGPT]# python3 main.py
2022-12-11 14:26:06 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2022-12-11 14:26:06.326] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2022-12-11 14:26:06.327] main.py (69) - [INFO] : 程序启动完成
2022-12-11 14:26:06 - ERROR    did not receive a valid HTTP response
[2022-12-11 14:26:06.331] base.py (43) - [ERROR] : did not receive a valid HTTP response
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/http.py", line 200, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/client.py", line 138, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/http.py", line 122, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/root/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/root/anaconda3/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/root/anaconda3/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/root/anaconda3/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/root/anaconda3/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/root/anaconda3/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/root/anaconda3/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/client.py", line 326, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/root/anaconda3/lib/python3.9/site-packages/websockets/legacy/client.py", line 144, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response
```

**Comment by RockChinQ** [comment]
看起来像是mirai或mirai-api-http没有正常运行导致的，检查一下mirai-api-http配置中设置的端口是否可以正常访问

**Comment by DCPro-35** [comment]
的确是mirai-api-http没有正常运行，我用code-server把端口占了，修改端口后已解决

**Comment by RockChinQ** [comment]
需要更换端口，方法见：https://github.com/RockChinQ/QChatGPT/issues/22
