### ISSUE TITLE
[BUG]chatwaifu插件中文英语输出语音都正常，但回复内容是日语就报错

### ISSUE THREAD

**Issue by ygmz233** [RockChinQ/QChatGPT#162]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
     windows11 x64

**描述漏洞**  
报错于bot端

chatwaifu中文英语输出语音都正常，但回复内容是日语就报错
**完整报错信息**  
```Pyhon
[2023-02-02 20:16:45.321] host.py (273) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误
[2023-02-02 20:16:45.322] host.py (274) - [ERROR] : Traceback (most recent call last):
File "E:\桌面\QQbot\bot\QChatGPT.\pkg\plugin\host.py", line 263, in emit
hook(plugin['instance'], **kwargs)
File "E:\桌面\QQbot\bot\QChatGPT.\plugins\QchatPlugins-master\ChatWaifu\main.py", line 34, in group_normal_message_received
kwargs['host'].send_group_message(kwargs["launcher_id"], voice)
File "E:\桌面\QQbot\bot\QChatGPT.\pkg\plugin\host.py", line 232, in send_group_message
asyncio.run(self.get_bot().send_group_message(group, message))
File "asyncio\runners.py", line 44, in run
File "asyncio\base_events.py", line 649, in run_until_complete
File "E:\桌面\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 415, in call
return await self.set(*args, **kwargs)
File "E:\桌面\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 383, in set
return await self._call_api(
File "E:\桌面\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
return await api.call(self.api_provider, method, response_type)
File "E:\桌面\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 304, in call
raw_response = await api_provider.call_api(
File "E:\桌面\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 91, in call_api
return await self._adapter.call_api(api, *args, **kwargs)
File "E:\桌面\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 236, in call_api
return await self._recv(sync_id)
File "E:\桌面\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 165, in _recv
raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'message is empty')
```

**Comment by RockChinQ** [comment]
外部插件问题请前往插件仓库反馈 https://github.com/dominoar/QchatPlugins
