### ISSUE TITLE
能不能让群友或者特定QQ也能！reload吖[ENHANCE]

### ISSUE THREAD

**Issue by r5rinimaa** [RockChinQ/QChatGPT#178]
这样可以缓解rev一小时的限制

**Comment by RockChinQ** [comment]
可以到revcfg.py设置多个ChatGPT账号，以便1小时限制时自动切换

**Comment by RockChinQ** [comment]
feat: 支持多管理员

**Comment by r5rinimaa** [comment]
您好 并不会自动切换，只有!reload 才会切换 另外请问多管理员的格式是什么

**Comment by RockChinQ** [comment]
> 您好 并不会自动切换，只有!reload 才会切换 另外请问多管理员的格式是什么
> 

你是如何判断未切换的？逆向库的多账户算法与主程序不同，会存在多个账户同时使用的情况；若有报错请提供控制台截图

**Comment by RockChinQ** [comment]
你需要清楚，不是所有报错都会引起账号切换，仅当报错消息中包含1小时内请求过多时才会切换

**Comment by r5rinimaa** [comment]
[2023-02-24 16:23:00.831] V1.py (256) - [ERROR] : Error parsing JSON
Traceback (most recent call last):
  File "C:\aaa\python\lib\site-packages\revChatGPT\V1.py", line 254, in ask
    continue
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Stack (most recent call last):
  File "threading.py", line 973, in _bootstrap
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\aaa\python\lib\site-packages\func_timeout\dafunc.py", line 68, in funcwrap
    ret.append( func(*args2, **kwargs2) )
  File "C:\aaa\QChatGPT\.\pkg\qqbot\manager.py", line 227, in time_ctrl_wrapper
    reply = processor.process_message('person', event.sender.id, str(event.message_chain),
  File "C:\aaa\QChatGPT\.\pkg\qqbot\process.py", line 107, in process_message
    event = plugin_host.emit(plugin_models.PersonNormalMessageReceived
  File "C:\aaa\QChatGPT\.\pkg\plugin\host.py", line 237, in emit
    return context.get_plugin_host().emit(event_name, **kwargs)
  File "C:\aaa\QChatGPT\.\pkg\plugin\host.py", line 296, in emit
    hook(plugin['instance'], **kwargs)
  File "C:\aaa\QChatGPT\.\plugins\revLibs\main.py", line 88, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 47, in process_message
    for section in session.get_reply(prompt):
  File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 55, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 52, in get_reply
    for r in reply_gen:
  File "C:\aaa\python\lib\site-packages\revChatGPT\V1.py", line 256, in ask
    line = line[6:]

**Comment by r5rinimaa** [comment]
[2023-02-24 16:28:15.760] V1.py (43) - [INFO] : Exiting ask with return value <generator object Chatbot.ask at 0x00000246AD8977D0>. Took 0.0 seconds.
[2023-02-24 16:28:43.654] V1.py (33) - [INFO] : Entering __check_response with args (<revChatGPT.V1.Chatbot object at 0x00000246A9960A30>, <Response [200]>) and kwargs {}
Traceback (most recent call last):
  File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 761, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
    yield
  File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 828, in read_chunked
    self._update_chunk_length()
  File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 765, in _update_chunk_length
    raise InvalidChunkLength(self, line)
urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\aaa\python\lib\site-packages\requests\models.py", line 816, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 816, in read_chunked
    with self._error_catcher():
  File "contextlib.py", line 153, in __exit__
  File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 47, in process_message
    for section in session.get_reply(prompt):
  File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 55, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 72, in get_reply
    raise e
  File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 52, in get_reply
    for r in reply_gen:
  File "C:\aaa\python\lib\site-packages\revChatGPT\V1.py", line 235, in ask
    log.debug(json.dumps(data, indent=2))
  File "C:\aaa\python\lib\site-packages\revChatGPT\V1.py", line 40, in wrapper
    out = func(*args, **kwargs)
  File "C:\aaa\python\lib\site-packages\revChatGPT\V1.py", line 291, in __check_response
    self.conversation_mapping[conversation_id] = parent_id
  File "C:\aaa\python\lib\site-packages\requests\models.py", line 793, in apparent_encoding
    return chardet.detect(self.content)["encoding"]
  File "C:\aaa\python\lib\site-packages\requests\models.py", line 899, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "C:\aaa\python\lib\site-packages\requests\models.py", line 818, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

**Comment by RockChinQ** [comment]
> ```
> [2023-02-24 16:28:43.654] V1.py (33) - [INFO] : Entering __check_response with args (<revChatGPT.V1.Chatbot object at 0x00000246A9960A30>, <Response [200]>) and kwargs {}
> Traceback (most recent call last):
>   File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 761, in _update_chunk_length
>     self.chunk_left = int(line, 16)
> ValueError: invalid literal for int() with base 16: b''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 444, in _error_catcher
>     yield
>   File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 828, in read_chunked
>     self._update_chunk_length()
>   File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 765, in _update_chunk_length
>     raise InvalidChunkLength(self, line)
> urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\aaa\python\lib\site-packages\requests\models.py", line 816, in generate
>     yield from self.raw.stream(chunk_size, decode_content=True)
>   File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 624, in stream
>     for line in self.read_chunked(amt, decode_content=decode_content):
>   File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 816, in read_chunked
>     with self._error_catcher():
>   File "contextlib.py", line 153, in __exit__
>   File "C:\aaa\python\lib\site-packages\urllib3\response.py", line 461, in _error_catcher
>     raise ProtocolError("Connection broken: %r" % e, e)
> urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 47, in process_message
>     for section in session.get_reply(prompt):
>   File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 55, in get_reply
>     for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
>   File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 72, in get_reply
>     raise e
>   File "C:\aaa\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 52, in get_reply
>     for r in reply_gen:
>   File "C:\aaa\python\lib\site-packages\revChatGPT\V1.py", line 235, in ask
>     log.debug(json.dumps(data, indent=2))
>   File "C:\aaa\python\lib\site-packages\revChatGPT\V1.py", line 40, in wrapper
>     out = func(*args, **kwargs)
>   File "C:\aaa\python\lib\site-packages\revChatGPT\V1.py", line 291, in __check_response
>     self.conversation_mapping[conversation_id] = parent_id
>   File "C:\aaa\python\lib\site-packages\requests\models.py", line 793, in apparent_encoding
>     return chardet.detect(self.content)["encoding"]
>   File "C:\aaa\python\lib\site-packages\requests\models.py", line 899, in content
>     self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
>   File "C:\aaa\python\lib\site-packages\requests\models.py", line 818, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
> ```

这个不清楚是什么问题，应该是网络不太好

**Comment by RockChinQ** [comment]
现已更新，请更新主程序，并在`config.py`中设置多管理员，可以参考`config-template.py`中关于`admin_qq`字段的注释
