### ISSUE TITLE
[BUG]接收消息的时候，python asyncio库文件报错，有时会自动退出程序

### ISSUE THREAD

**Issue by niezhe** [RockChinQ/QChatGPT#179]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署
- 系统环境：
    win10
- Python环境（仅手动部署填写）：
    例如： 3.9.10

**报错描述**  
接收消息的时候，python asyncio库文件报错，有时候会自动退出程序

**完整报错信息**  

```Traceback (most recent call last):
  File "D:\python3.9\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001D553F56270> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "D:\python3.9\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001D553F56270> still has pending operation at deallocation, the process may crash```

**Comment by niezhe** [comment]
### pythonlog
`[2023-02-25 15:41:04.018] message.py (27) - [INFO] : [person_]发送消息:测试机器人
[2023-02-25 15:41:04.018] util.py (67) - [INFO] : message='Request to OpenAI API' method=post path=https://api.openai.com/v1/completions
[2023-02-25 15:41:10.289] util.py (67) - [INFO] : message='OpenAI API response' path=https://api.openai.com/v1/completions processing_ms=5563 request_id= response_code=200
[2023-02-25 15:41:10.351] process.py (119) - [INFO] : 回复[person_]文字消息:你可以尝试使用 Python 来创建一个机器人，它可以通过聊天或命令行来处理用户输入。可以使用框架和库，如 NLTK、ChatterBot、Rasa 等来开始你的测试机器人项目。
Traceback (most recent call last):
  File "D:\python3.9\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001D553FB0DB0> still has pending operation at deallocation, the process may crash
Traceback (most recent call last):
  File "D:\python3.9\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001D553FB0DB0> still has pending operation at deallocation, the process may crash`

### mirai log
`2023-02-25 15:41:03 V/Bot.: () -> 测试机器人
2023-02-25 15:41:03 E/Mah Debug: java.util.concurrent.CancellationException: ArrayChannel was cancelled
java.util.concurrent.CancellationException: ArrayChannel was cancelled
        at kotlinx.coroutines.channels.AbstractChannel.cancel(AbstractChannel.kt:656)
        at kotlinx.coroutines.channels.ReceiveChannel$DefaultImpls.cancel$default(Channel.kt:279)
        at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.websocket.DefaultWebSocketSessionImpl$runOutgoingProcessor$1.invokeSuspend(DefaultWebSocketSession.kt:228)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:245)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:183)
        at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:190)
        at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1475)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:900)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:747)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
        at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:549)
        at kotlinx.coroutines.JobKt.cancel(Unknown Source)
        at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:548)
        at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
        at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.server.cio.backend.ServerPipelineKt$startServerConnectionPipeline$1.invokeSuspend(ServerPipeline.kt:180)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-25 15:41:03 E/Mah Debug: java.util.concurrent.CancellationException: ArrayChannel was cancelled
java.util.concurrent.CancellationException: ArrayChannel was cancelled
        at kotlinx.coroutines.channels.AbstractChannel.cancel(AbstractChannel.kt:656)
        at kotlinx.coroutines.channels.ReceiveChannel$DefaultImpls.cancel$default(Channel.kt:279)
        at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.websocket.DefaultWebSocketSessionImpl$runOutgoingProcessor$1.invokeSuspend(DefaultWebSocketSession.kt:228)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:245)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:183)
        at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:190)
        at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1475)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:900)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:747)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
        at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:549)
        at kotlinx.coroutines.JobKt.cancel(Unknown Source)
        at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:548)
        at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
        at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.server.cio.backend.ServerPipelineKt$startServerConnectionPipeline$1.invokeSuspend(ServerPipeline.kt:180)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-25 15:41:10 V/Bot.3300488495: Friend() <- 你可以尝试使用 Python 来创建一个机器人，它可以通过聊天或命令 行来处理用户输入。可以使用框架和库，如 NLTK、ChatterBot、Rasa 等来开始你的测试机器人项目。`

**Comment by RockChinQ** [comment]
你是自己把日志中的QQ号删掉了吗？

**Comment by niezhe** [comment]
是的，只删除了QQ号

**Comment by RockChinQ** [comment]
不清楚是什么问题，可以重启或者重装试试看

**Comment by niezhe** [comment]
python asyncio这个库里面报错，是应为回调超时了吗？

**Comment by RockChinQ** [comment]
> python asyncio这个库里面报错，是应为回调超时了吗？

这个库的报错通常是由于调用方导致的，可能是yirimirai的代码引起的，但此报错从未见过

**Comment by niezhe** [comment]
> > python asyncio这个库里面报错，是应为回调超时了吗？
> 
> 这个库的报错通常是由于调用方导致的，可能是yirimirai的代码引起的，但此报错从未见过

好的谢谢，我重装下mirai试下看看

**Comment by niezhe** [comment]
`[program:cancel]
command=D:\\code\\QChatGPT\\venv\\Scripts\\python.exe D:\\code\\QChatGPT\\main.py

[supervisord]
nodaemon=true

[supervisorctl]`

`supervisord -c D:\code\QChatGPT\supervisord.conf`

使用守护进程方式解决程序自动退出的问题

**Comment by RichardWang2023** [comment]
这个可能是操作系统的问题，如果更改事件循环策略有效果的话
`asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())`
你现在解决了吗？
