### ISSUE TITLE
请问这个该怎么解决 received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

### ISSUE THREAD

**Issue by akenaizi** [RockChinQ/QChatGPT#199]
[2023-03-03 10:11:21.168] manager.py (293) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新
Exception in thread Thread-2 (run):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "B:\chat2\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "B:\chat2\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 383, in set
    return await self._call_api(
  File "B:\chat2\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "B:\chat2\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "B:\chat2\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "B:\chat2\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 232, in call_api
    await self.connection.send(json_dumps(content))
  File "B:\chat2\QQbot\bot\python\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "B:\chat2\QQbot\bot\python\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

**Comment by RockChinQ** [comment]
确保mirai登录的QQ和你config.py的`mirai_http_api_config`中的QQ是同一个
