### ISSUE TITLE
[BUG]ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] 及[ERROR] : string indices must be integers

### ISSUE THREAD

**Issue by deadnessking** [RockChinQ/QChatGPT#201]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    使用安装器安装
- 系统环境：
    Winserver2019

**描述漏洞**  
mirai已经配置好没问题，代理也设置了确定可以上api.openai.com。但是对话后回复错误：[bot]err:string indices must be integers
看后台主要是这两条Error
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)
还有[2023-03-03 16:54:48.657] message.py (125) - [ERROR] : string indices must be integers

**完整报错信息**  
[2023-03-03 16:54:47.820] message.py (28) - [INFO] : [person_101922237]发送消息:在吗
Exception in thread Thread-6 (run_until_complete):
Traceback (most recent call last):
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\aiohttp\connector.py", line 1091, in _start_tls_connection
    tls_transport = await self._loop.start_tls(
  File "asyncio\base_events.py", line 1247, in start_tls
  File "asyncio\sslproto.py", line 534, in data_received
  File "asyncio\sslproto.py", line 188, in feed_ssldata
  File "ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\openai\api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\aiohttp\connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\aiohttp\connector.py", line 1325, in _create_proxy_connection
    return await self._start_tls_connection(
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\aiohttp\connector.py", line 1105, in _start_tls_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.openai.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Soft\GptQQ\RockChinQ-old\QChatGPT\.\pkg\openai\modelmgr.py", line 44, in __a_request__
    self.ret = await self.request_fun(**kwargs)
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\openai\api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "C:\Soft\GptQQ\RockChinQ-old\python\lib\site-packages\openai\api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
[2023-03-03 16:54:48.657] message.py (125) - [ERROR] : string indices must be integers
Traceback (most recent call last):
  File "C:\Soft\GptQQ\RockChinQ-old\QChatGPT\.\pkg\qqbot\message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "C:\Soft\GptQQ\RockChinQ-old\QChatGPT\.\pkg\openai\session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "C:\Soft\GptQQ\RockChinQ-old\QChatGPT\.\pkg\openai\manager.py", line 59, in request_completion
    return ai.get_message()
  File "C:\Soft\GptQQ\RockChinQ-old\QChatGPT\.\pkg\openai\modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 16:54:48.662] manager.py (307) - [INFO] : 通知管理员:person_101922237会话处理异常:string indices must be integers
[2023-03-03 16:54:48.666] process.py (150) - [INFO] : 回复[person_101922237]文字消息:[bot]err:string indices must be integers
[2023-03-03 16:54:48.782] main.py (263) - [INFO] : 当前已是最新版本

**Comment by LINSTCL** [comment]
用的是系统代理吗？还是刚更新的config.py中的代理？

**Comment by deadnessking** [comment]
> 用的是系统代理吗？还是刚更新的config.py中的代理？

是clash的系统代理，在config里设置了。
openai_config = {
    "api_key": {
        "default": "**API**"
    },
    "http_proxy": "http://127.0.0.1:7890"
}

**Comment by XuanRanDev** [comment]
在使用代理时同样出现这个问题：
```shell
2023-03-03 15:17:42 - INFO     [WebSocket] 成功登录到账号xxxx。
[2023-03-03 15:17:42.950] websocket.py (194) - [INFO] : [WebSocket] 成功登录到账号xxxxx。
2023-03-03 15:17:42 - INFO     [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-03-03 15:17:42.951] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-03-03 15:17:54.850] main.py (232) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-03-03 15:17:56.905] message.py (28) - [INFO] : [person_3xxxxxxx]发送消息:1
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 127.0.0.1:15777

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/bot/pkg/openai/modelmgr.py", line 44, in __a_request__
    self.ret = await self.request_fun(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
ERROR: string indices must be integers
Traceback (most recent call last):
  File "/bot/pkg/qqbot/message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "/bot/pkg/openai/session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "/bot/pkg/openai/manager.py", line 59, in request_completion
    return ai.get_message()
  File "/bot/pkg/openai/modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 15:17:57.051] message.py (125) - [ERROR] : string indices must be integers
Traceback (most recent call last):
  File "/bot/pkg/qqbot/message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "/bot/pkg/openai/session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "/bot/pkg/openai/manager.py", line 59, in request_completion
    return ai.get_message()
  File "/bot/pkg/openai/modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 15:17:57.055] manager.py (307) - [INFO] : 通知管理员:person_3xxxxxxx会话处理异常:string indices must be integers
[2023-03-03 15:17:57.057] process.py (150) - [INFO] : 回复[person_3xxxxxxxxxxxx9]文字消息:[bot]err:string indices must be integers
[2023-03-03 15:18:00.370] main.py (263) - [INFO] : 当前已是最新版本
[2023-03-03 15:18:03.737] message.py (28) - [INFO] : [person_31xxxxxxxxxxxxx]发送消息:你好
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 127.0.0.1:15777

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/bot/pkg/openai/modelmgr.py", line 44, in __a_request__
    self.ret = await self.request_fun(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
ERROR: string indices must be integers
Traceback (most recent call last):
  File "/bot/pkg/qqbot/message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "/bot/pkg/openai/session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "/bot/pkg/openai/manager.py", line 59, in request_completion
    return ai.get_message()
  File "/bot/pkg/openai/modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 15:18:03.837] message.py (125) - [ERROR] : string indices must be integers
Traceback (most recent call last):
  File "/bot/pkg/qqbot/message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "/bot/pkg/openai/session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "/bot/pkg/openai/manager.py", line 59, in request_completion
    return ai.get_message()
  File "/bot/pkg/openai/modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 15:18:03.838] manager.py (307) - [INFO] : 通知管理员:person_3xxxxxxxxxxxx会话处理异常:string indices must be integers
[2023-03-03 15:18:03.839] process.py (150) - [INFO] : 回复[person_3xxxxxxxxxxxx9]文字消息:[bot]err:string indices must be integers
[root@xuanran net.mamoe.mirai-api-http]# 
```

**Comment by RockChinQ** [comment]
#205

**Comment by RockChinQ** [comment]
@LINSTCL 这可能是由于请求失败、获取到空信息时程序不正确的处理导致的，麻烦看一下啊
```
[2023-03-04 21:27:45.590] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-03-04 21:27:52.951] message.py (29) - [INFO] : [person_1010553892]发送消息:使用Java写一个快速排序
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 1120, in _create_connection_transport
    await waiter
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 534, in send
    self._register_with_iocp(conn)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\windows_events.py", line 723, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 87] 参数错误。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\client.py", line 520, in _request
    conn = await self._connector.connect(
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\connector.py", line 890, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\connector.py", line 1139, in _create_proxy_connection
    transport, proto = await self._wrap_create_connection(
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiohttp\connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.openai.com:443 ssl:default [参数错误。]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\10105\PycharmProjects\QChatGPT\pkg\openai\modelmgr.py", line 44, in __a_request__
    self.ret = await self.request_fun(**kwargs)
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "C:\Users\10105\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\openai\api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
[2023-03-04 21:27:56.817] gatherer.py (39) - [WARNING] : report to server failed, status_code: 502, text: 
[2023-03-04 21:27:56.819] message.py (126) - [ERROR] : string indices must be integers
Traceback (most recent call last):
  File "C:\Users\10105\PycharmProjects\QChatGPT\pkg\qqbot\message.py", line 46, in process_normal_message
    text = session.append(text_message)
  File "C:\Users\10105\PycharmProjects\QChatGPT\pkg\openai\session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "C:\Users\10105\PycharmProjects\QChatGPT\pkg\openai\manager.py", line 59, in request_completion
    return ai.get_message()
  File "C:\Users\10105\PycharmProjects\QChatGPT\pkg\openai\modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-04 21:27:56.836] manager.py (307) - [INFO] : 通知管理员:person_1010553892会话处理异常:string indices must be integers
[2023-03-04 21:27:56.840] process.py (150) - [INFO] : 回复[person_1010553892]文字消息:[bot]err:string indices must be integers
```

**Comment by LINSTCL** [comment]
@RockChinQ ，我只能提个pr加个错误上报，让不要直接甩错误，然后请求不到的时候直接返回空数据
还有就是开系统代理有时候会报SSL错误，把系统代理关了直接走软件proxy应该会正常，或者就是这个用户节点有问题，可能屏蔽了一些流量

**Comment by RockChinQ** [comment]
> @RockChinQ ，我只能提个pr加个错误上报，让不要直接甩错误，然后请求不到的时候直接返回空数据 还有就是开系统代理有时候会报SSL错误，把系统代理关了直接走软件proxy应该会正常，或者就是这个用户节点有问题，可能屏蔽了一些流量

只要程序能检测到报错、区分清楚是否是代理地址不正确就行，然后可以抛一个自定义异常来提示用户

**Comment by deadnessking** [comment]
我把 "http_proxy":改回None就正常了，能用就先用着

**Comment by RockChinQ** [comment]
这个问题通常在以下情况复现：代理软件设置了系统代理，程序能自动走代理，但仍在http_proxy填写了代理地址。  
可以直接将http_proxy改为`None`来使程序走自动选择的系统代理来解决
