### ISSUE TITLE
[BUG]err:string indices must be integers

### ISSUE THREAD

**Issue by XuanRanDev** [RockChinQ/QChatGPT#205]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    例如： Centos x64

**描述漏洞**  
主程序，能正常访问api.openai.com

**完整报错信息**  
```shell
2023-03-03 15:17:42 - INFO     [WebSocket] 成功登录到账号xxxx。
[2023-03-03 15:17:42.950] websocket.py (194) - [INFO] : [WebSocket] 成功登录到账号xxxxx。
2023-03-03 15:17:42 - INFO     [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-03-03 15:17:42.951] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-03-03 15:17:54.850] main.py (232) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-03-03 15:17:56.905] message.py (28) - [INFO] : [person_3xxxxxxx]发送消息:1
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 127.0.0.1:15777

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/bot/pkg/openai/modelmgr.py", line 44, in __a_request__
    self.ret = await self.request_fun(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
ERROR: string indices must be integers
Traceback (most recent call last):
  File "/bot/pkg/qqbot/message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "/bot/pkg/openai/session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "/bot/pkg/openai/manager.py", line 59, in request_completion
    return ai.get_message()
  File "/bot/pkg/openai/modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 15:17:57.051] message.py (125) - [ERROR] : string indices must be integers
Traceback (most recent call last):
  File "/bot/pkg/qqbot/message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "/bot/pkg/openai/session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "/bot/pkg/openai/manager.py", line 59, in request_completion
    return ai.get_message()
  File "/bot/pkg/openai/modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 15:17:57.055] manager.py (307) - [INFO] : 通知管理员:person_3xxxxxxx会话处理异常:string indices must be integers
[2023-03-03 15:17:57.057] process.py (150) - [INFO] : 回复[person_3xxxxxxxxxxxx9]文字消息:[bot]err:string indices must be integers
[2023-03-03 15:18:00.370] main.py (263) - [INFO] : 当前已是最新版本
[2023-03-03 15:18:03.737] message.py (28) - [INFO] : [person_31xxxxxxxxxxxxx]发送消息:你好
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 899, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1221, in _create_proxy_connection
    proxy_req = ClientRequest(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 305, in __init__
    self.update_host(url)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 364, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL: 127.0.0.1:15777

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/bot/pkg/openai/modelmgr.py", line 44, in __a_request__
    self.ret = await self.request_fun(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "/usr/local/lib/python3.9/site-packages/openai/api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI
ERROR: string indices must be integers
Traceback (most recent call last):
  File "/bot/pkg/qqbot/message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "/bot/pkg/openai/session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "/bot/pkg/openai/manager.py", line 59, in request_completion
    return ai.get_message()
  File "/bot/pkg/openai/modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 15:18:03.837] message.py (125) - [ERROR] : string indices must be integers
Traceback (most recent call last):
  File "/bot/pkg/qqbot/message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "/bot/pkg/openai/session.py", line 203, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "/bot/pkg/openai/manager.py", line 59, in request_completion
    return ai.get_message()
  File "/bot/pkg/openai/modelmgr.py", line 107, in get_message
    return self.ret["choices"][0]["message"]['content'] #需要时直接加载加快请求速度，降低内存消耗
TypeError: string indices must be integers
[2023-03-03 15:18:03.838] manager.py (307) - [INFO] : 通知管理员:person_3xxxxxxxxxxxx会话处理异常:string indices must be integers
[2023-03-03 15:18:03.839] process.py (150) - [INFO] : 回复[person_3xxxxxxxxxxxx9]文字消息:[bot]err:string indices must be integers
[root@xuanran net.mamoe.mirai-api-http]# 
```

**Comment by XuanRanDev** [comment]
已解决，代理少了http前缀
