### ISSUE TITLE
运行“run-mirai.bat”时出现问题

### ISSUE THREAD

**Issue by Leocjy** [RockChinQ/QChatGPT#21]

**Comment by RockChinQ** [comment]
麻烦再运行一次run-mirai.bat，保存完整运行信息，以文字的形式回复此issue

**Comment by Leocjy** [comment]
`Y:\OpenAIBotForQQ>run-mirai.bat

Y:\OpenAIBotForQQ>cd mirai/

Y:\OpenAIBotForQQ\mirai>java\bin\java -jar mcl.jar
  12:25:25 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  12:25:25 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.5 (arch: 64)
  12:25:25 [INFO] https://github.com/iTXTech/mirai-console-loader
  12:25:25 [INFO] This program is licensed under GNU AGPL v3
  12:25:26 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  12:25:26 [INFO] Verifying "net.mamoe:mirai-console" v2.13.2
  12:25:26 [ERROR] "net.mamoe:mirai-console" is corrupted.
  12:25:29 [INFO] Updating "net.mamoe:mirai-console" to v2.13.2
  12:25:39 [ERROR] javax.net.ssl.SSLHandshakeException: Remote host terminated the handshakeB (93.3%)
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.followRedirect(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at org.itxtech.mcl.module.builtin.MDownloader$DownloadTask.run(MDownloader.java:149)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        ... 17 more

 Downloading mirai-console-2.13.2-all.jar [==============================] 7.36 MB
  12:25:43 [ERROR] java.io.IOException: EOF reached while reading
 Downloading mirai-console-2.13.2-all.jar.sha1 [==============================]
  12:25:44 [ERROR] The local file "net.mamoe:mirai-console" is still corrupted, please check the network.
  12:25:44 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.2
  12:25:46 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.2
  12:25:46 [ERROR] "net.mamoe:mirai-core-all" is corrupted.
  12:25:47 [INFO] Updating "net.mamoe:mirai-core-all" to v2.13.2
  12:25:55 [ERROR] javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake2 MB (35.9%)
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at org.itxtech.mcl.module.builtin.MDownloader$DownloadTask.run(MDownloader.java:148)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        ... 13 more

 Downloading mirai-core-all-2.13.2-all.jar [==============================] 36.02 MB
 Downloading mirai-core-all-2.13.2-all.jar.sha1 [==============================] 40 B
  12:26:29 [ERROR] The local file "net.mamoe:mirai-core-all" is still corrupted, please check the network.
  12:26:29 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  12:26:31 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2
  12:26:31 [ERROR] java.util.zip.ZipException: invalid END header (bad central directory offset)
        at java.base/java.util.zip.ZipFile$Source.zerror(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:83)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)

`

**Comment by Leocjy** [comment]
这是再次运行的结果
Y:\OpenAIBotForQQ>run-mirai.bat

Y:\OpenAIBotForQQ>cd mirai/

Y:\OpenAIBotForQQ\mirai>java\bin\java -jar mcl.jar
  12:31:31 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  12:31:31 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.5 (arch: 64)
  12:31:31 [INFO] https://github.com/iTXTech/mirai-console-loader
  12:31:31 [INFO] This program is licensed under GNU AGPL v3
  12:31:32 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  12:31:32 [INFO] Verifying "net.mamoe:mirai-console" v2.13.2
  12:31:32 [ERROR] "net.mamoe:mirai-console" is corrupted.
  12:31:37 [INFO] Updating "net.mamoe:mirai-console" to v2.13.2
 Downloading mirai-console-2.13.2-all.jar [==============================] 7.36 MB
 Downloading mirai-console-2.13.2-all.jar.sha1 [==============================] 40 B
  12:32:15 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.2
  12:32:18 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.2
  12:32:18 [ERROR] "net.mamoe:mirai-core-all" is corrupted.
  12:32:18 [INFO] Updating "net.mamoe:mirai-core-all" to v2.13.2
  12:32:29 [ERROR] javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake2 MB (24.4%)
        at java.base/sun.security.ssl.SSLSocketImpl.handleEOF(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
        at org.itxtech.mcl.module.builtin.MDownloader$DownloadTask.run(MDownloader.java:148)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at java.base/sun.security.ssl.SSLSocketInputRecord.read(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketInputRecord.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        ... 13 more

 Downloading mirai-core-all-2.13.2-all.jar [==============================] 36.02 MB
 Downloading mirai-core-all-2.13.2-all.jar.sha1 [==============================] 40 B
  12:33:49 [ERROR] The local file "net.mamoe:mirai-core-all" is still corrupted, please check the network.
  12:33:49 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  12:33:51 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2
  12:33:51 [ERROR] java.util.zip.ZipException: zip END header not found
        at java.base/java.util.zip.ZipFile$Source.findEND(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.initCEN(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile$Source.get(Unknown Source)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.zip.ZipFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at java.base/java.util.jar.JarFile.<init>(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:83)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
