### ISSUE TITLE
[BUG]登录失败 Connection timed out

### ISSUE THREAD

**Issue by Qinggao1729** [RockChinQ/QChatGPT#214]
**运行环境**
- 部署方式：
    安装器部署
- 系统环境：
    例如： Windows 11 x64
- 人在美国

**描述漏洞**  
运行run-mirai.bat，输入账号密码后报错connection timed out

**完整报错信息**  
```bash
> login *** ***
Login failed: Connection timed out: no further information: msfwifi.3g.qq.com/43.135.106.161:8080
2023-03-04 11:52:44 E/console: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: msfwifi.3g.qq.com/43.135.106.161:8080
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: msfwifi.3g.qq.com/43.135.106.161:8080
        Suppressed: NettyChannelException(message=null, cause=io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: msfwifi.3g.qq.com/43.135.106.161:8080)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.createConnection$suspendImpl(NettyNetworkHandler.kt:116)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$createConnection$1.invokeSuspend(NettyNetworkHandler.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Caused by: [CIRCULAR REFERENCE: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: msfwifi.3g.qq.com/43.135.106.161:8080]
Caused by: java.net.ConnectException: Connection timed out: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

2023-03-04 11:52:44 I/Bot.3627180263: Bot cancelled: Bot closed
>
```
前面有显示`W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用`，不知道是否有关

**Comment by RockChinQ** [comment]
这是mirai无法连接到QQ服务器导致的。  
主机在美国？近期敏感时期gfw审查严格，建议使用境内主机进行登录。

**Comment by Qinggao1729** [comment]
> 这是mirai无法连接到QQ服务器导致的。 主机在美国？近期敏感时期gfw审查严格，建议使用境内主机进行登录。

那还有什么其他办法吗

**Comment by mengzuihuawu** [comment]
> 

实测新加坡可以

**Comment by RockChinQ** [comment]
> > 这是mirai无法连接到QQ服务器导致的。 主机在美国？近期敏感时期gfw审查严格，建议使用境内主机进行登录。
> 
> 那还有什么其他办法吗

这是mirai连不上，我也不太清楚具体解决办法，你可以去 mamoe/mirai 的issues去反馈一下，他们应该更加了解，我这边就先关闭了
