### ISSUE TITLE
[BUG] !reload 重新加载以后首次对话报错

### ISSUE THREAD

**Issue by HaanJam** [RockChinQ/QChatGPT#234]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    例如： debian11

**描述漏洞**  
!reload 命令重新加载以后报错
**完整报错信息**  
[2023-03-06 10:12:16.134] main.py (264) - [INFO] : 热重载完成
[2023-03-06 10:12:21.458] main.py (290) - [INFO] : 当前已是最新版本
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/mirai/utils.py", line 20, in async_with_exception
    return await async_(obj)
  File "/usr/local/lib/python3.9/site-packages/mirai/utils.py", line 14, in async_
    return (await obj) if inspect.isawaitable(obj) else obj
  File "/bot/pkg/qqbot/manager.py", line 119, in on_friend_message
    self.go(friend_message_handler, event)
  File "/bot/pkg/qqbot/manager.py", line 177, in go
    self.pool.submit(func, *args, **kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown

**Comment by RockChinQ** [comment]
用!version指令看看版本

**Comment by HaanJam** [comment]
> 用!version指令看看版本

[bot]当前版本:
v2.1.3 线程控制、依赖库更新问题
## What's Changed
* 启动时，更新openai和pillow库超时问题 by @yichuxue in https://github.com/RockChinQ/QChatGPT/pull/228
* 使用线程池控制线程数量，防止高并发崩溃 by @LINSTCL in https://github.com/RockChinQ/QChatGPT/pull/222
* 添加配置文件完整性校验 by @LINSTCL in https://github.com/RockChinQ/QChatGPT/pull/230

## New Contributors
* @yichuxue made their first contribution in https://github.com/RockChinQ/QChatGPT/pull/228

**Full Changelog**: https://github.com/RockChinQ/QChatGPT/compare/v2.1.2...v2.1.3

**Comment by Ludovicofu** [comment]
对，更新到这个版本后，!reload再执行docker compose run -itd setup无法启动容器

**Comment by RockChinQ** [comment]
已确定是bug，预计明日修复
