### ISSUE TITLE
[BUG]更新2.1.3之后出现的问题

### ISSUE THREAD

**Issue by EricMeteorite** [RockChinQ/QChatGPT#237]
请认真按照实际情况填写以下信息！！！！

**运行环境**
Ubuntu22.04 LTS
- 部署方式：
    手动部署
- 系统环境：
   Ubuntu22.04 LTS x86_x64

**描述漏洞**  
更新完2.1.3版本的bot之后发现的问题，2.1.2没有问题。
暂时没有影响，但很奇怪，部署很清楚是什么原因。
还有一个问题同样跟另一个issue一样，是在!reload之后会报错，无法回复消息。

**完整报错信息**  
`Exception in thread Thread-3 (run):
Traceback (most recent call last):
  File "/home/Files/python/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/Files/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Files/python/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/Files/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/Files/python/lib/python3.10/site-packages/mirai/models/api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "/home/Files/python/lib/python3.10/site-packages/mirai/models/api.py", line 383, in set
    return await self._call_api(
  File "/home/Files/python/lib/python3.10/site-packages/mirai/models/api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "/home/Files/python/lib/python3.10/site-packages/mirai/models/api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "/home/Files/python/lib/python3.10/site-packages/mirai/bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "/home/Files/python/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "/home/Files/python/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'Illegal base64 character -49')`

**Comment by RockChinQ** [comment]
这个是赞助图片编码有问题，已修复，等待新的发行版

**Comment by EricMeteorite** [comment]
好的感谢！
