### ISSUE TITLE
主程序启动报错

### ISSUE THREAD

**Issue by liuss77** [RockChinQ/QChatGPT#238]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    例如： Centos x64
- Python环境（仅手动部署填写）：
    

**描述漏洞**  
主程序启动报错
**完整报错信息**  
2023-03-06 13:47:43 - ERROR    Multiple exceptions: [Errno 111] Connect call failed ('::1', 1843, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1843)
[2023-03-06 13:47:43.014] base.py (43) - [ERROR] : Multiple exceptions: [Errno 111] Connect call failed ('::1', 1843, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1843)
[2023-03-06 13:47:43.015] main.py (248) - [ERROR] : 捕捉到未知异常:Multiple exceptions: [Errno 111] Connect call failed ('::1', 1843, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1843), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/main.py", line 251, in run_bot_wrapper
    raise e
  File "/bot/main.py", line 213, in run_bot_wrapper
    qqbot.bot.run()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1073, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 1843, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1843)

**Comment by RockChinQ** [comment]
#68
