### ISSUE TITLE
运行“run-bot.bat”时出现报错，server rejected WebSocket connection: HTTP 404

### ISSUE THREAD

**Issue by Leocjy** [RockChinQ/QChatGPT#24]
报错内容如下
```[2022-12-14 13:16:46.171] main.py (74) - [INFO] : 程序启动完成
2022-12-14 13:16:46 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2022-12-14 13:16:46.171] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2022-12-14 13:16:56 - ERROR
[2022-12-14 13:16:56.185] base.py (43) - [ERROR] :
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\websockets\legacy\client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\tasks.py", line 456, in wait_for
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "Y:\OpenAIBotForQQ\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "asyncio\tasks.py", line 458, in wait_for
asyncio.exceptions.TimeoutError
```

**Comment by RockChinQ** [comment]
原因：8080端口被其他程序占用

**Comment by RockChinQ** [comment]
已解决，见：https://github.com/RockChinQ/QChatGPT/issues/22
