### ISSUE TITLE
E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1468594275), code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录。, errorInfo=)[BUG]

### ISSUE THREAD

**Issue by Zoumachuan** [RockChinQ/QChatGPT#249]
**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    例如： Ubuntu Server 22.04 LTS 64bi

**描述漏洞**  
2023/3/7,在尝试!update后，机器人无反应，后登出，再次登陆时发现mirai无法登录，尝试切换多个QQ号后仍然报错内容如下。

**完整报错信息**  
2023-03-07 15:12:39 I/Bot.**********: [SliderCaptcha] 正在提交中...
2023-03-07 15:12:39 I/Bot.**********: [SliderCaptcha] Submitting...
2023-03-07 15:12:39 I/Bot.********** Bot cancelled: Bot closed
2023-03-07 15:12:39 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(**********), code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(**********), code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Adlith** [comment]
the same
![image](https://user-images.githubusercontent.com/13307223/223512977-d6c2af48-e899-4dc0-a0fc-f86ce1c6d199.png)

**Comment by FUQUANYUO** [comment]
![image](https://user-images.githubusercontent.com/74005988/223581157-f33c4bbf-7d8c-40d1-97e3-2ecdf2cdac08.png)
风控增强了吗

**Comment by RockChinQ** [comment]
见 #137，不行的话到mamoe/mirai的issues寻求帮助

**Comment by Zoumachuan** [comment]
疑似是腾讯最新风控
https://github.com/mamoe/mirai/issues/2552

**Comment by RockChinQ** [comment]
此问题统一解法 #285
