### ISSUE TITLE
[BUG]key有余额报错问题

### ISSUE THREAD

**Issue by xiaoxin6666666** [RockChinQ/QChatGPT#266]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
 Centos x64

**描述漏洞**  
我放了多条key的他没有给我切换key然后我把有余额的key放到第一来也是这样不知道哪里出问题

**完整报错信息**  
[2023-03-12 01:43:20.819] util.py (67) - [INFO] : error_code=invalid_api_key error_message='Incorrect API key provided: sk-zkqJh***************************************OAvj. You can find your API key at https://platform.openai.com/account/api-keys.' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-03-12 01:43:20.819] message.py (126) - [ERROR] : Incorrect API key provided: sk-zkqJh***************************************OAvj. You can find your API key at https://platform.openai.com/account/api-keys.
Traceback (most recent call last):
  File "C:\Users\1\Desktop\备用\QChatGPT\.\pkg\qqbot\message.py", line 46, in process_normal_message
    text = session.append(text_message)
  File "C:\Users\1\Desktop\备用\QChatGPT\.\pkg\openai\session.py", line 217, in append
    message = pkg.utils.context.get_openai_manager().request_completion(
  File "C:\Users\1\Desktop\备用\QChatGPT\.\pkg\openai\manager.py", line 55, in request_completion
    ai.request(
  File "C:\Users\1\Desktop\备用\QChatGPT\.\pkg\openai\modelmgr.py", line 127, in request
    super().request(**kwargs)
  File "C:\Users\1\Desktop\备用\QChatGPT\.\pkg\openai\modelmgr.py", line 82, in request
    self.ret = self.request_fun(**kwargs)
  File "C:\Users\1\Desktop\备用\python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\1\Desktop\备用\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\1\Desktop\备用\python\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\1\Desktop\备用\python\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\1\Desktop\备用\python\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: Incorrect API key provided: sk-zkqJh***************************************OAvj. You can find your API key at https://platform.openai.com/account/api-keys.
[2023-03-12 01:43:20.823] manager.py (337) - [INFO] : 通知管理员:person_3184会话处理异常:Incorrect API key provided: sk-zkqJh***************************************OAvj. You can find your API key at https://platform.openai.com/account/api-keys.
[2023-03-12 01:43:20.823] process.py (155) - [INFO] : 回复[person_3189]文字消息:[bot]err:Incorrect API key provided: sk-zkqJh***************************************OAvj. You can fi...
[2023-03-12 01:43:24.149] main.py (297) - [INFO] : 当前已是最新版本

**Comment by RockChinQ** [comment]
检查是否填写正确，或尝试前往官网生成新的key并填入
