### ISSUE TITLE
运行python3 main.py 之后 机器人收到消息报错

### ISSUE THREAD

**Issue by The-Best-K** [RockChinQ/QChatGPT#27]
**运行环境**
- 部署方式：
    - [x] 手动部署
    - [ ] 自动部署
- 系统环境：
    Centos x64 7.6
- Python环境（仅手动部署填写）：
     Python 3.9.3

**描述漏洞**
什么时候发生的，mirai还是主程序，越详细越好
当机器人接收到第一条消息
**完整报错信息**
```[root@iZuf6i3mo0lf348xk2v50oZ QChatGPT]# python3 main.py
Database initialized.
2022-12-14 16:43:27 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2022-12-14 16:43:27.200] main.py (74) - [INFO] : 程序启动完成
[2022-12-14 16:43:27.200] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2022-12-14 16:43:37 - ERROR    
[2022-12-14 16:43:37.212] base.py (43) - [ERROR] : 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/local/python3/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/python3/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/python3/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/usr/local/python3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/python3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/python3/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/python3/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

```

**Comment by RockChinQ** [comment]
检查mirai是否按照手动部署教程安装并且正在运行且已登录QQ号

**Comment by The-Best-K** [comment]
> 检查mirai是否按照手动部署教程安装并且正在运行且已登录QQ号

检查过了 而且还重新部署了一次 还是这样

**Comment by The-Best-K** [comment]
> mirai方面问题，建议到mirai的社区寻求帮助

不是mirai报错....

**Comment by The-Best-K** [comment]
> yirimirai库的报错😑你这个看起来非常像是主程序和mirai的连接无法建立，检查`QChatGPT/config.py`里的`mirai-api-http`的端口与`mirai/config/net.mamoe.mirai-api-http/setting.yml`的端口是否一致，若两端不在一个机器上，还需要检查防火墙是否阻挡
解决了 mirai的地址要填写本机的ipv4 QChatGPT用本机ipv4连可以
