### ISSUE TITLE
[BUG]set_wakeup_fd only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by d4renk** [RockChinQ/QChatGPT#273]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
    例如： debian11 x64
- Python环境（仅手动部署填写）：
    例如： Python 3.9

**描述漏洞**  
我重启了项目后遇到了错误，但由于我之前写了自动git pull代码，所以我无法确定是哪个版本的代码出现了问题。
重新部署了 仍然存在此问题

**完整报错信息**  
```
[2023-03-13 12:00:09.516] keymgr.py (62) - [INFO] : 使用api-key:default
[2023-03-13 12:00:09.517] manager.py (30) - [INFO] : 文字总使用量：108276
[2023-03-13 12:00:09.519] manager.py (95) - [INFO] : 加载禁用列表: person: [***], group: [***]
[2023-03-13 12:00:09.520] host.py (88) - [INFO] : 加载插件
[2023-03-13 12:00:09.522] models.py (219) - [INFO] : 插件注册完成: n='加群审批', d='自动审批加群申请', v=0.1, a='RockChinQ' (<class 'plugins.auto_approval.main.AutoApproval'>)
[2023-03-13 12:00:09.523] host.py (80) - [INFO] : 加载模块: plugins/auto_approval/main.py 成功
[2023-03-13 12:00:09.524] models.py (219) - [INFO] : 插件注册完成: n='CmdCN', d='命令中文支持', v=0.1, a='RockChinQ' (<class 'plugins.cmdcn.cmdcn.CmdCnPlugin'>)
[2023-03-13 12:00:09.525] host.py (80) - [INFO] : 加载模块: plugins/cmdcn/cmdcn.py 成功
[2023-03-13 12:00:09.526] models.py (219) - [INFO] : 插件注册完成: n='Hello', d='hello world', v=0.1, a='RockChinQ' (<class 'plugins.hello_plugin.main.HelloPlugin'>)
[2023-03-13 12:00:09.527] host.py (80) - [INFO] : 加载模块: plugins/hello_plugin/main.py 成功
[2023-03-13 12:00:09.529] models.py (219) - [INFO] : 插件注册完成: n='啊对对对', d='你都这样了，我就顺从你吧', v=0.1, a='RockChinQ' (<class 'plugins.urlikethisijustsix.urlt.AdddPlugin'>)
[2023-03-13 12:00:09.530] host.py (80) - [INFO] : 加载模块: plugins/urlikethisijustsix/urlt.py 成功
[2023-03-13 12:00:09.530] host.py (105) - [INFO] : 初始化插件
[2023-03-13 12:00:09.531] host.py (113) - [INFO] : 插件 加群审批 已初始化
[2023-03-13 12:00:09.532] host.py (113) - [INFO] : 插件 CmdCN 已初始化
[2023-03-13 12:00:09.533] host.py (113) - [INFO] : 插件 Hello 已初始化
[2023-03-13 12:00:09.534] host.py (113) - [INFO] : 插件 啊对对对 已初始化
[2023-03-13 12:00:09.584] main.py (265) - [ERROR] : 捕捉到未知异常:set_wakeup_fd only works in main thread of the main interpreter, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
```

**Comment by tHaxWLa** [comment]
我删除并且重新拉取了项目,还是报错
```
[2023-03-13 20:03:17.952] keymgr.py (62) - [INFO] : 使用api-key:default
[2023-03-13 20:03:17.953] manager.py (30) - [INFO] : 文字总使用量：0
[2023-03-13 20:03:17.955] manager.py (95) - [INFO] : 加载禁用列表: person: [xxxx], group: [xxxx, 691226829]
[2023-03-13 20:03:17.956] host.py (88) - [INFO] : 加载插件
[2023-03-13 20:03:17.958] host.py (105) - [INFO] : 初始化插件
[2023-03-13 20:03:18.095] main.py (265) - [ERROR] : 捕捉到未知异常:set_wakeup_fd only works in main thread of the main interpreter, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 95, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread of the main interpreter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/orangepi/act/QChatGPT/main.py", line 268, in run_bot_wrapper
    raise e
  File "/home/orangepi/act/QChatGPT/main.py", line 230, in run_bot_wrapper
    qqbot.bot.run()
  File "/home/orangepi/.local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/home/orangepi/.local/lib/python3.9/site-packages/mirai/bot.py", line 257, in run
    if not asgi_serve(
  File "/home/orangepi/.local/lib/python3.9/site-packages/mirai/asgi.py", line 210, in asgi_serve
    asyncio.run(serve(app, config), debug=True)
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/orangepi/.local/lib/python3.9/site-packages/hypercorn/asyncio/__init__.py", line 49, in serve
    await worker_serve(
  File "/home/orangepi/.local/lib/python3.9/site-packages/hypercorn/asyncio/run.py", line 67, in worker_serve
    loop.add_signal_handler(getattr(signal, signal_name), _signal_handler)
  File "/usr/lib/python3.9/asyncio/unix_events.py", line 97, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread of the main interpreter
```

**Comment by RockChinQ** [comment]
是否安装了`uvicorn`或`hypercorn`，请卸载

**Comment by RockChinQ** [comment]
查看 #129 #65
