### ISSUE TITLE
[BUG]更新后Bot无法启动

### ISSUE THREAD

**Issue by DannyLI0319** [RockChinQ/QChatGPT#283]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    例如： Windows 10 X64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
更新后Bot无法启动

**完整报错信息**  
Traceback (most recent call last):
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\main.py", line 389, in <module>
    qqbot = main(True)
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\main.py", line 199, in main
    pkg.openai.dprompt.read_scenario_from_file()
  File "C:\Users\kuang\Desktop\ChatGPT\QChatGPT\.\pkg\openai\dprompt.py", line 40, in read_scenario_from_file
    __scenario_from_files__[file] = json.load(f)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 11 column 9 (char 275)

**Comment by DannyLI0319** [comment]
问题已经解决，是scenario下面文件格式不对
