### ISSUE TITLE
[BUG]尝试应用预设时抛出“未找到默认情景预设”error

### ISSUE THREAD

**Issue by DomeenoH** [RockChinQ/QChatGPT#288]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    例如： Windows Server 2019 Datacenter

**描述漏洞**  
使用```!reset [预设]```命令修改预设时，会在命令行抛出下面引用的错误，然后返回**“未找到默认情景预设”**的提示；
![RSF2VZUCL B%HPFYE3G$UF1](https://user-images.githubusercontent.com/29730075/225631672-46de4116-d690-40ad-bf06-64e9b63ea00a.png)
![image](https://user-images.githubusercontent.com/29730075/225632426-88cf9d89-d17e-44c2-b7e3-e90e2671941f.png)

使用```!default```命令，可以正常返回所有预设
![image](https://user-images.githubusercontent.com/29730075/225631642-7cbdb10b-9025-49e5-ac96-36f59ac07ecc.png)

**完整报错信息**  
```cmd
[2023-03-16 08:20:51.752] command.py (166) - [INFO] : [person_**********]发起指令:!reset en-dict
[2023-03-16 08:20:51.830] manager.py (337) - [INFO] : 通知管理员:person_**********指令执行失败:'未找到默认情景预设: en-dict'
[2023-03-16 08:20:52.738] command.py (384) - [ERROR] : '未找到默认情景预设: en-dict'
Traceback (most recent call last):
  File "E:\QChatGPT\.\pkg\qqbot\command.py", line 180, in process_command
    pkg.openai.session.get_session(session_name).reset(explicit=True, use_prompt=params[0])
  File "E:\QChatGPT\.\pkg\openai\session.py", line 315, in reset
    self.default_prompt = self.get_default_prompt(use_prompt)
  File "E:\QChatGPT\.\pkg\openai\session.py", line 142, in get_default_prompt
    current_default_prompt = dprompt.get_prompt(use_default)
  File "E:\QChatGPT\.\pkg\openai\dprompt.py", line 121, in get_prompt
    raise KeyError("未找到默认情景预设: " + name)
KeyError: '未找到默认情景预设: en-dict
```

**Comment by DomeenoH** [comment]
```preset_mode = "full_scenario"```
