### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FoolMaster00** [RockChinQ/QChatGPT#295]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
自动部署
- 系统环境：
win10 x64

**描述漏洞**  
修改QChatGPT\scenario 内的json时 添加了一个雌小鬼.json 发生报错 删除后正常运行 但后又添加了萝莉.json 未发生报错

**完整报错信息**  
Traceback (most recent call last):
  File "D:\gpt\bof\QChatGPT\main.py", line 389, in <module>
    qqbot = main(True)
  File "D:\gpt\bof\QChatGPT\main.py", line 199, in main
    pkg.openai.dprompt.read_scenario_from_file()
  File "D:\gpt\bof\QChatGPT\.\pkg\openai\dprompt.py", line 40, in read_scenario_from_file
    __scenario_from_files__[file] = json.load(f)
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 5 column 29 (char 86)

**Comment by RockChinQ** [comment]
JSON语法错误，请自行根据JSON语法标准修改

**Comment by RockChinQ** [comment]
参考https://www.runoob.com/json/json-tutorial.html
