### ISSUE TITLE
[BUG]运行python3 main.py 报错

### ISSUE THREAD

**Issue by yundabei** [RockChinQ/QChatGPT#317]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署
- 系统环境：
    例如： ubuntu aarch64
- Python环境（仅手动部署填写）：
    例如： Python 3.9.10

**描述漏洞**  
运行python3 main.py时报错

**完整报错信息**  
python3 main.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "main.py", line 389, in <module>
    qqbot = main(True)
  File "main.py", line 115, in main
    import config
  File "/mirai/QChatGPT/config.py", line 268, in <module>
    upgrade_dependencies = Flase
NameError: name 'Flase' is not defined

**Comment by yundabei** [comment]
错了 这个才是日志
root@instance-20230318-1853:/mirai/QChatGPT# python3 main.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
[2023-03-20 17:06:16.301] main.py (281) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
Traceback (most recent call last):
  File "main.py", line 389, in <module>
    qqbot = main(True)
  File "main.py", line 192, in main
    import pkg.openai.manager
  File "/mirai/QChatGPT/pkg/openai/manager.py", line 11, in <module>
    class OpenAIInteract:
  File "/mirai/QChatGPT/pkg/openai/manager.py", line 37, in OpenAIInteract
    def request_completion(self, prompts) -> tuple[str, int]:
TypeError: 'type' object is not subscriptable

**Comment by RockChinQ** [comment]
Python版本过低
