### ISSUE TITLE
[BUG]启动主程序报错module 'websockets.exceptions' has no attribute 'InvalidStatus'. Did you mean: 'InvalidState'?

### ISSUE THREAD

**Issue by wzh195879702** [RockChinQ/QChatGPT#326]
- 部署方式：
    手动部署
- 系统环境：
Ubuntu 22.04
- Python环境（仅手动部署填写）：
 Python 3.10.6

**描述漏洞**  
启动主程序时报错

**完整报错信息**  
Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 105, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread of the main interpreter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/QChatGPT/main.py", line 226, in run_bot_wrapper
    qqbot.bot.run()
  File "/usr/local/lib/python3.10/dist-packages/mirai/bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/mirai/bot.py", line 255, in run
    if not asgi_serve(
  File "/usr/local/lib/python3.10/dist-packages/mirai/asgi.py", line 211, in asgi_serve
    asyncio.run(serve(app, config), debug=True)
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/hypercorn/asyncio/__init__.py", line 49, in serve
    await worker_serve(
  File "/usr/local/lib/python3.10/dist-packages/hypercorn/asyncio/run.py", line 67, in worker_serve
    loop.add_signal_handler(getattr(signal, signal_name), _signal_handler)
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 107, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread of the main interpreter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QChatGPT/main.py", line 237, in run_bot_wrapper
    except websockets.exceptions.InvalidStatus as e:
AttributeError: module 'websockets.exceptions' has no attribute 'InvalidStatus'. Did you mean: 'InvalidState'?

**Comment by RockChinQ** [comment]
#273
