### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Fuky112** [RockChinQ/QChatGPT#331]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：自动部署/手动部署 都用了一遍
    手动部署/自动部署/Docker部署
- 系统环境：Windows 10 专业版22H2 x64

- Python环境（仅手动部署填写）：Python 3.11.2

**描述漏洞**  
一开始自动部署的，mirai登录QQ账号成功后，打开run-bot.bat的时候报错；重新手动部署了一遍run-bot.bat还是报错

**完整报错信息**  
C:\Users\Administrator\Desktop\QQBot>cd QChatGPT

C:\Users\Administrator\Desktop\QQBot\QChatGPT>..\python\python.exe main.py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QQBot\QChatGPT\main.py", line 12, in <module>
    import colorlog
ModuleNotFoundError: No module named 'colorlog'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QQBot\QChatGPT\main.py", line 15, in <module>
    import pkg.utils.pkgmgr as pkgmgr
ModuleNotFoundError: No module named 'pkg'

C:\Users\Administrator\Desktop\QQBot\QChatGPT>pause
请按任意键继续. . .

**Comment by RockChinQ** [comment]
系统上Python环境复杂，请只保留一个，进行手动部署，并保证启动时使用的是3.9以上的版本

**Comment by ABGOU** [comment]
可以试试在QChatGPT文件夹下运行cmd，输入python3 main.py直接运行主程序看看

**Comment by bcrdvwz** [comment]
我也是这个问题，请问解决了吗

**Comment by maimierjiafude** [comment]
复制   在Qchatgpt中的pkg文件夹
粘贴   在python文件夹下的lib->site-package中

**Comment by RockChinQ** [comment]
> 复制 在Qchatgpt中的pkg文件夹 粘贴 在python文件夹下的lib->site-package中

不建议采取此方法，这会导致python库更加混乱且无法进行程序自动更新

**Comment by maimierjiafude** [comment]
> > 复制 在Qchatgpt中的pkg文件夹 粘贴 在python文件夹下的lib->site-package中
> 
> 不建议采取此方法，这会导致python库更加混乱且无法进行程序自动更新

那就在 <kbd>main.py</kbd> 文件的import下加一行
sys.path.append(os.getcwd())
把<kbd>main.py</kbd>的路径加入到import的查找中

**Comment by RockChinQ** [comment]
> > > 复制 在Qchatgpt中的pkg文件夹 粘贴 在python文件夹下的lib->site-package中
> > 
> > 
> > 不建议采取此方法，这会导致python库更加混乱且无法进行程序自动更新
> 
> 那就在 main.py 文件的import下加一行 sys.path.append(os.getcwd()) 把main.py的路径加入到import的查找中

测试过这样是可行的吗？

**Comment by maimierjiafude** [comment]
> > > > 复制 在Qchatgpt中的pkg文件夹 粘贴 在python文件夹下的lib->site-package中
> > > 
> > > 
> > > 不建议采取此方法，这会导致python库更加混乱且无法进行程序自动更新
> > 
> > 
> > 那就在 main.py 文件的import下加一行 sys.path.append(os.getcwd()) 把main.py的路径加入到import的查找中
> 
> 测试过这样是可行的吗？

我之前也是这个问题，这是运行run-bot以后的一些输出日志，没有找不到模块的错误了
小号风控了所以没办法开maria，所以整体的问题不太清楚，但是解决了pkg模块丢失的问题
```
[2023-03-27 16:46:32.870] keymgr.py (62) - [INFO] : 使用api-key:default
[2023-03-27 16:46:32.871] manager.py (30) - [INFO] : 文字总使用量：0
[2023-03-27 16:46:32.874] manager.py (87) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-03-27 16:46:32.875] host.py (89) - [INFO] : 加载插件
[2023-03-27 16:46:32.880] host.py (106) - [INFO] : 初始化插件
2023-03-27 16:46:32 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-03-27 16:46:32.883] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-03-27 16:46:34.882] main.py (280) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
2023-03-27 16:46:34 - ERROR    无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。
[2023-03-27 16:46:34.943] base.py (40) - [ERROR] : 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。
[2023-03-27 16:46:34.950] main.py (245) - [ERROR] : 连接mirai-api-http失败:无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。, 请检查是否已按照文档启动mirai
```
