### ISSUE TITLE
[Bug]: docker mirai-login-solver-selenium is not supported.

### ISSUE THREAD

**Issue by CBEpt** [RockChinQ/QChatGPT#346]
### 部署方式

Docker部署

### 系统环境

CentOS-7.6.1810-x64

### Python环境

docker?

### 异常情况

报错如图。。/qq/config文件夹内没出现 /net.mamoe.mirai-api-http，只有Console
![image](https://user-images.githubusercontent.com/103420806/228723588-1e088a6b-2fbb-4119-922b-8cfb196461a4.png)

### 报错信息

```
[root@ser669800626517 qchat]# docker attach 8d1761c1eeaf
2023-03-30 03:40:45 I/net.mamoe.mirai-login-solver-selenium: Loading mirai-login-solver-selenium v1.0-dev-12                      
2023-03-30 03:40:46 W/net.mamoe.mirai-login-solver-selenium: mirai-login-solver-selenium is not supported.
java.lang.RuntimeException: Exception in loading selenium
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:33)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt:17)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLoginSolver.kt)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverPluginMode.onLoad(SeleniumLoginSolverPluginMode.kt:29)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:368)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:283)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:96)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:152)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:290)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.UnsupportedOperationException: Unsupported Platform: Linux
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:266)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:138)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt:64)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumLoginSolverImpl.kt)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:32)
        ... 30 more
Caused by: java.io.IOException: Cannot run program "xdg-settings": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.commandProcessResult(MxSelenium.java:124)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.commandProcessResult(MxSelenium.java:114)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:252)
        ... 36 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
        at java.base/java.lang.ProcessImpl.start(Unknown Source)
        ... 41 more

2023-03-30 03:40:46 W/net.mamoe.mirai-login-solver-selenium: Visit https://github.com/project-mirai/mirai-login-solver-selenium for more information
java.lang.RuntimeException: Exception in loading selenium
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:33)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt:17)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolver$SeleniumLoginSolver$2.invoke(SeleniumLoginSolver.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolver.getInstance(SeleniumLoginSolver.kt)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverPluginMode.onLoad(SeleniumLoginSolverPluginMode.kt:29)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:368)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:283)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:96)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:152)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:290)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.UnsupportedOperationException: Unsupported Platform: Linux
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:266)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.initialize(MxSelenium.java:138)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt:64)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt$setup$2.invoke(SeleniumLoginSolverImpl.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImplKt.getSetup(SeleniumLoginSolverImpl.kt)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.<init>(SeleniumLoginSolverImpl.kt:32)
        ... 30 more
Caused by: java.io.IOException: Cannot run program "xdg-settings": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.commandProcessResult(MxSelenium.java:124)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.commandProcessResult(MxSelenium.java:114)
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//io.github.karlatemp.mxlib.selenium.MxSelenium.initialize0(MxSelenium.java:252)
        ... 36 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
        at java.base/java.lang.ProcessImpl.start(Unknown Source)
        ... 41 more

2023-03-30 03:40:46 I/plugin: Successfully loaded plugin net.mamoe.mirai-login-solver-selenium v1.0-dev-12
2023-03-30 03:40:46 I/plugin: Successfully loaded plugin Soyuz v1.0.0
2023-03-30 03:40:46 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
2023-03-30 03:40:46 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-03-30 03:40:48 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-03-30 03:40:48 I/Soyuz: Soyuz Access Token: slzJ4r6iUkyB3HGvft56
2023-03-30 03:40:49 W/Soyuz: Linked class io.netty.handler.codec.http.HttpServerCodec in mirai-login-solver-selenium-1.0-dev-17-all.jar but plugin not depend on it.
2023-03-30 03:40:49 W/Soyuz: Class loading logic may change in feature.
2023-03-30 03:40:49 I/ktor.application: Autoreload is disabled because the development mode is off.
2023-03-30 03:40:49 I/ktor.application: Responding at http://0.0.0.0:9876
2023-03-30 03:40:49 I/ktor.application: Application started in 0.303 seconds.
2023-03-30 03:40:50 I/Soyuz: iTXTech Soyuz is listening on ws://localhost:9876
2023-03-30 03:40:51 W/mirai-api-http: USING INITIAL KEY, please edit the key
2023-03-30 03:40:51 I/Mirai HTTP API: ********************************************************
2023-03-30 03:40:51 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off.
2023-03-30 03:40:52 I/MahKtorAdapter[http]: Application started in 0.862 seconds.
2023-03-30 03:40:52 I/MahKtorAdapter[http]: Responding at http://localhost:8080
2023-03-30 03:40:52 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2023-03-30 03:40:52 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEYiTVnVnbX
2023-03-30 03:40:52 I/Mirai HTTP API: adaptors: [http]
2023-03-30 03:40:52 I/Mirai HTTP API: ********************************************************
2023-03-30 03:40:52 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-03-30 03:40:52 I/main: 4 plugin(s) enabled.
2023-03-30 03:40:52 I/main: mirai-console started successfully.
> 2023-03-30 03:40:52 W/console: Closing input service...
```

**Comment by RockChinQ** [comment]
你要不去mamoe/mirai的issue搜一搜吧，我不太懂这是为什么
