### ISSUE TITLE
[Bug]: GBK编解码器错误，确认后提交iss

### ISSUE THREAD

**Issue by SkyFutu** [RockChinQ/QChatGPT#357]
### 部署方式

一键安装包部署

### 系统环境

windows  server 2019

### Python环境

py 3.10 自动部署

### 异常情况

!update更新后报错，为编码错误，不过没什么影响
![QQ图片20230401115536](https://user-images.githubusercontent.com/119418823/229264654-047f49f5-6d77-4370-96bc-798cdeb1e7ec.png)

### 报错信息

[2023-04-01 11:53:05.523] main.py (203) - [ERROR] : 'gbk' codec can't decode byte 0xae in position 46: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QChatGPT\main.py", line 201, in start
    pkg.qqbot.cmds.mgr.apply_privileges()
  File "C:\Users\Administrator\Desktop\QChatGPT\.\pkg\qqbot\cmds\mgr.py", line 319, in apply_privileges
    data = json.load(f)
  File "json\__init__.py", line 293, in load
UnicodeDecodeError: 'gbk' codec can't decode byte 0xae in position 46: illegal multibyte sequence
Database initialized.

**Comment by RockChinQ** [comment]
已在v2.3.1修复
