### ISSUE TITLE
[Bug]: 会话处理异常:argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by chinawonder** [RockChinQ/QChatGPT#359]
### 部署方式

安装器部署

### 系统环境

win10

### Python环境

python 3.10

### 异常情况

bot无法正常工作，在回复消息时会出现“会话处理异常:argument of type 'NoneType' is not iterable”的报错，但并不是每次回复都会出现，具体触发条件未知。经过简单测试，回复“你好”“在吗”这样的消息可以稳定正常工作，回复类似“你是谁？”“你叫什么名字？”这样的消息概率报错，回复“你能回答什么问题？”稳定报错。
从Traceback中所提示的出错位置检查，在安装器自动下载的python\lib\site-packages\openai\api_requestor.py文件的668行之前将rcode输出，发现正常情况下rcode应为200，报错情况下rcode为433，在618行前将result.content输出，发现正常情况下应包含回复文本内容的byte以及其他信息，报错情况下为空。

### 报错信息

[2023-04-01 15:15:37.313] message.py (124) - [ERROR] : argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "F:\chatbot\QChatGPT\.\pkg\qqbot\message.py", line 45, in process_normal_message
    text = session.append(text_message)
  File "F:\chatbot\QChatGPT\.\pkg\openai\session.py", line 226, in append
    message, total_token = pkg.utils.context.get_openai_manager().request_completion(
  File "F:\chatbot\QChatGPT\.\pkg\openai\manager.py", line 55, in request_completion
    ai.request(
  File "F:\chatbot\QChatGPT\.\pkg\openai\modelmgr.py", line 131, in request
    super().request(**kwargs)
  File "F:\chatbot\QChatGPT\.\pkg\openai\modelmgr.py", line 86, in request
    self.ret = self.request_fun(**kwargs)
  File "F:\chatbot\python\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "F:\chatbot\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "F:\chatbot\python\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "F:\chatbot\python\lib\site-packages\openai\api_requestor.py", line 618, in _interpret_response
    self._interpret_response_line(
  File "F:\chatbot\python\lib\site-packages\openai\api_requestor.py", line 668, in _interpret_response_line
    if 'text/plain' in rheaders.get('Content-Type'):
TypeError: argument of type 'NoneType' is not iterable
[2023-04-01 15:15:37.316] manager.py (338) - [INFO] : 通知管理员:person_1292889811会话处理异常:argument of type 'NoneType' is not iterable

**Comment by RockChinQ** [comment]
无法复现，估计是OpenAI的问题  
若仍有此问题，请在`config.py`设置`logging_level=logging.DEBUG`开启调试模式，获取相关调试信息输出后贴上来

**Comment by Chen-23333** [comment]
[chat.log](https://github.com/RockChinQ/QChatGPT/files/11185064/chat.log)
我这边复现了这个问题，会话内容是提问“苏州和杭州，著名的景点和小吃有哪些”。
看 log 信息是 opanai 返回的 response 里，状态码是 433，这种情况下不会有返回数据，所以 header 里面没有 Content-Type 字段，代码 `if 'text/plain' in rheaders.get('Content-Type'):` 中 get 取不到值，就相当于对一个空对象做 if in 操作。

具体为什么返回的状态码是443，不清楚是不是和设置了反向代理有关。

**Comment by RockChinQ** [comment]
openai库的问题，不再调查，请移步openai的仓库
