### ISSUE TITLE
[Bug]  base.py (43) - [ERROR]  main.py (266) - [ERROR] : 捕捉到未知异常:,

### ISSUE THREAD

**Issue by teleVico** [RockChinQ/QChatGPT#361]
### 部署方式

安装器部署

### 系统环境

window10

### Python环境

3.10.9

### 异常情况

mirai正常登录，run-bot启动报错；查询发现8080未被占用，尝试杀死8080端口进程后再尝试启动也没有。
后发现通过删除bots/下所有内容再重新登陆mirai解决问题。

### 报错信息

C:\Users\xiao\Desktop\Chat>cd QChatGPT

C:\Users\xiao\Desktop\Chat\QChatGPT>..\python\python.exe main.py
正在更新依赖库，请等待...
这个操作不是必须的,如果不想更新,请在config.py中将upgrade_dependencies设置为False
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.douban.com/simple/
Requirement already satisfied: openai in c:\users\xiao\desktop\chat\python\lib\site-packages (0.27.2)
Requirement already satisfied: Pillow in c:\users\xiao\desktop\chat\python\lib\site-packages (9.4.0)
Requirement already satisfied: tqdm in c:\users\xiao\desktop\chat\python\lib\site-packages (from openai) (4.65.0)
Requirement already satisfied: aiohttp in c:\users\xiao\desktop\chat\python\lib\site-packages (from openai) (3.8.4)
Requirement already satisfied: requests>=2.20 in c:\users\xiao\desktop\chat\python\lib\site-packages (from openai) (2.28.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\xiao\desktop\chat\python\lib\site-packages (from requests>=2.20->openai) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\xiao\desktop\chat\python\lib\site-packages (from requests>=2.20->openai) (1.26.15)
Requirement already satisfied: idna<4,>=2.5 in c:\users\xiao\desktop\chat\python\lib\site-packages (from requests>=2.20->openai) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\xiao\desktop\chat\python\lib\site-packages (from requests>=2.20->openai) (3.1.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\xiao\desktop\chat\python\lib\site-packages (from aiohttp->openai) (22.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\xiao\desktop\chat\python\lib\site-packages (from aiohttp->openai) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\xiao\desktop\chat\python\lib\site-packages (from aiohttp->openai) (1.3.1)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\xiao\desktop\chat\python\lib\site-packages (from aiohttp->openai) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\xiao\desktop\chat\python\lib\site-packages (from aiohttp->openai) (1.8.2)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\xiao\desktop\chat\python\lib\site-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: colorama in c:\users\xiao\desktop\chat\python\lib\site-packages (from tqdm->openai) (0.4.6)
Database initialized.
[2023-03-31 21:42:22.158] keymgr.py (62) - [INFO] : 使用api-key:default
[2023-03-31 21:42:22.174] manager.py (30) - [INFO] : 文字总使用量：49429
[2023-03-31 21:42:22.189] manager.py (87) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-03-31 21:42:22.205] host.py (89) - [INFO] : 加载插件
[2023-03-31 21:42:22.220] host.py (106) - [INFO] : 初始化插件
2023-03-31 21:42:22 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-03-31 21:42:22.220] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-03-31 21:42:24.239] main.py (283) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
2023-03-31 21:42:32 - ERROR
[2023-03-31 21:42:32.280] base.py (43) - [ERROR] :
[2023-03-31 21:42:32.301] main.py (266) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\websockets\legacy\client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\tasks.py", line 456, in wait_for
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\xiao\Desktop\Chat\QChatGPT\main.py", line 269, in run_bot_wrapper
    raise e
  File "C:\Users\xiao\Desktop\Chat\QChatGPT\main.py", line 231, in run_bot_wrapper
    qqbot.bot.run()
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "C:\Users\xiao\Desktop\Chat\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "asyncio\tasks.py", line 458, in wait_for
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
#22
