### ISSUE TITLE
[BUG] 启动主程序后卡住

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/QChatGPT#37]
**描述漏洞**
启动`run-bot.bat`时或手动运行主程序时，黄字输出完之后程序卡住

**Comment by Ren-Boo** [comment]
> **问题原因** 主程序配置文件内设置的QQ号与mirai登录的QQ号不同或mirai没登录
> 
> **解决办法**
> 
> 1. 在mirai登录你要使用的QQ号，方法见[此处](https://github.com/RockChinQ/qcg-installer#i-%E5%90%AF%E5%8A%A8mirai)的登录教程
> 2. 在`QChatGPT/config.py`中修改`mirai_http_api_config`字段中的QQ为你在mirai登录的QQ号
> 3. 保持mirai运行状态，重启主程序

启动run-bot.bat还是没反应啊

**Comment by sagiri114** [comment]
Traceback (most recent call last):
  File "K:\QQbot+VITS\QQbot\bot\QChatGPT\main.py", line 275, in <module>
    main(True)
  File "K:\QQbot+VITS\QQbot\bot\QChatGPT\main.py", line 136, in main
    pkg.plugin.host.load_plugins()
  File "K:\QQbot+VITS\QQbot\bot\QChatGPT\.\pkg\plugin\host.py", line 62, in load_plugins
    walk_plugin_path(__import__('plugins'))
  File "K:\QQbot+VITS\QQbot\bot\QChatGPT\.\pkg\plugin\host.py", line 48, in walk_plugin_path
    walk_plugin_path(__import__(module.__name__ + '.' + item.name, fromlist=['']),
  File "K:\QQbot+VITS\QQbot\bot\QChatGPT\.\pkg\plugin\host.py", line 55, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\QQbot+VITS\QQbot\bot\QChatGPT\.\plugins\BanMassage\main.py", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml' 
这个是什么问题

**Comment by RockChinQ** [comment]
> Traceback (most recent call last): File "K:\QQbot+VITS\QQbot\bot\QChatGPT\main.py", line 275, in main(True) File "K:\QQbot+VITS\QQbot\bot\QChatGPT\main.py", line 136, in main pkg.plugin.host.load_plugins() File "K:\QQbot+VITS\QQbot\bot\QChatGPT.\pkg\plugin\host.py", line 62, in load_plugins walk_plugin_path(**import**('plugins')) File "K:\QQbot+VITS\QQbot\bot\QChatGPT.\pkg\plugin\host.py", line 48, in walk_plugin_path walk_plugin_path(**import**(module.**name** + '.' + item.name, fromlist=['']), File "K:\QQbot+VITS\QQbot\bot\QChatGPT.\pkg\plugin\host.py", line 55, in walk_plugin_path importlib.import_module(module.**name** + '.' + item.name) File "importlib__init__.py", line 126, in import_module File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1006, in _find_and_load_unlocked File "", line 688, in _load_unlocked File "", line 883, in exec_module File "", line 241, in _call_with_frames_removed File "K:\QQbot+VITS\QQbot\bot\QChatGPT.\plugins\BanMassage\main.py", line 9, in import yaml ModuleNotFoundError: No module named 'yaml' 这个是什么问题

插件内部问题请到插件仓库反馈

**Comment by wbfz89** [comment]
Exception in thread Thread-3 (run):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\ChatGPT\python\lib\site-packages\mirai\models\api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "C:\ChatGPT\python\lib\site-packages\mirai\models\api.py", line 383, in set
    return await self._call_api(
  File "C:\ChatGPT\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "C:\ChatGPT\python\lib\site-packages\mirai\models\api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "C:\ChatGPT\python\lib\site-packages\mirai\bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "C:\ChatGPT\python\lib\site-packages\mirai\adapters\websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "C:\ChatGPT\python\lib\site-packages\mirai\adapters\websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'java.net.SocketException: Connection reset')
启动主程序后卡住，发送消息不回复

**Comment by RockChinQ** [comment]
> Exception in thread Thread-3 (run): Traceback (most recent call last): File "threading.py", line 1016, in _bootstrap_inner File "threading.py", line 953, in run File "asyncio\runners.py", line 44, in run File "asyncio\base_events.py", line 649, in run_until_complete File "C:\ChatGPT\python\lib\site-packages\mirai\models\api.py", line 415, in **call** return await self.set(*args, **kwargs) File "C:\ChatGPT\python\lib\site-packages\mirai\models\api.py", line 383, in set return await self._call_api( File "C:\ChatGPT\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api return await api.call(self.api_provider, method, response_type) File "C:\ChatGPT\python\lib\site-packages\mirai\models\api.py", line 304, in call raw_response = await api_provider.call_api( File "C:\ChatGPT\python\lib\site-packages\mirai\bot.py", line 91, in call_api return await self._adapter.call_api(api, *args, **kwargs) File "C:\ChatGPT\python\lib\site-packages\mirai\adapters\websocket.py", line 236, in call_api return await self._recv(sync_id) File "C:\ChatGPT\python\lib\site-packages\mirai\adapters\websocket.py", line 165, in _recv raise exceptions.ApiError(data) mirai.exceptions.ApiError: (500, '[ERROR 500]mirai 内部错误。', 'java.net.SocketException: Connection reset') 启动主程序后卡住，发送消息不回复

网络问题，重启mirai和主程序

**Comment by mumudshelter** [comment]
大佬这个是啥问题啊
[2023-03-03 22:25:54.278] main.py (232) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息, 请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-03-03 22:25:59.913] manager.py (307) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新
Exception in thread Thread-3 (run):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "D:\ai\python\lib\site-packages\mirai\models\api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "D:\ai\python\lib\site-packages\mirai\models\api.py", line 383, in set
    return await self._call_api(
  File "D:\ai\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "D:\ai\python\lib\site-packages\mirai\models\api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "D:\ai\python\lib\site-packages\mirai\bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "D:\ai\python\lib\site-packages\mirai\adapters\websocket.py", line 232, in call_api
    await self.connection.send(json_dumps(content))
  File "D:\ai\python\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "D:\ai\python\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

**Comment by RockChinQ** [comment]
> 大佬这个是啥问题啊 [2023-03-03 22:25:54.278] main.py (232) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息, 请查看 #37 [2023-03-03 22:25:59.913] manager.py (307) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新 Exception in thread Thread-3 (run): Traceback (most recent call last): File "threading.py", line 1016, in _bootstrap_inner File "threading.py", line 953, in run File "asyncio\runners.py", line 44, in run File "asyncio\base_events.py", line 649, in run_until_complete File "D:\ai\python\lib\site-packages\mirai\models\api.py", line 415, in **call** return await self.set(*args, **kwargs) File "D:\ai\python\lib\site-packages\mirai\models\api.py", line 383, in set return await self._call_api( File "D:\ai\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api return await api.call(self.api_provider, method, response_type) File "D:\ai\python\lib\site-packages\mirai\models\api.py", line 304, in call raw_response = await api_provider.call_api( File "D:\ai\python\lib\site-packages\mirai\bot.py", line 91, in call_api return await self._adapter.call_api(api, *args, **kwargs) File "D:\ai\python\lib\site-packages\mirai\adapters\websocket.py", line 232, in call_api await self.connection.send(json_dumps(content)) File "D:\ai\python\lib\site-packages\websockets\legacy\protocol.py", line 635, in send await self.ensure_open() File "D:\ai\python\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open raise self.connection_closed_exc() websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

请查找此问题或开启新issue，请勿在此回复无关问题
