### ISSUE TITLE
[报错]: 切换至 ChatGPT网页版逆向3.5无法使用

### ISSUE THREAD

**Issue by xueji-x** [RockChinQ/QChatGPT#408]
### 部署方式

手动部署

### 系统环境

Windows11

### Python环境

Python3.10

### 异常情况

安装了插件Switcher,revLibs且按相关提示将文件补充完整
切换成bing和gpt3.5可以正常使用
切换成rgpt3.5报错

### 报错信息

[bot][rev] 处理消息时出现错误:
Traceback (most recent call last):
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\QChatGPT\.\plugins\revLibs\main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 132, in get_session
    __sessions__[name] = RevSession(name)
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\revss.py", line 45, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\QChatGPT\.\plugins\revLibs\pkg\process\impls\v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 54, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 159, in __init__
    self.__check_credentials()
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 54, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 183, in __check_credentials
    self.login()
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 54, in wrapper
    out = func(*args, **kwargs)
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\python\lib\site-packages\revChatGPT\V1.py", line 319, in login
    auth = Authenticator(
  File "C:\Users\12eqeq2e\Desktop\bot\QChatGPT\python\lib\site-packages\OpenAIAuth.py", line 38, in __init__
    raise ValueError("PUID is required")
ValueError: PUID is required

**Comment by RockChinQ** [comment]
acheong08/ChatGPT#1285 , revChatGPT账密登录方式已不在可用，请使用access_token的登录方式
