### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by theManOfNB** [RockChinQ/QChatGPT#434]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

win10

### Python环境

Python 3.11.0b3

### 异常情况

用gocp登陆然后接入newbing逆向库的时候提示没有问题，但是给机器人发消息则报错，回复的时候转发消息打不开

### 报错信息

[2023-04-25 13:34:37.998] main.py (112) - [ERROR] : [rev] Traceback (most recent call last):
  File "D:\qq-chat-gpt-new-bing\QChatGPT-2.4.0\plugins\revLibs\main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qq-chat-gpt-new-bing\QChatGPT-2.4.0\plugins\revLibs\pkg\process\procmsg.py", line 58, in process_message
    raise e
  File "D:\qq-chat-gpt-new-bing\QChatGPT-2.4.0\plugins\revLibs\pkg\process\procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "D:\qq-chat-gpt-new-bing\QChatGPT-2.4.0\plugins\revLibs\pkg\process\revss.py", line 96, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "D:\qq-chat-gpt-new-bing\QChatGPT-2.4.0\plugins\revLibs\pkg\process\impls\edgegpt.py", line 51, in get_reply
    resp = asyncio.run(task)
           ^^^^^^^^^^^^^^^^^
  File "D:\python3110b3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\python3110b3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python3110b3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\python3110b3\Lib\site-packages\EdgeGPT.py", line 376, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "D:\python3110b3\Lib\site-packages\EdgeGPT.py", line 293, in ask_stream
    self.wss = await websockets.connect(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python3110b3\Lib\site-packages\websockets\legacy\client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python3110b3\Lib\asyncio\base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python3110b3\Lib\asyncio\base_events.py", line 1132, in _create_connection_transport
    protocol = protocol_factory()
               ^^^^^^^^^^^^^^^^^^
  File "D:\python3110b3\Lib\site-packages\websockets\legacy\client.py", line 160, in __init__
    super().__init__(**kwargs)
  File "D:\python3110b3\Lib\site-packages\websockets\legacy\protocol.py", line 154, in __init__
    self._drain_lock = asyncio.Lock(
                       ^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by RockChinQ** [comment]
#82

**Comment by theManOfNB** [comment]
没有这两个依赖
