### ISSUE TITLE
[Bug]: module 'websockets.exceptions' has no attribute 'InvalidStatus'. Did you mean: 'InvalidState'?

### ISSUE THREAD

**Issue by tHaxWLa** [RockChinQ/QChatGPT#435]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

6.1.0-kali7-amd64

### Python环境

Python 3.11.2

### 异常情况

启动后报错

### 报错信息

```
[2023-04-25 16:55:29.124] main.py (271) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
Exception in thread Thread-3 (run_bot_wrapper):
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 105, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread of the main interpreter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xc9/act/QChatGPT/main.py", line 212, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/home/xc9/act/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 113, in run_sync
    self.bot.run()
  File "/home/xc9/.local/lib/python3.11/site-packages/mirai/bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/home/xc9/.local/lib/python3.11/site-packages/mirai/bot.py", line 255, in run
    if not asgi_serve(
           ^^^^^^^^^^^
  File "/home/xc9/.local/lib/python3.11/site-packages/mirai/asgi.py", line 211, in asgi_serve
    asyncio.run(serve(app, config), debug=True)
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/xc9/.local/lib/python3.11/site-packages/hypercorn/asyncio/__init__.py", line 49, in serve
    await worker_serve(
  File "/home/xc9/.local/lib/python3.11/site-packages/hypercorn/asyncio/run.py", line 67, in worker_serve
    loop.add_signal_handler(getattr(signal, signal_name), _signal_handler)
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 107, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread of the main interpreter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xc9/act/QChatGPT/main.py", line 223, in run_bot_wrapper
    except websockets.exceptions.InvalidStatus as e:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'websockets.exceptions' has no attribute 'InvalidStatus'. Did you mean: 'InvalidState'?
[2023-04-25 16:55:35.719] main.py (302) - [INFO] : 新版本可用，请发送 !update 进行自动更新
更新日志:
v2.4.2 细化到单个群的响应规则
v2.4.1 完善数据统计
v2.4.0 支持go-cqhttp登录
```

**Comment by RockChinQ** [comment]
#86

**Comment by tHaxWLa** [comment]
> #86

可以了,感谢

**Comment by RockChinQ** [comment]
> 我看issue很多问题都是hypercorn和uvicorn引起的,是否能在启动的时候卸载这两个依赖呢 @RockChinQ 还有这个是什么原因呢
> 
> ```
> [2023-04-26 08:55:09.081] manager.py (118) - [INFO] : Use adapter:yirimirai
> [2023-04-26 08:55:09.084] manager.py (242) - [INFO] : 加载禁用列表: person: [xxxxxx], group: [xxxxxx, xxxxxx]
> [2023-04-26 08:55:09.085] host.py (90) - [INFO] : 加载插件
> [2023-04-26 08:55:09.089] models.py (219) - [INFO] : 插件注册完成: n='Switcher', d='快捷切换使用的模型', v=0.1, a='RockChinQ' (<class 'plugins.Switcher.main.SwitcherPlugin'>)
> [2023-04-26 08:55:09.090] host.py (82) - [INFO] : 加载模块: plugins/Switcher/main.py 成功
> [2023-04-26 08:55:09.093] host.py (82) - [INFO] : 加载模块: plugins/Switcher/switches/model.py 成功
> [2023-04-26 08:55:09.095] host.py (82) - [INFO] : 加载模块: plugins/Switcher/switches/newbing.py 成功
> [2023-04-26 08:55:09.097] host.py (82) - [INFO] : 加载模块: plugins/Switcher/switches/openai_gpt3.py 成功
> [2023-04-26 08:55:09.098] host.py (82) - [INFO] : 加载模块: plugins/Switcher/switches/openai_gpt35.py 成功
> [2023-04-26 08:55:09.100] host.py (82) - [INFO] : 加载模块: plugins/Switcher/switches/openai_gpt4.py 成功
> [2023-04-26 08:55:09.101] host.py (82) - [INFO] : 加载模块: plugins/Switcher/switches/revchatgpt_gpt35.py 成功
> [2023-04-26 08:55:09.103] host.py (107) - [INFO] : 初始化插件
> [2023-04-26 08:55:09.103] host.py (115) - [INFO] : 插件 Switcher 已初始化
> [2023-04-26 08:55:09.106] main.py (211) - [INFO] : 使用账号: xxxxxx
> 2023-04-26 08:55:09 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
> 仅 HTTP 轮询与正向 WebSocket 可用。
> 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
> 在命令行键入：
>     pip install uvicorn
> 或者
>     pip install hypercorn
> [2023-04-26 08:55:09.110] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
> 仅 HTTP 轮询与正向 WebSocket 可用。
> 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
> 在命令行键入：
>     pip install uvicorn
> 或者
>     pip install hypercorn
> 2023-04-26 08:55:09 - ERROR    Lock.__init__() got an unexpected keyword argument 'loop'
> [2023-04-26 08:55:09.118] base.py (43) - [ERROR] : Lock.__init__() got an unexpected keyword argument 'loop'
> [2023-04-26 08:55:21.110] main.py (270) - [INFO] : QQ: xxxxxx, MAH: localhost:7893
> [2023-04-26 08:55:21.110] main.py (271) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
> [2023-04-26 08:55:28.906] main.py (302) - [INFO] : 新版本可用，请发送 !update 进行自动更新
> 更新日志:
> v2.4.2 细化到单个群的响应规则
> v2.4.1 完善数据统计
> v2.4.0 支持go-cqhttp登录
> ```

这个是由于YiriMirai底层兼容性问题，但目前此框架活跃性很低，故只能通过卸载不正常的依赖来解决。程序不应该在启动时尝试自动卸载此二依赖，因为这可能会影响用户系统上其他软件的运行。
