### ISSUE TITLE
[Bug]: [2023-04-26 15:48:39.970] host.py (335) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误 [2023-04-26 15:48:39.971] host.py (336) - [ERROR] : Traceback (most recent call last):   File "Z:\bot3\QChatGPT\.\pkg\plugin\host.py", line 329, in emit     hook(plugin['instance'], **kwargs)   File "Z:\bot3\QChatGPT\.\plugins\ChatWaifu\main.py", line 116, in group_normal_message_received     self_host.send_group_message(launcher_id, voice)   File "Z:\bot3\QChatGPT\.\pkg\plugin\host.py", line 290, in send_group_message     asyncio.run(self.get_bot().send_group_message(group, message))   File "Z:\bot3\QChatGPT\.\pkg\plugin\host.py", line 278, in get_bot     return context.get_qqbot_manager().bot AttributeError: 'QQBotManager' object has no attribute 'bot'

### ISSUE THREAD

**Issue by linjiangyu2** [RockChinQ/QChatGPT#440]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

Windows10

### Python环境

python3.10

### 异常情况

使用的Windows整合包

### 报错信息

[2023-04-26 15:48:39.970] host.py (335) - [ERROR] : 插件ChatWaifu触发事件normal_message_responded时发生错误
[2023-04-26 15:48:39.971] host.py (336) - [ERROR] : Traceback (most recent call last):
  File "Z:\bot3\QChatGPT\.\pkg\plugin\host.py", line 329, in emit
    hook(plugin['instance'], **kwargs)
  File "Z:\bot3\QChatGPT\.\plugins\ChatWaifu\main.py", line 116, in group_normal_message_received
    self_host.send_group_message(launcher_id, voice)
  File "Z:\bot3\QChatGPT\.\pkg\plugin\host.py", line 290, in send_group_message
    asyncio.run(self.get_bot().send_group_message(group, message))
  File "Z:\bot3\QChatGPT\.\pkg\plugin\host.py", line 278, in get_bot
    return context.get_qqbot_manager().bot
AttributeError: 'QQBotManager' object has no attribute 'bot'

**Comment by RockChinQ** [comment]
使用`!update`指令更新主程序到2.4.2版本
