### ISSUE TITLE
[Bug]: Ubantu中python main.py 报错

### ISSUE THREAD

**Issue by xianghuang2** [RockChinQ/QChatGPT#447]
### 部署方式

Docker部署

### 登录框架

Mirai

### 系统环境

Ubantu 18.04

### Python环境

Python2.7

### 异常情况

使用python main.py时，报错

### 报错信息

python main.py
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from pkg.utils.log import init_runtime_log_file, reset_logging
  File "/root/QChatGPT-master/pkg/utils/__init__.py", line 1, in <module>
    from .threadctl import ThreadCtl
  File "/root/QChatGPT-master/pkg/utils/threadctl.py", line 9
    pool_num:int = None
            ^
SyntaxError: invalid syntax

**Comment by RockChinQ** [comment]
要求Python版本高于3.9
