### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wcwq98** [RockChinQ/QChatGPT#450]
### 部署方式

安装器部署

### 登录框架

Mirai

### 系统环境

winsevre2019

### Python环境

python3.9

### 异常情况

连接不上mirai2.15

### 报错信息

Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "asyncio\base_events.py", line 1054, in create_connection
  File "asyncio\base_events.py", line 963, in _connect_sock
  File "asyncio\proactor_events.py", line 709, in sock_connect
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\Administrator\Desktop\电脑的\QChatGPT\main.py", line 252, in run_bot_wrapper
    raise e
  File "C:\Users\Administrator\Desktop\电脑的\QChatGPT\main.py", line 212, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "C:\Users\Administrator\Desktop\电脑的\QChatGPT\.\pkg\qqbot\sources\yirimirai.py", line 113, in run_sync
    self.bot.run()
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl_timeout__
    async with asyncio_timeout(self.open_timeout):
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\websockets\legacy\async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "C:\Users\Administrator\Desktop\电脑的\python\lib\site-packages\websockets\legacy\async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
提供主程序完整输出
