### ISSUE TITLE
[Bug]: main.py (250) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue

### ISSUE THREAD

**Issue by Tywh202** [RockChinQ/QChatGPT#464]
### 部署方式

一键安装包部署

### 登录框架

Mirai

### 系统环境

Windows10

### Python环境

Python3.10

### 异常情况

一直正常使用，再打开的时候报错
插件全部加载成功之后报错

### 2023-05-08 22:50:34 - ERROR
[2023-05-08 22:50:34.930] base.py (43) - [ERROR] :
[2023-05-08 22:50:34.935] main.py (250) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "G:\QQbot\29\bot3\python\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "G:\QQbot\29\bot3\python\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\QQbot\29\bot3\python\lib\site-packages\websockets\legacy\client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\tasks.py", line 456, in wait_for
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "G:\QQbot\29\bot3\QChatGPT\main.py", line 253, in run_bot_wrapper
    raise e
  File "G:\QQbot\29\bot3\QChatGPT\main.py", line 215, in run_bot_wrapper
    qqbot.bot.run()
  File "G:\QQbot\29\bot3\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "G:\QQbot\29\bot3\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "G:\QQbot\29\bot3\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "G:\QQbot\29\bot3\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "G:\QQbot\29\bot3\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "G:\QQbot\29\bot3\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "G:\QQbot\29\bot3\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "G:\QQbot\29\bot3\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "asyncio\tasks.py", line 458, in wait_for
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
#22
