### ISSUE TITLE
[Bug]: [2023-05-15 07:28:48.467] message.py (122) - [ERROR] : 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by p6oy** [RockChinQ/QChatGPT#470]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

ubuntu

### Python环境

python3.10

### 异常情况

[2023-05-15 07:28:47.720] message.py (26) - [INFO] : [group_912232335]发送消息:好了吗
[2023-05-15 07:28:48.467] message.py (122) - [ERROR] : 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/www/wwwroot/QChatGPT/pkg/qqbot/message.py", line 43, in process_normal_message
    text = session.append(text_message)
  File "/www/wwwroot/QChatGPT/pkg/openai/session.py", line 226, in append
    message, total_token = pkg.utils.context.get_openai_manager().request_completion(
  File "/www/wwwroot/QChatGPT/pkg/openai/manager.py", line 55, in request_completion
    ai.request(
  File "/www/wwwroot/QChatGPT/pkg/openai/modelmgr.py", line 131, in request
    super().request(**kwargs)
  File "/www/wwwroot/QChatGPT/pkg/openai/modelmgr.py", line 86, in request
    self.ret = self.request_fun(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
  File "/usr/local/lib/python3.10/dist-packages/openai/api_requestor.py", line 350, in handle_error_response
    error_code=error_data.get("code"),
AttributeError: 'str' object has no attribute 'get'
[2023-05-15 07:28:48.504] manager.py (368) - [INFO] : 通知管理员:group_912232335会话处理异常:'str' object has no attribute 'get'
[2023-05-15 07:28:49.139] process.py (157) - [INFO] : 回复[group_912232335]文字消息:[bot]err:'str' object has no attribute 'get'

**Comment by RockChinQ** [comment]
OpenAI库的问题吧，我没法解决，你可以尝试用pip更新一下openai库，或者到OpenAI的仓库去提issue
