### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by yanxiaochengya** [RockChinQ/QChatGPT#480]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

windows 10

### Python环境

Python 3.8

### 异常情况

go-cqhttp正常启动并运行，程序却无法连接go-cqhttp，已检查go-cqhttp的中的http端口、ws端口主程序中的一致。

### 报错信息

D:\桌面\新建文件夹>cd QChatGPT

D:\桌面\新建文件夹\QChatGPT>..\python\python.exe main.py
[2023-05-23 00:59:42.231] main.py (73) - [INFO] : 检查config模块完整性.
[2023-05-23 00:59:42.234] main.py (101) - [INFO] : 检查tips模块完整性.
正在更新依赖库，请等待...
这个操作不是必须的,如果不想更新,请在config.py中将upgrade_dependencies设置为False
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: openai in d:\桌面\新建文件夹\python\lib\site-packages (0.27.6)
Requirement already satisfied: Pillow in d:\桌面\新建文件夹\python\lib\site-packages (9.5.0)
Requirement already satisfied: nakuru-project-idk in d:\桌面\新建文件夹\python\lib\site-packages (0.0.2.1)
Requirement already satisfied: requests>=2.20 in d:\桌面\新建文件夹\python\lib\site-packages (from openai) (2.28.2)
Requirement already satisfied: tqdm in d:\桌面\新建文件夹\python\lib\site-packages (from openai) (4.64.1)
Requirement already satisfied: aiohttp in d:\桌面\新建文件夹\python\lib\site-packages (from openai) (3.8.3)
Requirement already satisfied: async-lru in d:\桌面\新建文件夹\python\lib\site-packages (from nakuru-project-idk) (2.0.2)
Requirement already satisfied: logbook in d:\桌面\新建文件夹\python\lib\site-packages (from nakuru-project-idk) (1.5.3)
Requirement already satisfied: pydantic in d:\桌面\新建文件夹\python\lib\site-packages (from nakuru-project-idk) (1.10.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\桌面\新建文件夹\python\lib\site-packages (from requests>=2.20->openai) (1.26.14)
Requirement already satisfied: idna<4,>=2.5 in d:\桌面\新建文件夹\python\lib\site-packages (from requests>=2.20->openai) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in d:\桌面\新建文件夹\python\lib\site-packages (from requests>=2.20->openai) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\桌面\新建文件夹\python\lib\site-packages (from requests>=2.20->openai) (2.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\桌面\新建文件夹\python\lib\site-packages (from aiohttp->openai) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\桌面\新建文件夹\python\lib\site-packages (from aiohttp->openai) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in d:\桌面\新建文件夹\python\lib\site-packages (from aiohttp->openai) (22.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in d:\桌面\新建文件夹\python\lib\site-packages (from aiohttp->openai) (1.3.1)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\桌面\新建文件夹\python\lib\site-packages (from aiohttp->openai) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in d:\桌面\新建文件夹\python\lib\site-packages (from aiohttp->openai) (1.3.3)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\桌面\新建文件夹\python\lib\site-packages (from async-lru->nakuru-project-idk) (4.4.0)
Requirement already satisfied: colorama in d:\桌面\新建文件夹\python\lib\site-packages (from tqdm->openai) (0.4.6)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: D:\桌面\新建文件夹\python\python.exe -m pip install --upgrade pip
Database initialized.
[2023-05-23 00:59:49.743] keymgr.py (61) - [INFO] : 使用api-key:default
[2023-05-23 00:59:49.748] manager.py (30) - [INFO] : 文字总使用量：821917
[2023-05-23 00:59:49.751] manager.py (118) - [INFO] : Use adapter:yirimirai
[2023-05-23 00:59:49.760] manager.py (243) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 614876491]
[2023-05-23 00:59:49.762] host.py (91) - [INFO] : 加载插件
[2023-05-23 00:59:49.767] host.py (108) - [INFO] : 初始化插件
[2023-05-23 00:59:49.769] main.py (211) - [INFO] : 使用账号: 1234567890
2023-05-23 00:59:49 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-05-23 00:59:49.773] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-05-23 00:59:51.770] main.py (262) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消 选择模式。
2023-05-23 00:59:59 - ERROR
[2023-05-23 00:59:59.782] base.py (43) - [ERROR] :
Traceback (most recent call last):
  File "D:\桌面\新建文件夹\python\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "D:\桌面\新建文件夹\python\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\桌面\新建文件夹\python\lib\site-packages\websockets\legacy\client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\tasks.py", line 456, in wait_for
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\桌面\新建文件夹\QChatGPT\main.py", line 212, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "D:\桌面\新建文件夹\QChatGPT\.\pkg\qqbot\sources\yirimirai.py", line 113, in run_sync
    self.bot.run()
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "D:\桌面\新建文件夹\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "asyncio\tasks.py", line 458, in wait_for
asyncio.exceptions.TimeoutError
[2023-05-23 01:00:00.010] main.py (249) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "D:\桌面\新建文件夹\python\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "D:\桌面\新建文件夹\python\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\桌面\新建文件夹\python\lib\site-packages\websockets\legacy\client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\tasks.py", line 456, in wait_for
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\桌面\新建文件夹\QChatGPT\main.py", line 252, in run_bot_wrapper
    raise e
  File "D:\桌面\新建文件夹\QChatGPT\main.py", line 212, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "D:\桌面\新建文件夹\QChatGPT\.\pkg\qqbot\sources\yirimirai.py", line 113, in run_sync
    self.bot.run()
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "D:\桌面\新建文件夹\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "D:\桌面\新建文件夹\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "asyncio\tasks.py", line 458, in wait_for
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
还有，python要求3.9以上，请仔细查看部署文档

**Comment by yanxiaochengya** [comment]
更换配置器后解决
