### ISSUE TITLE
[Bug]: 返回空消息

### ISSUE THREAD

**Issue by chenghancc** [RockChinQ/QChatGPT#481]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

debian11

### Python环境

python3.9.1

### 异常情况

在向qq机器人发消息时，会返回空消息[2023-05-25 18:29:31.675] process.py (161) - [INFO] : 回复[person]文字消息:[bot]err:<empty message>

### 报错信息

2023-05-25 18:29:31.666] message.py (122) - [ERROR] : <empty message>
Traceback (most recent call last):
  File "/root/test/QChatGPT/pkg/qqbot/message.py", line 43, in process_normal_message
    text = session.append(text_message)
  File "/root/test/QChatGPT/pkg/openai/session.py", line 226, in append
    message, total_token = pkg.utils.context.get_openai_manager().request_completion(
  File "/root/test/QChatGPT/pkg/openai/manager.py", line 55, in request_completion
    ai.request(
  File "/root/test/QChatGPT/pkg/openai/modelmgr.py", line 131, in request
    super().request(**kwargs)
  File "/root/test/QChatGPT/pkg/openai/modelmgr.py", line 86, in request
    self.ret = self.request_fun(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 230, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 624, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.9/dist-packages/openai/api_requestor.py", line 687, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <empty message>

**Comment by helloqingsir** [comment]
这个是怎么回事
