### ISSUE TITLE
[Bug]: 从2.2.1升级到最新版，调用api报错Network is unreachable

### ISSUE THREAD

**Issue by KevinXu02** [RockChinQ/QChatGPT#482]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Ubuntu

### Python环境

Python 3.10

### 异常情况

从2.2.1升级到最新版，调用api报错Network is unreachable，重新回退到2.2.1则重新可以使用。config中代理配置没有更改。

### 报错信息

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f16c553e860>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16c553e860>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/QChatGPT-2.2.1/plugins/revLibs/main.py", line 105, in normal_message_received
    reply_message = procmsg.process_message(session_name=kwargs['launcher_type']+"_"+str(kwargs['launcher_id']),
  File "/home/ubuntu/QChatGPT-2.2.1/plugins/revLibs/pkg/process/procmsg.py", line 32, in process_message
    session: revss.RevSession = revss.get_session(session_name)
  File "/home/ubuntu/QChatGPT-2.2.1/plugins/revLibs/pkg/process/revss.py", line 127, in get_session
    __sessions__[name] = RevSession(name)
  File "/home/ubuntu/QChatGPT-2.2.1/plugins/revLibs/pkg/process/revss.py", line 44, in __init__
    self.__rev_interface_impl__, valid, acc = __rev_interface_impl_class__.create_instance()
  File "/home/ubuntu/QChatGPT-2.2.1/plugins/revLibs/pkg/process/impls/v1impl.py", line 30, in create_instance
    return RevChatGPTV1(acc), valid_acc, acc
  File "/home/ubuntu/QChatGPT-2.2.1/plugins/revLibs/pkg/process/impls/v1impl.py", line 34, in __init__
    self.chatbot = Chatbot(
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/revChatGPT/V1.py", line 163, in __init__
    self.__check_credentials()
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/revChatGPT/V1.py", line 187, in __check_credentials
    self.login()
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/revChatGPT/V1.py", line 336, in login
    auth.begin()
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/OpenAIAuth.py", line 70, in begin
    response = self.session.get(
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qqbot/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='explorer.api.openai.com', port=443): Max retries exceeded with url: /api/auth/csrf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16c553e860>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by RockChinQ** [comment]
提供的报错是最新版的吗？这看起来是一个逆向库插件的问题，可以将主程序更新到最新版之后使用`!plugin update revLibs`更新逆向库插件到最新版

**Comment by KevinXu02** [comment]
在重新手动下载部署最新版之后问题好像解决了，感谢。
