### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Fuky112** [RockChinQ/QChatGPT#498]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Windows 10 22H2

### Python环境

Python 3.11.2

### 异常情况

部署完go-cqhttp和bot之后向bot发送消息时报错，对话窗口回复：
[bot]person_1379727817会话处理异常:You exceeded your current quota, please check your plan and billing details.
由于请求异常产生的未知错误，请查看日志

### 报错信息

[2023-06-15 21:19:16.222] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\main.py (73) - [INFO] :
检查config模块完整性.
[2023-06-15 21:19:16.223] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\main.py (101) - [INFO] :
检查tips模块完整性.
[2023-06-15 21:19:19.088] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\openai\keymgr.py (61) - [INFO] :
使用api-key:default
[2023-06-15 21:19:19.089] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\openai\manager.py (30) - [INFO] :
文字总使用量：0
[2023-06-15 21:19:19.089] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\qqbot\manager.py (121) - [INFO] :
Use adapter:nakuru
[2023-06-15 21:19:19.144] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\qqbot\manager.py (246) - [INFO] :
加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-06-15 21:19:19.145] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\plugin\host.py (91) - [INFO] :
加载插件
[2023-06-15 21:19:19.146] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\plugin\host.py (108) - [INFO] :
初始化插件
[2023-06-15 21:19:19.147] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\main.py (212) - [INFO] :
使用账号: 3443812618
[2023-06-15 21:19:19.150] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nakuru\application.py (59) - [INFO] :
Protocol: connected
[2023-06-15 21:19:21.149] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\main.py (274) - [INFO] :
您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
[2023-06-15 21:19:33.150] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\main.py (286) - [INFO] :
host: localhost, port: 6700, http_port: 5700
[2023-06-15 21:19:33.150] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\main.py (287) - [CRITICAL] :
程序启动完成,如长时间未显示 "Protocol: connected" ,并且不回复消息,请检查config.py中的nakuru_config是否正确
[2023-06-15 21:19:39.064] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\main.py (316) - [INFO] :
当前已是最新版本
[2023-06-15 21:19:52.973] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nakuru\application.py (95) - [INFO] :
Event: handling a event: GroupMessage
[2023-06-15 21:20:12.553] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nakuru\application.py (95) - [INFO] :
Event: handling a event: GroupMessage
[2023-06-15 21:20:51.134] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nakuru\application.py (95) - [INFO] :
Event: handling a event: GroupMessage
[2023-06-15 21:20:58.844] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nakuru\application.py (95) - [INFO] :
Event: handling a event: GroupMessage
[2023-06-15 21:21:10.514] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nakuru\application.py (95) - [INFO] :
Event: handling a event: FriendMessage
[2023-06-15 21:21:10.515] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\qqbot\message.py (26) - [INFO] :
[person_1379727817]发送消息:你好
[2023-06-15 21:21:11.196] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\util.py (67) - [INFO] :
message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=e1d2204c4554d6caca90032e46d6beec response_code=429
[2023-06-15 21:21:11.196] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\util.py (67) - [INFO] :
error_code=None error_message='You exceeded your current quota, please check your plan and billing details.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
[2023-06-15 21:21:11.214] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\qqbot\message.py (126) - [ERROR] :
You exceeded your current quota, please check your plan and billing details.
由于请求异常产生的未知错误，请查看日志
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\qqbot\message.py", line 43, in process_normal_message
    text = session.append(text_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\openai\session.py", line 226, in append
    message, total_token = pkg.utils.context.get_openai_manager().request_completion(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\openai\manager.py", line 55, in request_completion
    ai.request(
  File "C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\openai\modelmgr.py", line 132, in request
    self.ret_handle()
  File "C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\openai\modelmgr.py", line 101, in ret_handle
    raise Exception(self.error_info)
Exception: You exceeded your current quota, please check your plan and billing details.
由于请求异常产生的未知错误，请查看日志
[2023-06-15 21:21:11.215] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\qqbot\manager.py (381) - [INFO] :
通知管理员:person_1379727817会话处理异常:You exceeded your current quota, please check your plan and billing details.
由于请求异常产生的未知错误，请查看日志
[2023-06-15 21:21:11.220] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\qqbot\process.py (161) - [INFO] :
回复[person_1379727817]文字消息:[bot]err:You exceeded your current quota, please check your plan and billing details.
由于请求异常产生的未知错误，...
[2023-06-15 21:21:11.221] C:\Users\Administrator\Desktop\QChatGPT-2.4.6\pkg\qqbot\process.py (191) - [INFO] :
[风控] 强制延迟0.32秒(如需关闭，请到config.py修改force_delay_range字段)
[2023-06-15 21:21:11.880] C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\nakuru\application.py (95) - [INFO] :
Event: handling a event: GroupMessage

**Comment by RockChinQ** [comment]
你api的账号额度用完了，换号或充钱
