### ISSUE TITLE
[Bug]: [ERROR] : too many redirects

### ISSUE THREAD

**Issue by yuxiaoyu8192** [RockChinQ/QChatGPT#509]
### 部署方式

Docker部署

### 登录框架

Mirai

### 系统环境

CentOS 7.4 x64

### Python环境

Python 3.9

### 异常情况

base.py (43) - [ERROR] : too many redirects

### 报错信息

```
2023-07-24 06:58:36 - ERROR    too many redirects
[2023-07-24 06:58:36.619] base.py (43) - [ERROR] : too many redirects
Traceback (most recent call last):
  File "/bot/main.py", line 213, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/bot/pkg/qqbot/sources/yirimirai.py", line 113, in run_sync
    self.bot.run()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 682, in __await_impl__
    raise SecurityError("too many redirects")
websockets.exceptions.SecurityError: too many redirects
[2023-07-24 06:58:36.637] main.py (250) - [ERROR] : 捕捉到未知异常:too many redirects, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/main.py", line 253, in run_bot_wrapper
    raise e
  File "/bot/main.py", line 213, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/bot/pkg/qqbot/sources/yirimirai.py", line 113, in run_sync
    self.bot.run()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 682, in __await_impl__
    raise SecurityError("too many redirects")
websockets.exceptions.SecurityError: too many redirects
```

**Comment by yuxiaoyu8192** [comment]
我没有开代理

**Comment by RockChinQ** [comment]
难搞哦，这是你那网络问题，难搞
