### ISSUE TITLE
[Bug]:  in wait_for raise exceptions.TimeoutError() from exc asyncio.exceptions.TimeoutError

### ISSUE THREAD

**Issue by Anzu0831** [RockChinQ/QChatGPT#511]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu18

### Python环境

python3.9.0

### 异常情况

部署后使用new bing插件后热重载，关闭程序后根据readme创建文件并粘贴JSON格式的cookie。关闭gocqhttp和主程序后，分别依次启动gocqhttp和主程序。给机器人发送私聊消息后出现该报错。

### 报错信息

[2023-07-26 22:35:36.324] application.py (95) - [INFO] : Event: handling a event: FriendMessage
[2023-07-26 22:35:36.327] procmsg.py (19) - [INFO] : [rev] 收到person_2381684362消息: HI
[2023-07-26 22:35:36.328] edgegpt.py (39) - [INFO] : [rev] 初始化NewBing使用代理: None
[2023-07-26 22:35:36.331] edgegpt.py (45) - [INFO] : [rev] 初始化NewBing具有Cookies
[2023-07-26 22:35:36.582] main.py (316) - [INFO] : 当前已是最新版本
[2023-07-26 22:35:36.584] _client.py (1013) - [INFO] : HTTP Request: GET https://edgeservices.bing.com/edgesvc/turing/conversation/create "HTTP/1.1 200 OK"
[2023-07-26 22:35:36.852] _client.py (1729) - [INFO] : HTTP Request: GET https://www.bing.com/turing/conversation/create "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 487, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/new/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/root/new/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/root/new/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 102, in ask_stream
    async with connect(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 642, in __aenter__
    return await self
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 489, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
[2023-07-26 22:35:46.898] procmsg.py (63) - [ERROR] : Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 487, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/new/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
    for section in session.get_reply(prompt):
  File "/root/new/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 102, in get_reply
    for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
  File "/root/new/QChatGPT/plugins/revLibs/pkg/process/impls/edgegpt.py", line 61, in get_reply
    resp = asyncio.run(task)
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT/EdgeGPT.py", line 116, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.9/site-packages/EdgeGPT/chathub.py", line 102, in ask_stream
    async with connect(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 642, in __aenter__
    return await self
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 489, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
不懂，好像大家的new bing都这样

**Comment by Anzu0831** [comment]
> 不懂，好像大家的new bing都这样

刚才看了看wiki和readme，似乎没有提到能够自由切换bing和chatgpt的指令，没有吗

**Comment by RockChinQ** [comment]
> > 不懂，好像大家的new bing都这样
> 
> 刚才看了看wiki和readme，似乎没有提到能够自由切换bing和chatgpt的指令，没有吗

可以看看文档中提及的[Switcher插件](https://github.com/RockChinQ/Switcher)
