### ISSUE TITLE
[Bug]: 升级V2.50后装联网插件报错

### ISSUE THREAD

**Issue by Tudouuuuuu** [RockChinQ/QChatGPT#514]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

windows sever 2022

### Python环境

python 3.10

### 异常情况

更新v2.50后并装联网插件后 发信息报错 

### 报错信息

```
  发送消息:介绍一下这个项目https://gith...
[2023-07-29 19:39:28.971] util.py (67) - [INFO] : message='OpenAI API response' path=https://api.chatanywhere.cn/v1/chat/completions processing_ms=None request_id=None response_code=500
[2023-07-29 19:39:28.971] util.py (67) - [INFO] : error_code=unmarshal_response_body_failed error_message='json: cannot unmarshal object into Go struct field DetailResponse.detail of type string' error_param=null error_type=aigc_api_error message='OpenAI API error received' stream_error=False
[2023-07-29 19:39:28.986] message.py (126) - [ERROR] : json: cannot unmarshal object into Go struct field DetailResponse.detail of type string {"error":{"message":"json: cannot unmarshal object into Go struct field DetailResponse.detail of type string","type":"aigc_api_error","param":"null","code":"unmarshal_response_body_failed"}} 500 {'error': {'message': 'json: cannot unmarshal object into Go struct field DetailResponse.detail of type string', 'type': 'aigc_api_error', 'param': 'null', 'code': 'unmarshal_response_body_failed'}} <CIMultiDictProxy('Date': 'Sat, 29 Jul 2023 11:39:28 GMT', 'Content-Type': 'application/json', 'Content-Length': '190', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'OPTIONS,GET,POST', 'Access-Control-Allow-Headers': '*', 'Access-Control-Max-Age': '6000', 'Vary': 'Origin', 'Vary': 'Access-Control-Request-Method', 'Vary': 'Access-Control-Request-Headers', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=7aA9F1wUEOC1vOjhTD0ntj4qZa8jJ%2FmGUlLt5xWLb6OriREUigzsMvZ5LW12ABJvFCbcbFVsi%2BFhS7S9Cu7fVYdIcq5ZuIJ4snIoVChZ5ydIAnULOFSiqko%2FwyM6g2%2BFdwHq26my"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '7ee514ce6aa323c5-LHR')>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\qqbot\message.py", line 43, in process_normal_message
    text = session.append(text_message)
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\session.py", line 231, in append
    for resp in pkg.utils.context.get_openai_manager().request_completion(prompts):
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\manager.py", line 54, in request_completion
    for resp in request:
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\api\chat_completion.py", line 85, in __next__
    resp = self._req(**args)
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\api\model.py", line 41, in _req
    raise exception
  File "C:\Users\Administrator\Desktop\QQ\QChatGPT\.\pkg\openai\api\model.py", line 25, in awrapper
    ret = await self.req_func(**kwargs)
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_requestor.py", line 726, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\Administrator\Desktop\QQ\python\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.APIError: json: cannot unmarshal object into Go struct field DetailResponse.detail of type string {"error":{"message":"json: cannot unmarshal object into Go struct field DetailResponse.detail of type string","type":"aigc_api_error","param":"null","code":"unmarshal_response_body_failed"}} 500 {'error': {'message': 'json: cannot unmarshal object into Go struct field DetailResponse.detail of type string', 'type': 'aigc_api_error', 'param': 'null', 'code': 'unmarshal_response_body_failed'}} <CIMultiDictProxy('Date': 'Sat, 29 Jul 2023 11:39:28 GMT', 'Content-Type': 'application/json', 'Content-Length': '190', 'Connection': 'keep-alive', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'OPTIONS,GET,POST', 'Access-Control-Allow-Headers': '*', 'Access-Control-Max-Age': '6000', 'Vary': 'Origin', 'Vary': 'Access-Control-Request-Method', 'Vary': 'Access-Control-Request-Headers', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=7aA9F1wUEOC1vOjhTD0ntj4qZa8jJ%2FmGUlLt5xWLb6OriREUigzsMvZ5LW12ABJvFCbcbFVsi%2BFhS7S9Cu7fVYdIcq5ZuIJ4snIoVChZ5ydIAnULOFSiqko%2FwyM6g2%2BFdwHq26my"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '7ee514ce6aa323c5-LHR')>


```

**Comment by RockChinQ** [comment]
提供一下前后的更多输出

**Comment by Tudouuuuuu** [comment]
没了 这是发信息后面和提示管理员前面的所有报错了

**Comment by RockChinQ** [comment]
有在config.py中设置openai的网络代理吗？

**Comment by Tudouuuuuu** [comment]
是通过反向代理使用的国内中转API

**Comment by Tudouuuuuu** [comment]
"reverse_proxy": "https://api.chatanywhere.cn/v1"

**Comment by Tudouuuuuu** [comment]
代理没有用
