### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by CXY666CXY** [RockChinQ/QChatGPT#52]
**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
    e.g. Centos x64
- Python环境（仅手动部署填写）：
    e.g. Python 3.10.9

**描述漏洞**
什么时候发生的，mirai还是主程序，越详细越好
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2022-12-22 17:22:53.800] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2022-12-22 17:22:55 - ERROR    server rejected WebSocket connection: HTTP 404
[2022-12-22 17:22:55.855] base.py (43) - [ERROR] : server rejected WebSocket connection: HTTP 404
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\ikunbot\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "C:\ikunbot\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\ikunbot\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "C:\ikunbot\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "C:\ikunbot\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "C:\ikunbot\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\ikunbot\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "C:\ikunbot\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "asyncio\tasks.py", line 445, in wait_for
  File "C:\ikunbot\python\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "C:\ikunbot\python\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

**完整报错信息**
完整的报错信息

**Comment by RockChinQ** [comment]
见 #22
