### ISSUE TITLE
[Bug]: 启动报错

### ISSUE THREAD

**Issue by Anufether** [RockChinQ/QChatGPT#535]
### 部署方式

Docker部署

### 登录框架

Mirai

### 系统环境

debian

### Python环境

python:3.9

### 异常情况

更新最新版代码后发生报错

### 报错信息

[2023-08-06 12:09:39.431] main.py (77) - [INFO] : 检查config模块完整性.                                               
[2023-08-06 12:09:39.433] main.py (92) - [WARNING] : 以下配置字段不存在: at_sender, nakuru_config, switch_strategy, trace_function_calls
[2023-08-06 12:09:39.433] main.py (98) - [WARNING] : 以上不存在的配置已被设为默认值，您可以依据config-template.py检查config.py，将在3秒后继续启动... 
[2023-08-06 12:09:42.436] main.py (110) - [INFO] : 检查tips模块完整性.
Database initialized.
[2023-08-06 12:09:43.190] keymgr.py (78) - [INFO] : 使用api-key:default
[2023-08-06 12:09:43.194] manager.py (246) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-08-06 12:09:43.196] settings.py (98) - [INFO] : 已全局启用内容函数。
[2023-08-06 12:09:43.196] host.py (123) - [INFO] : 初始化插件
[2023-08-06 12:09:43.197] host.py (139) - [INFO] : 以下插件已初始化: 
[2023-08-06 12:09:55.201] main.py (298) - [INFO] : QQ: 1611283818, MAH: localhost:8080
[2023-08-06 12:09:55.202] main.py (299) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37
[2023-08-06 12:10:02.311] main.py (330) - [INFO] : 新版本可用，请发送 !update 进行自动更新
更新日志:
v2.5.2 优化函数调用逻辑、api-key主动负载
[2023-08-06 12:10:02.911] main.py (343) - [CRITICAL] : [公告]<2023-08-01 10:49:26> 现已支持GPT函数调用功能，欢迎了解：https://github.com/RockChinQ/QChatGPT/wiki/%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8-%E5%86%85%E5%AE%B9%E5%87%BD%E6%95%B0
2023-08-06 12:10:03 - ERROR    
[2023-08-06 12:10:03.218] base.py (43) - [ERROR] : 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 326, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 138, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/QChatGPT/main.py", line 229, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 119, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
[2023-08-06 12:10:03.224] main.py (266) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 326, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 138, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/QChatGPT/main.py", line 269, in run_bot_wrapper
    raise e
  File "/QChatGPT/main.py", line 229, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 119, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
连不上mirai，自行检查mirai及mirai-api-http是否配置正常，且QChatGPT可达

**Comment by Anufether** [comment]
更新mirai插件时mirai-api-http文件损坏，重装修好了
