### ISSUE TITLE
[Bug]: 联网函数调用时出错：Unknown message type

### ISSUE THREAD

**Issue by fwerkor** [RockChinQ/QChatGPT#541]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Ubuntu 22.04

### Python环境

Python最新版

### 异常情况

castronaut 17:47:32
你可以调用函数吗

CapAI 17:47:42
是的，我可以调用函数来执行一些操作。请告诉我你需要我做什么，我会尽力满足你的需求。

castronaut 17:48:19
看一下https://github.com/fwerkor

CapAI 17:48:29
[bot]person_3116935098会话处理异常:Unknown message type: 调用函数 Webwlkr-access_the_web...<class 'str'>

### 报错信息

[2023-08-08 17:47:41.506] process.py (161) - [INFO] : 回复[person_3116935098]文字消息:是的，我可以调用函数来执行一些操作。请告诉我你需要我做什么，我会尽力满足你的需求。
[2023-08-08 17:48:20.309] application.py (95) - [INFO] : Event: handling a event: FriendMessage
[2023-08-08 17:48:20.311] message.py (26) - [INFO] : [person_3116935098]发送消息:看一下https://github.co...
[2023-08-08 17:48:26.171] util.py (67) - [INFO] : message='OpenAI API response' path=https://openai.api2d.net/v1/chat/completions processing_ms=None request_id=None response_code=200
[2023-08-08 17:48:28.480] message.py (129) - [ERROR] : Unknown message type: 调用函数 Webwlkr-access_the_web...<class 'str'>
Traceback (most recent call last):
  File "/www/wwwroot/bot.fwerkor.com/QChatGPT/bin/pkg/qqbot/message.py", line 43, in process_normal_message
    text, finish_reason, funcs = session.query(text_message)
  File "/www/wwwroot/bot.fwerkor.com/QChatGPT/bin/pkg/openai/session.py", line 306, in query
    botmgr.adapter.send_message(
  File "/www/wwwroot/bot.fwerkor.com/QChatGPT/bin/pkg/qqbot/sources/nakuru.py", line 199, in send_message
    converted_msg = self.message_converter.yiri2target(message) if not converted else message
  File "/www/wwwroot/bot.fwerkor.com/QChatGPT/bin/pkg/qqbot/sources/nakuru.py", line 26, in yiri2target
    raise Exception("Unknown message type: " + str(message_chain) + str(type(message_chain)))
Exception: Unknown message type: 调用函数 Webwlkr-access_the_web...<class 'str'>
[2023-08-08 17:48:28.480] manager.py (397) - [INFO] : 通知管理员:person_3116935098会话处理异常:Unknown message type: 调用函数 Webwlkr-access_the_web...<class 'str'>
[2023-08-08 17:48:32.666] process.py (161) - [INFO] : 回复[person_3116935098]文字消息:[bot]err:出错了，请稍后再试
[2023-08-08 17:50:44.492] application.py (95) - [INFO] : Event: handling a event: FriendMessage
[2023-08-08 17:50:44.495] command.py (27) - [INFO] : [person_3116935098]发起指令:!func
[2023-08-08 17:50:44.496] process.py (161) - [INFO] : 回复[person_3116935098]文字消息:当前已加载的内容函数：

1. Webwlkr-access_the_web:
Call this function to search about the question before you a...

**Comment by fwerkor** [comment]
其它链接/搜索要求都存在类似问题，已多次reset重试

**Comment by RockChinQ** [comment]
gocq兼容性问题，可以在`config.py`中将`trace_function_calls`设为`False`解决，或将gocq换成mirai框架，详细请阅读本仓库README.md中的手动部署步骤

**Comment by fwerkor** [comment]
已解决，非常感谢！
