### ISSUE TITLE
[Bug]: [2023-08-12 14:01:38.716] main.py (266) - [ERROR] : 捕捉到未知异常:, 

### ISSUE THREAD

**Issue by 022c** [RockChinQ/QChatGPT#544]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

windows11

### Python环境

3.11

### 异常情况

[2023-08-12 14:01:38.716] main.py (266) - [ERROR] : 捕捉到未知异常:,  请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue

### 报错信息

Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\websockets\legacy\client.py", line 662, in __await_impl__
    await protocol.handshake(
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\websockets\legacy\client.py", line 329, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\websockets\legacy\client.py", line 676, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "F:\jqrxxxxxxxxx\QChatGPT\main.py", line 269, in run_bot_wrapper
    raise e
  File "F:\jqrxxxxxxxxx\QChatGPT\main.py", line 229, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "F:\jqrxxxxxxxxx\QChatGPT\.\pkg\qqbot\sources\yirimirai.py", line 119, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl_timeout__
    async with asyncio_timeout(self.open_timeout):
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\websockets\legacy\async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\websockets\legacy\async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
在issues搜索`HTTP 404`
