### ISSUE TITLE
 无法连接到 mirai

### ISSUE THREAD

**Issue by 022c** [RockChinQ/QChatGPT#545]
### 部署方式

安装器部署

### 登录框架

None

### 系统环境

windows11

### Python环境

3.11

### 异常情况

2023-08-12 17:01:48 - ERROR    无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。
[2023-08-12 17:01:48.610] base.py (40) - [ERROR] : 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确 。

### 报错信息

。
[2023-08-12 17:01:58.520] main.py (298) - [INFO] : QQ: 1234567890, MAH: localhost:8080
[2023-08-12 17:01:58.522] main.py (299) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37
Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\websockets\legacy\client.py", line 622, in __await_impl__
    transport, protocol = await self._create_connection()
  File "asyncio\base_events.py", line 1075, in create_connection
  File "asyncio\base_events.py", line 1054, in create_connection
  File "asyncio\base_events.py", line 963, in _connect_sock
  File "asyncio\proactor_events.py", line 709, in sock_connect
  File "asyncio\windows_events.py", line 821, in _poll
  File "asyncio\windows_events.py", line 608, in finish_connect
ConnectionRefusedError: [WinError 1225] 远程计算机拒绝网络连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\jqrxxxxxxxxx\QChatGPT\main.py", line 229, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "F:\jqrxxxxxxxxx\QChatGPT\.\pkg\qqbot\sources\yirimirai.py", line 119, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\adapters\base.py", line 41, in wrapped
    raise err from e
mirai.exceptions.NetworkError: 无法连接到 mirai。请检查 mirai-api-http 是否启动，地址与端口是否正确。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "F:\jqrxxxxxxxxx\QChatGPT\main.py", line 240, in run_bot_wrapper
    except websockets.exceptions.InvalidStatus as e:
AttributeError: module 'websockets.exceptions' has no attribute 'InvalidStatus'. Did you mean: 'InvalidState'?

**Comment by RockChinQ** [comment]
请检查config.py中的mirai配置是否正确， mirai-api-http 是否启动，主程序是否可以与mirai通信，地址与端口是否正确。

**Comment by 022c** [comment]
> 请检查 config.py 中的mirai配置是否正确， mirai-api-http 是否启动，主程序是否可以与mirai通信，地址与端口是否正确
配置我没改过，我也不知道对不对，是可以收到信息的，端口8080

**Comment by RockChinQ** [comment]
那就按照文档要求的步骤检查信息是否填写正确
