### ISSUE TITLE
[Bug]: 没有找到函数: python

### ISSUE THREAD

**Issue by netses** [RockChinQ/QChatGPT#546]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Ubuntu 22

### Python环境

Python 3.10

### 异常情况

开启联网插件后有概率报错没有找到函数: python
但是系统是能找到python命令的，应该跟系统没关系

### 报错信息

[2023-08-13 15:09:45.345] message.py (129) - [ERROR] : 没有找到函数: python      Traceback (most recent call last):                                                 File "/root/QChatGPT/pkg/openai/api/chat_completion.py", line 153, in __next__     arguments = json.loads(cp_pending_func_call['arguments'])                      File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/QChatGPT/pkg/openai/api/chat_completion.py", line 157, in __next__
    func_schema = get_func_schema(func_name)
  File "/root/QChatGPT/pkg/openai/funcmgr.py", line 39, in get_func_schema
    raise ContentFunctionNotFoundError("没有找到内容函数: {}".format(name))
pkg.openai.funcmgr.ContentFunctionNotFoundError: 没有找到内容函数: python

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/QChatGPT/pkg/qqbot/message.py", line 43, in process_normal_message
    text, finish_reason, funcs = session.query(text_message)
  File "/root/QChatGPT/pkg/openai/session.py", line 266, in query
    for resp in pkg.utils.context.get_openai_manager().request_completion(prompts):
  File "/root/QChatGPT/pkg/openai/manager.py", line 54, in request_completion
    for resp in request:
  File "/root/QChatGPT/pkg/openai/api/chat_completion.py", line 203, in __next__
    raise Exception("没有找到函数: {}".format(func_name))
Exception: 没有找到函数: python

**Comment by RockChinQ** [comment]
你问了啥呀？这个函数调用功能，GPT3.5不太适合做这个的，经常出问题，有条件可以换GPT4模型
