### ISSUE TITLE
[Bug]: openai的反向代理用不了

### ISSUE THREAD

**Issue by 13055751** [RockChinQ/QChatGPT#554]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Termux

### Python环境

3.11

### 异常情况

反向代理用不了。
用你提供的也不行。

### 报错信息

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/main.py", line 471, in <module>
    main()
  File "/data/data/com.termux/files/home/main.py", line 417, in main
    pkg.utils.context.context['logger_handler'] = reset_logging()
                                                  ^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/pkg/utils/log.py", line 39, in reset_logging
    import config
  File "/data/data/com.termux/files/home/config.py", line 73
    "reverse_proxy": http://api.openai.rockchin.top/v1
                         ^
SyntaxError: invalid syntax

**Comment by 13055751** [comment]
已解决
