### ISSUE TITLE
修改README中关于部署的部分，增加doc目录存放说明文档

### ISSUE THREAD

**Issue by summeriver13** [RockChinQ/QChatGPT#56]
晚上花了6h部署（可能是太菜了QAQ）

最后还是部署成功了，但一路下来踩坑翻看文档和issues观感并不是很好。
所以我打算修改部分README，主要修改关于部署这部分的。
我想结合之前的文档，issue和这次部署成功的经验单独写一份md文件。
对原README的修改部分会尽可能的小，新加的内容会写新文件里，README里再去链接。
我想详尽的部署教程，对于不熟悉的新手还是很有帮助的。

**Comment by FakeGod13** [comment]
等待维护者回复后，开PR或者再讨论。

**Comment by RockChinQ** [comment]
感谢支持，您大可尝试编写可读性更高、更直观的部署教程，个人认为放到一个单独的文档可能会更好，同时若增加对常见问题的issue指引或许会更加方便

**Comment by RockChinQ** [comment]
https://github.com/RockChinQ/QChatGPT/wiki

**Comment by FakeGod13** [comment]
wiki好像没办法提交pr吧？
我以前是了解到wiki好像只能维护者去修改。

**Comment by FakeGod13** [comment]
不论如何，我先写好部署教程的md文件，再看用什么方式提交吧。

**Comment by RockChinQ** [comment]
> 好的，我会尽快完成，这周就会提交PR。 之前临近期末，DDL一大堆QAQ。

感谢对此项目的关注及贡献，祝你好运！

**Comment by 3205675095** [comment]
H:\下载\新建文件夹\QQbot\bot>cd QChatGPT

H:\下载\新建文件夹\QQbot\bot\QChatGPT>..\python\python.exe main.py
Database initialized.
[2023-02-11 21:47:29.949] keymgr.py (56) - [INFO] : 使用api-key:default
[2023-02-11 21:47:29.981] manager.py (74) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790]
2023-02-11 21:47:29 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-11 21:47:29.984] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-02-11 21:47:41.984] main.py (168) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息, 请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-02-11 21:47:47.399] manager.py (239) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新
Exception in thread Thread-2 (run):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 415, in __call__
    return await self.set(*args, **kwargs)
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 383, in set
    return await self._call_api(
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\models\api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\mirai\adapters\websocket.py", line 232, in call_api
    await self.connection.send(json_dumps(content))
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\websockets\legacy\protocol.py", line 635, in send
    await self.ensure_open()
  File "H:\下载\新建文件夹\QQbot\bot\python\lib\site-packages\websockets\legacy\protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) 指定Bot不存在; then sent 1000 (OK) 指定Bot不存在

**Comment by Reax1720** [comment]
message.py (130) - [ERROR] : 'str' object has no attribute 'choices' 这是怎么回事

**Comment by Reax1720** [comment]
[bot]person_123456789会话处理异常:'str' object has no attribute 'choices'
[bot]err:'str' object has no attribute 'choices'

**Comment by ROSV777** [comment]
"reverse_proxy": 的那个地址最后加上v1
