### ISSUE TITLE
[Bug]: 8月31号以后Api无法正常读取  You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY)

### ISSUE THREAD

**Issue by Shadowshark996** [RockChinQ/QChatGPT#561]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Windows10

### Python环境

Python3.10

### 异常情况

从8月31号开始，机器人不再正常回复，并出现如下报错
会话处理异常:You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.在此之前可正常使用

### 报错信息

[2023-09-02 16:55:48.032] message.py (26) - [INFO] : [person_1257487020]发送消息:你好
[2023-09-02 16:55:53.508] util.py (67) - [INFO] : message='OpenAI API response' path=http://api.openai.rockchin.top/v1/chat/completions processing_ms=None request_id=fb696858f54422be85e853e5ca2a705d response_code=401
[2023-09-02 16:55:53.521] util.py (67) - [INFO] : error_code=None error_message="You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys." error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-09-02 16:55:53.521] message.py (129) - [ERROR] : You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\qqbot\message.py", line 43, in process_normal_message
    text, finish_reason, funcs = session.query(text_message)
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\session.py", line 266, in query
    for resp in pkg.utils.context.get_openai_manager().request_completion(prompts):
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\manager.py", line 54, in request_completion
    for resp in request:
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\api\chat_completion.py", line 88, in __next__
    resp = self._req(**args)
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\api\model.py", line 54, in _req
    raise exception
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\api\model.py", line 33, in awrapper
    ret = await self.req_func(**kwargs)
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_requestor.py", line 382, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_requestor.py", line 728, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.
[2023-09-02 16:55:53.605] manager.py (397) - [INFO] : 通知管理员:person_1257487020会话处理异常:You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.
[2023-09-02 16:55:54.949] process.py (161) - [INFO] : 回复[person_1257487020]文字消息:[bot]err:You didn't provide an API key. You need to provide your API key in an Authorization header ...

**Comment by RockChinQ** [comment]
改成 https://api.openai.rockchin.top/v1 就可以了

**Comment by Shadowshark996** [comment]
大佬，改成 https://api.openai.rockchin.top/v1后依旧会有错误提示，内容如下:
[2023-09-03 00:40:55.419] message.py (26) - [INFO] : [person_1257487020]发送消息:你好
[2023-09-03 00:40:59.592] util.py (67) - [INFO] : message='OpenAI API response' path=https://api.openai.rockchin.top/v1/chat/completions processing_ms=5 request_id=8cdcde62c7420f53c436f3fab9ae0e78 response_code=404
[2023-09-03 00:40:59.596] util.py (67) - [INFO] : error_code=None error_message='This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?' error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-09-03 00:40:59.616] manager.py (397) - [INFO] : 通知管理员:person_1257487020API调用参数错误:This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

[2023-09-03 00:41:00.859] process.py (161) - [INFO] : 回复[person_1257487020]文字消息:[bot]err:API调用参数错误，请联系管理员，或等待修复

**Comment by RockChinQ** [comment]
那就是你模型写错了，你看看你config.py中openai_api_params中的model写对了没有

**Comment by Shadowshark996** [comment]
模型确认填写无误：
# 具体请查看OpenAI的文档: https://beta.openai.com/docs/api-reference/completions/create
# 请将内容修改到config.py中，请勿修改config-template.p
completion_api_params = {
    "model": "gpt-3.5-turbo",
    "temperature": 0.9,  # 数值越低得到的回答越理性，取值范围[0, 1]
    "top_p": 1,  # 生成的文本的文本与要求的符合度, 取值范围[0, 1]
    "frequency_penalty": 0.2,
    "presence_penalty": 1.0,
}
机器人依旧回复以下内容：
2023-09-03 11:36:40.026] message.py (26) - [INFO] : [person_1257487020]发送消息:你好
[2023-09-03 11:36:46.174] util.py (67) - [INFO] : message='OpenAI API response' path=https://api.openai.rockchin.top/v1/chat/completions processing_ms=7 request_id=505b9a01aab2bab3cc609b2a3788a518 response_code=404
[2023-09-03 11:36:46.187] util.py (67) - [INFO] : error_code=None error_message='This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?' error_param=model error_type=invalid_request_error message='OpenAI API error received' stream_error=False
[2023-09-03 11:36:46.192] manager.py (397) - [INFO] : 通知管理员:person_1257487020API调用参数错误:This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

[2023-09-03 11:36:47.688] process.py (161) - [INFO] : 回复[person_1257487020]文字消息:[bot]err:API调用参数错误，请联系管理员，或等待修复

**Comment by RockChinQ** [comment]
我这里测试没有这个问题，你尝试使用其他的代理试试看

**Comment by Shadowshark996** [comment]
问题已解决，是APIkey的问题，更换APIkey即可
