### ISSUE TITLE
[Bug]: 初始化失败:Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Programmer-Red** [RockChinQ/QChatGPT#581]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu 18

### Python环境

python3.10

### 异常情况

cq-http登录和启动正常，报错和配置文件如下

**main.py**

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 37, in _scan_once
    nextchar = string[idx]
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 79, in scan_once
    return _scan_once(string, idx)
  File "/usr/lib/python3/dist-packages/simplejson/scanner.py", line 39, in _scan_once
    raise JSONDecodeError(errmsg, string, idx)
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bc/robot/QChatGPT/main.py", line 213, in start
    qqbot = pkg.qqbot.manager.QQBotManager(first_time_init=first_time_init)
  File "/bc/robot/QChatGPT/pkg/qqbot/manager.py", line 130, in __init__
    self.adapter = NakuruProjectAdapter(config.nakuru_config)
  File "/bc/robot/QChatGPT/pkg/qqbot/sources/nakuru.py", line 188, in __init__
    self.bot_account_id = int(resp.json()['data']['user_id'])
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-10-05 20:10:21.251] main.py (284) - [ERROR] : 初始化失败:Expecting value: line 1 column 1 (char 0)
[2023-10-05 20:10:33.256] main.py (302) - [INFO] : host: localhost, port: 6700, http_port: 5700
[2023-10-05 20:10:33.256] main.py (303) - [CRITICAL] : 程序启动完成,如长时间未显示 "Protocol: connected" ,并且不回复消息,请检查config.py中的nakuru_config是否正确

**config.py配置文件**
![image](https://github.com/RockChinQ/QChatGPT/assets/45087936/23fc9076-7551-44ec-b595-46cd68829956)
<img width="422" alt="image" src="https://github.com/RockChinQ/QChatGPT/assets/45087936/a7c2b2a5-a014-43fa-b2d7-8b0218637b38">

**Comment by RockChinQ** [comment]
不太清楚，应该是nakuru或者go-cqhttp的问题，使用 go-cqhttp 最新版测试未发现此问题，可以再重新部署试一下
