### ISSUE TITLE
[Bug]: 机器人报错 code 502

### ISSUE THREAD

**Issue by Shadowshark996** [RockChinQ/QChatGPT#584]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Windows10

### Python环境

Python3.10

### 异常情况

对机器人发出消息后，机器人回复会话处理异常HTTP code 502 form API

### 报错信息

[2023-10-21 15:23:20.993] message.py (26) - [INFO] : [person_1257487020]发送消息:下午好
[2023-10-21 15:23:22.726] util.py (67) - [INFO] : message='OpenAI API response' path=https://api.openai.rockchin.top/v1/chat/completions processing_ms=None request_id=None response_code=502
[2023-10-21 15:23:22.734] message.py (129) - [ERROR] : HTTP code 502 from API ()
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    data = json.loads(rbody)
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\qqbot\message.py", line 43, in process_normal_message
    text, finish_reason, funcs = session.query(text_message)
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\session.py", line 266, in query
    for resp in pkg.utils.context.get_openai_manager().request_completion(prompts):
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\manager.py", line 54, in request_completion
    for resp in request:
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\api\chat_completion.py", line 88, in __next__
    resp = self._req(**args)
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\api\model.py", line 54, in _req
    raise exception
  File "C:\Users\Administrator\Desktop\Alice\QChatGPT\.\pkg\openai\api\model.py", line 33, in awrapper
    ret = await self.req_func(**kwargs)
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 219, in acreate
    response, _, api_key = await requestor.arequest(
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_requestor.py", line 384, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_requestor.py", line 738, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\Administrator\Desktop\Alice\python\lib\site-packages\openai\api_requestor.py", line 767, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 502 from API ()
[2023-10-21 15:23:22.747] manager.py (397) - [INFO] : 通知管理员:person_1257487020会话处理异常:HTTP code 502 from API ()
[2023-10-21 15:23:24.187] process.py (161) - [INFO] : 回复[person_1257487020]文字消息:[bot]err:出错了，请稍后再试

**Comment by RockChinQ** [comment]
反向代理的问题，现已恢复服务
