### ISSUE TITLE
[Bug]: 启动/更新时提示 ModuleNotFoundError: No module named 'openai.error'

### ISSUE THREAD

**Issue by a86296007** [RockChinQ/QChatGPT#585]
### 部署方式

安装器部署

### 登录框架

Mirai

### 系统环境

Windows Server 2019 Datacenter

### Python环境

Python 3.10

### 异常情况

启动时提示 ModuleNotFoundError: No module named 'openai.error' 随后卡死（已确认config.py中QQ相关信息填写无误）

### 报错信息

D:\QCG-2>cd QChatGPT

D:\QCG-2\QChatGPT>..\python\python.exe main.py
[2023-11-09 21:53:35.545] main.py (77) - [INFO] : 检查config模块完整性.
[2023-11-09 21:53:35.547] main.py (110) - [INFO] : 检查tips模块完整性.
Traceback (most recent call last):
  File "D:\QCG-2\QChatGPT\main.py", line 177, in start
    import pkg.openai.manager
  File "D:\QCG-2\QChatGPT\.\pkg\openai\manager.py", line 8, in <module>
    from pkg.openai.modelmgr import select_request_cls
  File "D:\QCG-2\QChatGPT\.\pkg\openai\modelmgr.py", line 9, in <module>
    import openai.error as aiE
ModuleNotFoundError: No module named 'openai.error'
[2023-11-09 21:53:35.952] main.py (284) - [ERROR] : 初始化失败:No module named 'openai.error'
[2023-11-09 21:53:37.954] main.py (290) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
[2023-11-09 21:53:49.956] main.py (298) - [INFO] : QQ: 2727399847, MAH: localhost:54142
[2023-11-09 21:53:49.956] main.py (299) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37

**Comment by shenby1999** [comment]
删除modelmgr.py文件第9行import openai.error as aiE 后正常启动 可能是openai库版本原因

**Comment by a86296007** [comment]
> 删除modelmgr.py文件第9行import openai.error as aiE 后正常启动 可能是openai库版本原因


删除这行之后是能启动了，但我尝试对话的时候没有任何回复也不报错（!help之类的命令倒是正常回复），继续发也不会触发并行限制提示（依然不回复），不知道是我的API配置有问题但报错的组件不存在了呢还是删掉之后整个功能都不运行了

**Comment by RockChinQ** [comment]
OpenAI库兼容性问题，请等待修复

**Comment by RockChinQ** [comment]
已修复，请等待下一版本更新
