### ISSUE TITLE
[Bug]: 启动报错

### ISSUE THREAD

**Issue by shenby1999** [RockChinQ/QChatGPT#586]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Windows10

### Python环境

Python 3.10.6 pip 23.3.1

### 异常情况

启动报错 main.py (284) - [ERROR] : 初始化失败:No module named 'openai.error'
删除modelmgr.py文件第9行import openai.error as aiE 后正常启动 可能是openai库版本原因

### 报错信息

Traceback (most recent call last):
  File "J:\workspaces\python\QChatGPT-2.6.1\main.py", line 471, in <module>
    main()
  File "J:\workspaces\python\QChatGPT-2.6.1\main.py", line 460, in main
    stop()
  File "J:\workspaces\python\QChatGPT-2.6.1\main.py", line 350, in stop
    import pkg.qqbot.manager
  File "J:\workspaces\python\QChatGPT-2.6.1\pkg\qqbot\manager.py", line 11, in <module>
    import pkg.openai.session
  File "J:\workspaces\python\QChatGPT-2.6.1\pkg\openai\session.py", line 11, in <module>
    import pkg.openai.manager
  File "J:\workspaces\python\QChatGPT-2.6.1\pkg\openai\manager.py", line 8, in <module>
    from pkg.openai.modelmgr import select_request_cls
  File "J:\workspaces\python\QChatGPT-2.6.1\pkg\openai\modelmgr.py", line 9, in <module>
    import openai.error as aiE
ModuleNotFoundError: No module named 'openai.error'

**Comment by RockChinQ** [comment]
OpenAI库兼容性问题，统一到 #585 跟踪
