### ISSUE TITLE
[Bug]: 初始化失败:module 'openai' has no attribute 'Client'

### ISSUE THREAD

**Issue by o3oGekkou** [RockChinQ/QChatGPT#589]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu 18

### Python环境

py3.10

### 异常情况

重新部署出现这个问题
Traceback (most recent call last):
  File "/root/QChatGPT/main.py", line 177, in start
    import pkg.openai.manager
  File "/root/QChatGPT/pkg/openai/manager.py", line 8, in <module>
    from pkg.openai.modelmgr import select_request_cls
  File "/root/QChatGPT/pkg/openai/modelmgr.py", line 11, in <module>
    from pkg.openai.api.model import RequestBase
  File "/root/QChatGPT/pkg/openai/api/model.py", line 9, in <module>
    class RequestBase:
  File "/root/QChatGPT/pkg/openai/api/model.py", line 11, in RequestBase
    client: openai.Client
AttributeError: module 'openai' has no attribute 'Client'
[2023-11-10 04:46:45.149] main.py (287) - [ERROR] : 初始化失败:module 'openai' has no attribute 'Client'

**Comment by RockChinQ** [comment]
更新依赖库：
```bash
pip install -U openai
```

**Comment by o3oGekkou** [comment]
> 更新依赖库：
> 
> ```shell
> pip install -U openai
> ```

ok解决了 谢谢
