### ISSUE TITLE
[Bug]: No module named 'openai.error'

### ISSUE THREAD

**Issue by kjjiji** [RockChinQ/QChatGPT#593]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

win11

### Python环境

python3

### 异常情况

main.py (284) - [ERROR] : 初始化失败:No module named 'openai.error'

### 报错信息

Traceback (most recent call last):
  File "E:\1414\111\QChatGPT\main.py", line 177, in start
    import pkg.openai.manager
  File "E:\1414\111\QChatGPT\.\pkg\openai\manager.py", line 8, in <module>
    from pkg.openai.modelmgr import select_request_cls
  File "E:\1414\111\QChatGPT\.\pkg\openai\modelmgr.py", line 9, in <module>
    import openai.error as aiE
ModuleNotFoundError: No module named 'openai.error'
[2023-11-12 22:15:58.173] main.py (284) - [ERROR] : 初始化失败:No module named 'openai.error'
[2023-11-12 22:16:00.189] main.py (290) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
[2023-11-12 22:16:12.196] main.py (298) - [INFO] : QQ: 2702198677, MAH: localhost:8080
[2023-11-12 22:16:12.196] main.py (299) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37

**Comment by RockChinQ** [comment]
`openai` 最新版移除了 openai.error 模块，更新 QChatGPT 到最新版本即可解决：
从本仓库 releases 页面下载最新发行版的 zip 压缩包，解压覆盖现部署的 QChatGPT 代码。

**Comment by kjjiji** [comment]
这是来自自动回复邮件本人有空会及时回复，谢谢！

**Comment by RockChinQ** [comment]
更新方式：https://github.com/RockChinQ/QChatGPT/discussions/595
