### ISSUE TITLE
[Bug]: [ERROR] : 初始化失败:No module named 'CallingGPT'

### ISSUE THREAD

**Issue by JJH529529** [RockChinQ/QChatGPT#616]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Ubuntu

### Python环境

Python 3.10

### 异常情况

输出完./run-bot.sh,后提示没有模块CallingGPT

### 报错信息

Traceback (most recent call last):
  File "/root/bot/QChatGPT/main.py", line 218, in start
    import pkg.openai.manager
  File "/root/bot/QChatGPT/pkg/openai/manager.py", line 5, in <module>
    from ..openai import keymgr
  File "/root/bot/QChatGPT/pkg/openai/keymgr.py", line 5, in <module>
    from ..plugin import host as plugin_host
  File "/root/bot/QChatGPT/pkg/plugin/host.py", line 24, in <module>
    from CallingGPT.session.session import Session
ModuleNotFoundError: No module named 'CallingGPT'
[2023-11-26 11:54:30.033] main.py (328) - [ERROR] : 初始化失败:No module named 'CallingGPT'

**Comment by RockChinQ** [comment]
你部署方式到底是什么

**Comment by RockChinQ** [comment]
如果是手动部署，按照手动部署的步骤使用命令`pip install -r requirements.txt`把依赖装全。如果是安装器部署，到`/root/bot/`目录，执行命令`./python/python -m pip install -r QChatGPT/requirements.txt`
