### ISSUE TITLE
[Bug]: 启动异常 找不到模块CallingGPT

### ISSUE THREAD

**Issue by VegaEC** [RockChinQ/QChatGPT#620]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Win11

### Python环境

3.10

### 异常情况

安装完后打开runbot提示此错误

### 报错信息

Traceback (most recent call last):
  File "E:\Q-ChatGPT\QChatGPT\main.py", line 218, in start
    import pkg.openai.manager
  File "E:\Q-ChatGPT\QChatGPT\.\pkg\openai\manager.py", line 5, in <module>
    from ..openai import keymgr
  File "E:\Q-ChatGPT\QChatGPT\.\pkg\openai\keymgr.py", line 5, in <module>
    from ..plugin import host as plugin_host
  File "E:\Q-ChatGPT\QChatGPT\.\pkg\plugin\host.py", line 24, in <module>
    from CallingGPT.session.session import Session
ModuleNotFoundError: No module named 'CallingGPT'
[2023-11-28 21:33:34.099] main.py (328) - [ERROR] : 初始化失败:No module named 'CallingGPT'

**Comment by RockChinQ** [comment]
重复问题，搜一下前几天一个issue吧
