### ISSUE TITLE
[Bug]: No module named 'CallingGPT'

### ISSUE THREAD

**Issue by CreativeBiao** [RockChinQ/QChatGPT#629]
### 部署方式

一键安装包部署

### 登录框架

Mirai

### 系统环境

win11

### Python环境

python3.9

### 异常情况

打开run-bot.bat时提示：初始化失败:No module named 'CallingGPT'

### 报错信息

D:\EDGE下载\QChatGPT>..\python\python.exe main.py
[2023-12-11 02:05:00.664] main.py (118) - [INFO] : 检查config模块完整性.
[2023-12-11 02:05:00.666] main.py (151) - [INFO] : 检查tips模块完整性.
Traceback (most recent call last):
  File "D:\EDGE下载\QChatGPT\main.py", line 218, in start
    import pkg.openai.manager
  File "D:\EDGE下载\QChatGPT\.\pkg\openai\manager.py", line 5, in <module>
    from ..openai import keymgr
  File "D:\EDGE下载\QChatGPT\.\pkg\openai\keymgr.py", line 5, in <module>
    from ..plugin import host as plugin_host
  File "D:\EDGE下载\QChatGPT\.\pkg\plugin\host.py", line 24, in <module>
    from CallingGPT.session.session import Session
ModuleNotFoundError: No module named 'CallingGPT'
[2023-12-11 02:05:01.249] main.py (328) - [ERROR] : 初始化失败:No module named 'CallingGPT'
[2023-12-11 02:05:03.255] main.py (334) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
[2023-12-11 02:05:15.260] main.py (342) - [INFO] : QQ: 2609413463, MAH: localhost:8080

**Comment by RockChinQ** [comment]
#616 #621
