### ISSUE TITLE
[Bug]: 百度和阿里不能使用

### ISSUE THREAD

**Issue by jsxupeng** [RockChinQ/QChatGPT#630]
### 部署方式

Docker部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu

### Python环境

py310

### 异常情况

百度和阿里不能使用
failed to get token encoder for model ERNIE-Bot-turbo: no encoding for model ERNIE-Bot-turbo, using encoder for gpt-3.5-turbo

**Comment by RockChinQ** [comment]
你搭了 one-api 才能用啊，https://github.com/songquanpeng/one-api

**Comment by jsxupeng** [comment]
自己搭了 星火能用 chatglm能用，chatgptapi能用，就百度和阿里不能用

**Comment by jsxupeng** [comment]
failed to get token encoder for model ERNIE-Bot-turbo: no encoding for model ERNIE-Bot-turbo, using encoder for gpt-3.5-turbo
这个是oneapi的日志

**Comment by RockChinQ** [comment]
你发一下模型的配置信息，我调试一下；还有 one-api 和 QChatGPT 的控制台日志，多发一点

**Comment by jsxupeng** [comment]
qchatgpt：
stderr: [37m[2023-12-11 11:20:13.654] process.py (153) - [INFO] : 回复[person_840651001]文字消息:[Switcher] 已切换至 OneAPI 百度文心千帆ERNIE-Bot-Turbo[0m
stderr: [37m[2023-12-11 11:20:13.661] process.py (183) - [INFO] : [风控] 强制延迟1.61秒(如需关闭，请到config.py修改force_delay_range字段)[0m
stderr: [37m[2023-12-11 11:20:18.764] application.py (95) - [INFO] : Event: handling a event: GroupMessage[0m
stderr: [37m[2023-12-11 11:20:18.824] application.py (95) - [INFO] : Event: handling a event: FriendMessage[0m
stderr: [37m[2023-12-11 11:20:18.828] message.py (27) - [INFO] : [person_840651001]发送消息:你好[0m
stderr: [37m[2023-12-11 11:20:19.745] _client.py (1013) - [INFO] : HTTP Request: POST http://127.0.0.1:3005/v1/chat/completions "HTTP/1.1 200 OK"[0m
stderr: [31m[2023-12-11 11:20:19.746] message.py (130) - [ERROR] : 'NoneType' object is not subscriptable[0m
stderr: Traceback (most recent call last):
stderr:   File "/QChatGPT/pkg/qqbot/message.py", line 44, in process_normal_message
stderr:     text, finish_reason, funcs = session.query(text_message)
stderr:   File "/QChatGPT/pkg/openai/session.py", line 265, in query
stderr:     for resp in context.get_openai_manager().request_completion(prompts):
stderr:   File "/QChatGPT/pkg/openai/manager.py", line 59, in request_completion
stderr:     for resp in request:
stderr:   File "/QChatGPT/pkg/openai/api/chat_completion.py", line 96, in __next__
stderr:     choice0 = resp.choices[0]
stderr: TypeError: 'NoneType' object is not subscriptable
stderr: [37m[2023-12-11 11:20:19.788] manager.py (392) - [INFO] : 通知管理员:person_840651001会话处理异常:'NoneType' object is not subscriptable[0m
stderr: [37m[2023-12-11 11:20:20.080] process.py (153) - [INFO] : 回复[person_840651001]文字消息:[bot]err:出错了，请稍后再试[0m


------------------------------------------
oneapi：
stdout: [SYS] 2023/12/11 - 10:41:10 | database migrated 
stdout: [SYS] 2023/12/11 - 10:41:10 | REDIS_CONN_STRING not set, Redis is not enabled 
stdout: [SYS] 2023/12/11 - 10:41:10 | initializing token encoders 
stdout: [SYS] 2023/12/11 - 10:41:11 | token encoders initialized 
stderr: [SYS] 2023/12/11 - 11:02:38 | failed to get token encoder for model ERNIE-Bot-turbo: no encoding for model ERNIE-Bot-turbo, using encoder for gpt-3.5-turbo 
stdout: [INFO] 2023/12/11 - 11:02:38 | 20231211110237903842824wxu57yTr | user 1 has enough quota 9999786468, trusted and no need to pre-consume 
stderr: [ERR] 2023/12/11 - 11:02:38 | 20231211110237903842824wxu57yTr | relay error (channel #2): message content can not be empty (request id: 20231211110237903842824wxu57yTr) 
stdout: [GIN] 2023/12/11 - 11:02:38 | 20231211110237903842824wxu57yTr | 200 |   847.27451ms |      172.16.0.1 |    POST /v1/chat/completions
stderr: 2023/12/11 11:02:57 [sessions] ERROR! securecookie: the value is not valid
stdout: [GIN] 2023/12/11 - 11:02:57 | 20231211110257162047460Bd8ARfag | 401 |     934.707µs |   192.168.5.201 |     GET /api/log/?p=0&type=0&username=&token_name=&model_name=&start_timestamp=0&end_timestamp=1702267376&channel=
stdout: [GIN] 2023/12/11 - 11:02:57 | 20231211110257176458866AUHPtW6g | 200 |    2.347158ms |   192.168.5.201 |     GET /api/status
stdout: [GIN] 2023/12/11 - 11:02:58 | 20231211110258117205106mUKXExAV | 200 |    2.330095ms |   192.168.5.201 |     GET /login?expired=true
stdout: [GIN] 2023/12/11 - 11:02:58 | 20231211110258811844082KQkRsEcn | 200 |     705.946µs |   192.168.5.201 |     GET /api/status
stdout: [GIN] 2023/12/11 - 11:19:51 | 20231211111951785387387EdbmdZsf | 200 |    1.728374ms |   192.168.5.201 |     GET /api/status
stderr: 2023/12/11 11:20:04 [sessions] ERROR! securecookie: the value is not valid
stdout: [GIN] 2023/12/11 - 11:20:04 | 20231211112004530735191rqY5I18p | 200 |  151.777063ms |   192.168.5.201 |    POST /api/user/login
stdout: [GIN] 2023/12/11 - 11:20:04 | 20231211112004918849103FzmrA0d2 | 200 |    4.865336ms |   192.168.5.201 |     GET /api/token/?p=0
stdout: [GIN] 2023/12/11 - 11:20:08 | 202312111120081153990472Wwzji4a | 200 |     4.08236ms |   192.168.5.201 |     GET /api/log/?p=0&type=0&username=&token_name=&model_name=&start_timestamp=0&end_timestamp=1702268407&channel=
stdout: [INFO] 2023/12/11 - 11:20:19 | 202312111120194943109175noqlpGA | user 1 has enough quota 9999786468, trusted and no need to pre-consume 
stdout: [GIN] 2023/12/11 - 11:20:19 | 202312111120194943109175noqlpGA | 200 |  246.559565ms |      172.16.0.1 |    POST /v1/chat/completions
stderr: [ERR] 2023/12/11 - 11:20:19 | 202312111120194943109175noqlpGA | relay error (channel #2): message content can not be empty (request id: 202312111120194943109175noqlpGA) 

百度后台能考到调用记录，但是是调用失败

**Comment by RockChinQ** [comment]
检查了一下这个模型名称也没有写错，然后 QChatGPT 调用是正常的，可以去 One API 的仓库看看有没有具体的分析
