### ISSUE TITLE
[Bug]: !cfg命令失效

### ISSUE THREAD

**Issue by Vlfx1** [RockChinQ/QChatGPT#638]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Ubuntu Server 20.04 LTS 64bit

### Python环境

Python 3.11

### 异常情况

!cfg 命令失效

### 日志信息

[2023-12-18 21:40:37.594] /usr/local/lib/python3.11/dist-packages/nakuru/application.py (95) - [INFO] :
Event: handling a event: FriendMessage
[2023-12-18 21:40:37.595] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py (11) - [INFO] :
[person_1042075652]发起指令:!~openai_config.api_key
[2023-12-18 21:40:37.595] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/process.py (153) - [INFO] :
回复[person_1042075652]文字消息:[bot]err:未找到配置项 openai_config.api_key
[2023-12-18 21:42:01.357] /usr/local/lib/python3.11/dist-packages/nakuru/application.py (95) - [INFO] :
Event: handling a event: FriendMessage
[2023-12-18 21:42:01.358] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py (11) - [INFO] :
[person_1042075652]发起指令:!cfg default_prompt "我是Rock Chin"
[2023-12-18 21:42:01.358] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/process.py (153) - [INFO] :
回复[person_1042075652]文字消息:[bot]err:未找到配置项 default_prompt

[2023-12-18 21:45:48.305] /usr/local/lib/python3.11/dist-packages/nakuru/application.py (95) - [INFO] :
Event: handling a event: FriendMessage
[2023-12-18 21:45:48.306] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py (11) - [INFO] :
[person_1042075652]发起指令:!~ completion_api_params.model "gpt-3.5-turbo"
[2023-12-18 21:45:48.306] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/manager.py (392) - [INFO] :
通知管理员:person_1042075652指令执行失败:invalid syntax (<string>, line 1)
[2023-12-18 21:45:48.308] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py (46) - [ERROR] :
invalid syntax (<string>, line 1)
Traceback (most recent call last):
  File "/home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py", line 39, in process_command
    reply = cmdmgr.execute(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/cmds/aamgr.py", line 268, in execute
    execed, reply = node['cls'].process(ctx)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/cmds/system/cconfig.py", line 100, in process
    return True, config_operation(ctx.command, ctx.params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/cmds/system/cconfig.py", line 65, in config_operation
    cfg_value = eval(cfg_value)
                ^^^^^^^^^^^^^^^
  File "<string>", line 1
    completion_api_params.model "gpt-3.5-turbo"
                                ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax
[2023-12-18 21:45:48.309] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/process.py (153) - [INFO] :
回复[person_1042075652]文字消息:[bot]err:invalid syntax (<string>, line 1)

**Comment by RockChinQ** [comment]
已修复，将在下一版本中包含。
