### ISSUE TITLE
[Bug]: 添加了QChatAIPaint插件后主程序无法启动（或许我应该提交在插件的issue下？）

### ISSUE THREAD

**Issue by youyi0218** [RockChinQ/QChatGPT#653]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

proot装的Ubuntu

### Python环境

3.10

### QChatGPT版本

2.6.9

### 异常情况

在跑起来之后通过机器人命令安装了QChatAIPaint插件，然后！reload后台日志机器人报错但未停止响应，但是与之对话无反应。配置好插件的config并安装了插件所需的pydantic==1.8.2之后主程序启动就报错

### 日志信息

Traceback (most recent call last):
  File "/root/QChatGPT/main.py", line 57, in <module>
    from pkg.utils.log import init_runtime_log_file, reset_logging
  File "/root/QChatGPT/pkg/utils/log.py", line 6, in <module>
    from . import context
  File "/root/QChatGPT/pkg/utils/context.py", line 7, in <module>
    from ..openai import manager as openai_mgr
  File "/root/QChatGPT/pkg/openai/manager.py", line 3, in <module>
    import openai
  File "/usr/local/lib/python3.10/dist-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/usr/local/lib/python3.10/dist-packages/openai/types/__init__.py", line 5, in <module>
    from .edit import Edit as Edit
  File "/usr/local/lib/python3.10/dist-packages/openai/types/edit.py", line 6, in <module>
    from .._models import BaseModel
  File "/usr/local/lib/python3.10/dist-packages/openai/_models.py", line 33, in <module>
    from ._utils import (
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/__init__.py", line 2, in <module>
    from ._utils import flatten as flatten
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 24, in <module>
    from .._compat import parse_date as parse_date
  File "/usr/local/lib/python3.10/dist-packages/openai/_compat.py", line 55, in <module>
    from pydantic.typing import is_union as is_union
ImportError: cannot import name 'is_union' from 'pydantic.typing' (/usr/local/lib/python3.10/dist-packages/pydantic/typing.py)

### 启用的插件

QChatAIPaint
WebwlkrPlugin

**Comment by RockChinQ** [comment]
插件问题前往插件仓库提交issue
