### ISSUE TITLE
[Bug]:  运行主程序超时

### ISSUE THREAD

**Issue by ivring2** [RockChinQ/QChatGPT#654]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Ubuntu22.04

### Python环境

python3.9.5

### QChatGPT版本

最新版本

### 异常情况

Traceback (most recent call last):
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 319, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/preject/qqbot/QChatGPT/main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/home/preject/qqbot/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
[2024-01-04 12:59:34.315] main.py (324) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 319, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/preject/qqbot/QChatGPT/main.py", line 327, in run_bot_wrapper
    raise e
  File "/home/preject/qqbot/QChatGPT/main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/home/preject/qqbot/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by RockChinQ** [comment]
估计是连不通mirai吧，检查一下mirai有没有正常运行，mirai-api-http是否配置正确，端口是否正常放行（检查系统防火墙）

**Comment by ivring2** [comment]
mirai 运行 正常 配置也正常 端口也能通 就是超时

**Comment by RockChinQ** [comment]
再次按照文档检查是否配置 mirai-api-http 并且在 config.py 填写了正确的配置。实在不行把所有日志都贴出来，尽可能多。

**Comment by ivring2** [comment]
2024-01-04 16:39:09 - ERROR    
[2024-01-04 16:39:09.654] base.py (43) - [ERROR] : 
Traceback (most recent call last):
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 319, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/preject/qqbot/QChatGPT/main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/home/preject/qqbot/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
[2024-01-04 16:39:09.659] main.py (324) - [ERROR] : 捕捉到未知异常:, 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 319, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 139, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/http.py", line 120, in read_response
    status_line = await read_line(stream)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/http.py", line 194, in read_line
    line = await stream.readline()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/preject/qqbot/QChatGPT/main.py", line 327, in run_bot_wrapper
    raise e
  File "/home/preject/qqbot/QChatGPT/main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "/home/preject/qqbot/QChatGPT/pkg/qqbot/sources/yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 169, in __aexit__
    self._do_exit(exc_type)
  File "/root/anaconda3/envs/qqgpt/lib/python3.9/site-packages/websockets/legacy/async_timeout.py", line 252, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

Session was closed

**Comment by RockChinQ** [comment]
还是不太清楚，如果你确定你的 mirai-api-http（不是mirai本身） 版本正确、配置正确、运行正常，并且 `config.py` 中填写的 mirai_http_api 配置信息符合 mirai-api-http 的设置。那么你需要确定 QChatGPT 实例能正常访问 mirai-api-http 提供的端口，这种情况下，异常通常是由防火墙拦截、mirai-api-http 端口和其他程序冲突等问题造成的。

**Comment by ivring2** [comment]
谢谢 哥 现在机器人通了 但是只会回复回复[group_728694710]文字消息:[bot]err:'NoneType' object is not subscriptable 这个是哪里出了问题

**Comment by RockChinQ** [comment]
还是需要完整的日志才能知道是什么问题
