### ISSUE TITLE
[Bug]: No module named 'openai.types'

### ISSUE THREAD

**Issue by Sprt98** [RockChinQ/QChatGPT#662]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Windows 10、中国大陆

### Python环境

Python 3.10.9

### QChatGPT版本

v2.6.9

### 异常情况

在更新到最新版本之后，出现：
Traceback (most recent call last):
  File "F:\bot3\QChatGPT\main.py", line 57, in <module>
    from pkg.utils.log import init_runtime_log_file, reset_logging
  File "F:\bot3\QChatGPT\.\pkg\utils\log.py", line 6, in <module>
    from . import context
  File "F:\bot3\QChatGPT\.\pkg\utils\context.py", line 7, in <module>
    from ..openai import manager as openai_mgr
  File "F:\bot3\QChatGPT\.\pkg\openai\manager.py", line 4, in <module>
    from openai.types import images_response
ModuleNotFoundError: No module named 'openai.types'
之后再启动机器人的时候也出现这个错误。

### 日志信息

[2024-01-14 18:54:50.290] F:\bot3\QChatGPT\main.py (73) - [INFO] :
检查config模块完整性.
[2024-01-14 18:54:50.305] F:\bot3\QChatGPT\main.py (101) - [INFO] :
检查tips模块完整性.
[2024-01-14 18:56:09.540] F:\bot3\QChatGPT\.\pkg\openai\keymgr.py (61) - [INFO] :
使用api-key:api1
[2024-01-14 18:56:09.555] F:\bot3\QChatGPT\.\pkg\openai\manager.py (30) - [INFO] :
文字总使用量：822320
[2024-01-14 18:56:09.563] F:\bot3\QChatGPT\.\pkg\qqbot\manager.py (90) - [INFO] :
Use adapter:nakuru
[2024-01-14 18:56:10.115] F:\bot3\QChatGPT\.\pkg\qqbot\manager.py (214) - [INFO] :
加载禁用列表: person: [2854196310], group: [204785790, 614876491]
[2024-01-14 18:56:10.132] F:\bot3\QChatGPT\.\pkg\plugin\host.py (90) - [INFO] :
加载插件
[2024-01-14 18:56:10.770] F:\bot3\QChatGPT\.\pkg\plugin\models.py (219) - [INFO] :
插件注册完成: n='BanMassage', d='屏蔽插件，若匹配到关键词则屏蔽，不回复', v=0.1, a='多米诺艾尔' (<class 'plugins.BanMassage.main.HelloPlugin'>)
[2024-01-14 18:56:10.779] F:\bot3\QChatGPT\.\pkg\plugin\host.py (82) - [INFO] :
加载模块: plugins/BanMassage/main.py 成功
[2024-01-14 18:56:10.792] F:\bot3\QChatGPT\.\pkg\plugin\host.py (82) - [INFO] :
加载模块: plugins/ChatWaifu/config.py 成功
[2024-01-14 18:57:49.311] F:\bot3\QChatGPT\.\pkg\plugin\models.py (219) - [INFO] :
插件注册完成: n='ChatWaifu', d='这是一个语音程序，可以让你的GPT3生成语音发送到QQ群里', v=0.2, a='多米诺艾尔' (<class 'plugins.ChatWaifu.main.HelloPlugin'>)
[2024-01-14 18:57:49.311] F:\bot3\QChatGPT\.\pkg\plugin\host.py (82) - [INFO] :
加载模块: plugins/ChatWaifu/main.py 成功
[2024-01-14 18:57:49.327] F:\bot3\QChatGPT\.\pkg\plugin\host.py (82) - [INFO] :
加载模块: plugins/headers.py 成功
[2024-01-14 18:57:51.090] F:\bot3\QChatGPT\.\pkg\plugin\models.py (219) - [INFO] :
插件注册完成: n='Hello', d='hello world', v=0.1, a='RockChinQ' (<class 'plugins.randomimg.main.HelloPlugin'>)
[2024-01-14 18:57:51.090] F:\bot3\QChatGPT\.\pkg\plugin\host.py (82) - [INFO] :
加载模块: plugins/randomimg/main.py 成功
[2024-01-14 18:57:51.096] F:\bot3\QChatGPT\.\pkg\plugin\host.py (107) - [INFO] :
初始化插件
[2024-01-14 18:57:51.096] F:\bot3\QChatGPT\.\pkg\plugin\host.py (115) - [INFO] :
插件 BanMassage 已初始化
[2024-01-14 18:57:51.097] F:\bot3\QChatGPT\.\pkg\plugin\host.py (115) - [INFO] :
插件 Hello 已初始化
[2024-01-14 18:57:51.098] F:\bot3\QChatGPT\.\pkg\plugin\host.py (115) - [INFO] :
插件 ChatWaifu 已初始化
[2024-01-14 18:57:51.131] F:\bot3\python\lib\site-packages\nakuru\application.py (59) - [INFO] :
Protocol: connected
[2024-01-14 18:57:53.115] F:\bot3\QChatGPT\main.py (261) - [INFO] :
您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
[2024-01-14 18:58:05.128] F:\bot3\QChatGPT\main.py (273) - [INFO] :
host: localhost, port: 6700, http_port: 5700
[2024-01-14 18:58:05.131] F:\bot3\QChatGPT\main.py (274) - [CRITICAL] :
程序启动完成,如长时间未显示 "Protocol: connected" ,并且不回复消息,请检查config.py中的nakuru_config是否正确
[2024-01-14 18:58:26.366] F:\bot3\QChatGPT\main.py (301) - [INFO] :
新版本可用，请发送 !update 进行自动更新
更新日志:
v2.6.9 完善的使用量分析
v2.6.8 支持 Gemini Pro 模型
v2.6.7 修复绘图命令不可用问题
v2.6.6 修复反代失败
v2.6.5 优化导入
v2.6.4 修复插件安装问题
v2.6.3 适配 OpenAI 新版本 API
v2.6.0 One API支持
v2.5.2 优化函数调用逻辑、api-key主动负载
v2.5.1 功能适配、token bugfix
v2.5.0 支持函数调用功能
v2.4.7 gpt-turbo-16k模型支持
v2.4.6 消息禁用、会话自动重置
v2.4.5 增强的!cfg命令
v2.4.4 热重载bug，消息主动延迟
v2.4.3.1 fixVerNum
v2.4.3 优化插件更新逻辑
v2.4.2 细化到单个群的响应规则
v2.4.1 完善数据统计
[2024-01-14 18:58:26.991] F:\bot3\QChatGPT\main.py (313) - [CRITICAL] :
[公告]<2023-08-01 10:49:26> 现已支持GPT函数调用功能，欢迎了解：https://github.com/RockChinQ/QChatGPT/wiki/%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8-%E5%86%85%E5%AE%B9%E5%87%BD%E6%95%B0
[2024-01-14 18:58:26.992] F:\bot3\QChatGPT\main.py (313) - [CRITICAL] :
[公告]<2023-11-10 12:20:09> OpenAI 库1.0版本已发行，若出现 OpenAI 调用问题，请更新 QChatGPT 版本。详见项目主页：https://github.com/RockChinQ/QChatGPT
[2024-01-14 18:58:26.994] F:\bot3\QChatGPT\main.py (313) - [CRITICAL] :
[公告]<2023-11-13 18:02:39> 近期 OpenAI 接口改动频繁，正在积极适配并添加新功能，请尽快更新到最新版本，更新方式：https://github.com/RockChinQ/QChatGPT/discussions/595
[2024-01-14 18:58:26.995] F:\bot3\QChatGPT\main.py (313) - [CRITICAL] :
[公告]<2023-12-07 9:20:00> QChatGPT 一周年啦！感谢大家的选择和支持，RockChinQ 在此衷心感谢素未谋面但又至关重要的你们每一个人，愿 AI 与我们同在！欢迎前往：https://github.com/RockChinQ/QChatGPT/discussions/627 参与讨论。
[2024-01-14 18:59:13.332] F:\bot3\python\lib\site-packages\nakuru\application.py (95) - [INFO] :
Event: handling a event: FriendMessage
[2024-01-14 18:59:13.376] F:\bot3\QChatGPT\.\pkg\qqbot\command.py (27) - [INFO] :
[person_2357901854]发起指令:!update
[2024-01-14 18:59:13.379] F:\bot3\QChatGPT\.\pkg\qqbot\process.py (157) - [INFO] :
回复[person_2357901854]文字消息:[bot]正在更新，请耐心等待，请勿重复发起更新...
[2024-01-14 18:59:14.280] F:\bot3\QChatGPT\.\pkg\utils\updater.py (96) - [INFO] :
更新日志: ['v2.6.9 完善的使用量分析', 'v2.6.8 支持 Gemini Pro 模型', 'v2.6.7 修复绘图命令不可用问题', 'v2.6.6 修复反代失败', 'v2.6.5 优化导入', 'v2.6.4 修复插件安装问题', 'v2.6.3 适配 OpenAI 新版本 API', 'v2.6.0 One API支持', 'v2.5.2 优化函数调用逻辑、api-key主动负载', 'v2.5.1 功能适配、token bugfix', 'v2.5.0 支持函数调用功能', 'v2.4.7 gpt-turbo-16k模型支持', 'v2.4.6 消息禁用、会话自动重置', 'v2.4.5 增强的!cfg命令', 'v2.4.4 热重载bug，消息主动延迟', 'v2.4.3.1 fixVerNum', 'v2.4.3 优化插件更新逻辑', 'v2.4.2 细化到单个群的响应规则', 'v2.4.1 完善数据统计', 'v2.4.0 支持go-cqhttp登录']
[2024-01-14 18:59:14.280] F:\bot3\QChatGPT\.\pkg\utils\updater.py (105) - [INFO] :
开始下载最新版本: https://api.github.com/repos/RockChinQ/QChatGPT/zipball/v2.6.9
[2024-01-14 18:59:16.335] F:\bot3\QChatGPT\.\pkg\utils\updater.py (124) - [INFO] :
下载最新版本完成: temp/updater/v2.6.9.zip
[2024-01-14 18:59:17.588] F:\bot3\QChatGPT\.\pkg\qqbot\manager.py (340) - [INFO] :
通知管理员:已更新到最新版本: v2.6.9
更新日志:
v2.6.9 完善的使用量分析
v2.6.8 支持 Gemini Pro 模型
v2.6.7 修复绘图命令不可用问题
v2.6.6 修复反代失败
v2.6.5 优化导入
v2.6.4 修复插件安装问题
v2.6.3 适配 OpenAI 新版本 API
v2.6.0 One API支持
v2.5.2 优化函数调用逻辑、api-key主动负载
v2.5.1 功能适配、token bugfix
v2.5.0 支持函数调用功能
v2.4.7 gpt-turbo-16k模型支持
v2.4.6 消息禁用、会话自动重置
v2.4.5 增强的!cfg命令
v2.4.4 热重载bug，消息主动延迟
v2.4.3.1 fixVerNum
v2.4.3 优化插件更新逻辑
v2.4.2 细化到单个群的响应规则
v2.4.1 完善数据统计
完整的更新日志请前往 https://github.com/RockChinQ/QChatGPT/releases 查看
[2024-01-14 18:59:17.599] F:\bot3\QChatGPT\.\pkg\utils\reloader.py (27) - [INFO] :
执行程序关闭流程
[2024-01-14 18:59:17.658] F:\bot3\QChatGPT\.\main.py (423) - [INFO] :
持久化session: person_2357901854
[2024-01-14 18:59:17.806] F:\bot3\QChatGPT\.\pkg\utils\reloader.py (17) - [INFO] :
reload module: audit.gatherer, path: audit/gatherer.py
[2024-01-14 18:59:17.814] F:\bot3\QChatGPT\.\pkg\utils\reloader.py (17) - [INFO] :
reload module: audit.identifier, path: audit/identifier.py
[2024-01-14 18:59:17.824] F:\bot3\QChatGPT\.\pkg\utils\reloader.py (17) - [INFO] :
reload module: config.manager, path: config/manager.py
[2024-01-14 18:59:17.826] F:\bot3\QChatGPT\.\pkg\utils\reloader.py (17) - [INFO] :
reload module: config.model, path: config/model.py
[2024-01-14 18:59:17.831] F:\bot3\QChatGPT\.\pkg\utils\reloader.py (17) - [INFO] :
reload module: database.manager, path: database/manager.py
[2024-01-14 18:59:17.852] F:\bot3\QChatGPT\.\pkg\utils\reloader.py (17) - [INFO] :
reload module: openai.api.chat_completion, path: openai/api/chat_completion.py
[2024-01-14 18:59:17.869] F:\bot3\QChatGPT\.\pkg\qqbot\manager.py (340) - [INFO] :
通知管理员:更新失败:No module named 'openai.types'
[2024-01-14 18:59:49.121] F:\bot3\python\lib\site-packages\nakuru\application.py (95) - [INFO] :
Event: handling a event: FriendMessage

**Comment by RockChinQ** [comment]
更新一下 openai 库到 1.0 以上。
pip install -U openai
