### ISSUE TITLE
[Bug]:  !cfg 正常 !~ 报错 

### ISSUE THREAD

**Issue by Vlfx1** [RockChinQ/QChatGPT#663]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Ubuntu Server 20.04 LTS 64bit 中国大陆

### Python环境

Python 3.11

### QChatGPT版本

v2.6.9

### 异常情况

!cfg 命令可以正常使用，!~报错

### 日志信息

[2024-01-15 17:47:02.919] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py (11) - [INFO] :
[person_1042075652]发起指令:!~ prompt_submit_len...
[2024-01-15 17:47:02.919] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/manager.py (396) - [INFO] :
通知管理员:person_1042075652指令执行失败:invalid syntax (<string>, line 1)
[2024-01-15 17:47:02.921] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py (46) - [ERROR] :
invalid syntax (<string>, line 1)
Traceback (most recent call last):
  File "/home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py", line 39, in process_command
    reply = cmdmgr.execute(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/cmds/aamgr.py", line 267, in execute
    execed, reply = node['cls'].process(ctx)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/cmds/system/cconfig.py", line 90, in process
    return True, config_operation(ctx.command, ctx.params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/cmds/system/cconfig.py", line 57, in config_operation
    cfg_value = eval(cfg_value)
                ^^^^^^^^^^^^^^^
  File "<string>", line 1
    prompt_submit_length 1024
                         ^^^^
SyntaxError: invalid syntax
[2024-01-15 17:47:02.922] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/process.py (156) - [INFO] :
回复[person_1042075652]文字消息:[bot]err:invalid syntax (<string>, line 1)
[2024-01-15 17:47:09.582] /usr/local/lib/python3.11/dist-packages/nakuru/application.py (95) - [INFO] :
Event: handling a event: FriendMessage
[2024-01-15 17:47:09.584] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py (11) - [INFO] :
[person_1042075652]发起指令:!~
[2024-01-15 17:47:09.585] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/process.py (156) - [INFO] :
回复[person_1042075652]文字消息:[bot]err:指令不存在：cfg
[2024-01-15 17:47:16.021] /usr/local/lib/python3.11/dist-packages/nakuru/application.py (95) - [INFO] :
Event: handling a event: FriendMessage
[2024-01-15 17:47:16.023] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/command.py (11) - [INFO] :
[person_1042075652]发起指令:!cfg
[2024-01-15 17:47:16.023] /home/lighthouse/QChatGPT-2.6.7/pkg/qqbot/process.py (156) - [INFO] :
回复[person_1042075652]文字消息:[bot]err:请输入!cmd cfg查看使用方法

### 启用的插件

#1 Switcher 
快捷切换使用的模型
v0.2.0
作者: RockChinQ

#2 Webwlkr 
基于GPT的函数调用能力，为QChatGPT提供联网功能
v0.1.1
作者: RockChinQ

#3 chat_voice 
让机器人用语音输出
v1.4
作者: oliverkirk-sudo

**Comment by Vlfx1** [comment]
好的，可以使用了
