### ISSUE TITLE
[Bug]: OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 8080, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 8080)

### ISSUE THREAD

**Issue by TedSIWEILIU** [RockChinQ/QChatGPT#668]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

MacOS,中国，使用梯子（放在了config.py --http_proxy）

### Python环境

python 3.10

### QChatGPT版本

?

### 异常情况

无法运行main.py文件，一直显示OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 8080, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 8080)。但是我使用sudo lsof -i :8080检查了，8080没有被其他进程占用

### 日志信息

./anaconda3/envs/qqchat/bin/python ./Downloads/QChatGPT-master/main.py
[2024-01-19 15:21:37.045] manager.py (242) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2024-01-19 15:21:37.046] settings.py (98) - [INFO] : 已全局启用内容函数。
[2024-01-19 15:21:37.046] host.py (163) - [INFO] : 以下插件已初始化: 
2024-01-19 15:21:37 - ERROR    Multiple exceptions: [Errno 61] Connect call failed ('::1', 8080, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 8080)
[2024-01-19 15:21:37.049] base.py (43) - [ERROR] : Multiple exceptions: [Errno 61] Connect call failed ('::1', 8080, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 8080)
Traceback (most recent call last):
  File "./Downloads/QChatGPT-master/main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "./Downloads/QChatGPT-master/pkg/qqbot/sources/yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "./anaconda3/envs/qqchat/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "./anaconda3/envs/qqchat/lib/python3.10/asyncio/base_events.py", line 1084, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 8080, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 8080)
[2024-01-19 15:21:37.054] main.py (324) - [ERROR] : 捕捉到未知异常:Multiple exceptions: [Errno 61] Connect call failed ('::1', 8080, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 8080), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "./anaconda3/envs/qqchat/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "./anaconda3/envs/qqchat/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "./Downloads/QChatGPT-master/main.py", line 327, in run_bot_wrapper
    raise e
  File "./Downloads/QChatGPT-master/main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "./Downloads/QChatGPT-master/pkg/qqbot/sources/yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "./anaconda3/envs/qqchat/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "./anaconda3/envs/qqchat/lib/python3.10/site-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "./anaconda3/envs/qqchat/lib/python3.10/asyncio/base_events.py", line 1084, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 8080, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 8080)

**Comment by RockChinQ** [comment]
#68
