### ISSUE TITLE
运行主程序报错base.py (43) - [ERROR]

### ISSUE THREAD

**Issue by Beyond121** [RockChinQ/QChatGPT#67]
**运行环境**
- 部署方式：
    安装器
- 系统环境：
    windows10 企业版 LTSC

**描述漏洞**  
mirai正常运行，启动主程序时报错

**完整报错信息**  

D:\qcg>cd QChatGPT

D:\qcg\QChatGPT>..\python\python.exe main.py
Database initialized.
[2022-12-30 03:36:14.669] keymgr.py (153) - [INFO] : load fee:{'bff09b413bb21feda6539a277a449847': 0, 'ed7a18f7fd87f0437a9ecb2555fe02fa': 0}
[2022-12-30 03:36:14.672] keymgr.py (54) - [INFO] : 使用api-key:default
[2022-12-30 03:36:14.690] main.py (74) - [INFO] : 程序启动完成
2022-12-30 03:36:14 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2022-12-30 03:36:14.690] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2022-12-30 03:36:24 - ERROR
[2022-12-30 03:36:24.694] base.py (43) - [ERROR] :
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "D:\qcg\python\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "D:\qcg\python\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\qcg\python\lib\site-packages\websockets\legacy\client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio\tasks.py", line 456, in wait_for
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\qcg\python\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "D:\qcg\python\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "D:\qcg\python\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "D:\qcg\python\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "D:\qcg\python\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "D:\qcg\python\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "D:\qcg\python\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "D:\qcg\python\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "asyncio\tasks.py", line 458, in wait_for
asyncio.exceptions.TimeoutError

**Comment by Beyond121** [comment]
mirai的setting.yml

adapters: 
  - http
debug: false
enableVerify: true
verifyKey: INITKEYkSqxqw8E
singleMode: false
cacheSize: 4096
persistenceFactory: 'built-in'
adapterSettings: {
  http:
    host: localhost
    port: 8080
    cors: ["*"]
}

qcg的cofig.py里的部分

mirai_http_api_config = {
    "adapter": "WebSocketAdapter",
    "host": "localhost",
    "port": 8080,
    "verifyKey": "INITKEYkSqxqw8E",
    "qq": 15******07
}

是在同一设备上运行的

**Comment by Beyond121** [comment]
把mirai的配置改成

adapters: 
  - http
  - ws
debug: false
enableVerify: true
verifyKey: INITKEYkSqxqw8E
singleMode: false
cacheSize: 4096
persistenceFactory: 'built-in'
adapterSettings: {}

就好了，虽然我也不知道原因（）
但是好了就行（

**Comment by 123lzz** [comment]
我也是。。但是照你的mirai配置改完还是报错

**Comment by RockChinQ** [comment]
> 我也是。。但是照你的mirai配置改完还是报错

查看 #22
