### ISSUE TITLE
[BUG] 运行bot时报错：ERROR    Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)

### ISSUE THREAD

**Issue by hmsjy2017** [RockChinQ/QChatGPT#68]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    Ubuntu 20 x64

**描述漏洞**  
运行bot报错

**完整报错信息**  
![2987C5B9-76F8-4C7F-A3D6-E68446A28E49](https://user-images.githubusercontent.com/42692274/210034610-3215ee1a-04a9-4712-848f-d1c82bc941b6.jpeg)

**Comment by RockChinQ** [comment]
把运行之后的所有输出信息粘贴过来，要文字形式的，不要放图

**Comment by hmsjy2017** [comment]
```bash
root@iecho:~/bot# ./run-bot.sh 
Database initialized.
[2022-12-30 11:11:35.037] keymgr.py (153) - [INFO] : load fee:{'6eb34730181d380f0a18cca95429dc52': 0, 'ccf1698c99e9234d3699528bcea2ee93': 0}
[2022-12-30 11:11:35.045] keymgr.py (54) - [INFO] : 使用api-key:default
[2022-12-30 11:11:35.048] main.py (74) - [INFO] : 程序启动完成
2022-12-30 11:11:35 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2022-12-30 11:11:35.050] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2022-12-30 11:11:35 - ERROR    Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
[2022-12-30 11:11:35.057] base.py (43) - [ERROR] : Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "/root/bot/python/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/bot/python/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 274, in run
    asyncio.run(self._run())
  File "/root/bot/python/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/bot/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 238, in _run
    await self.startup()
  File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "/root/bot/python/lib/python3.10/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/root/bot/python/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/root/bot/python/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/root/bot/python/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/root/bot/python/lib/python3.10/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/root/bot/python/lib/python3.10/asyncio/base_events.py", line 1078, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
nnect call failed ('127.0.0.1', 8080)
[2022-12-30 11:11:35.057] base.py (43) - [ERROR] : Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
Exception in thread Thread-1 (run):
Traceback (most recent call last):
File "/root/bot/python/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  self.run()
File "/root/bot/python/lib/python3.10/threading.py", line 953, in run
  self._target(*self._args, **self._kwargs)
File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 197, in run
  MiraiRunner(self).run(host, port, asgi_server, **kwargs)
File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 274, in run
  asyncio.run(self._run())
File "/root/bot/python/lib/python3.10/asyncio/runners.py", line 44, in run
  return loop.run_until_complete(main)
File "/root/bot/python/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
  return future.result()
File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 238, in _run
  await self.startup()
File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 226, in startup
  await asyncio.gather(*coros)
File "/root/bot/python/lib/python3.10/site-packages/mirai/bot.py", line 135, in startup
  await self._adapter.login(self.qq)
File "/root/bot/python/lib/python3.10/site-packages/mirai/adapters/base.py", line 35, in wrapped
  return await func(self, *args, **kwargs)
File "/root/bot/python/lib/python3.10/site-packages/mirai/adapters/websocket.py", line 187, in login
  self.connection = await connect(self.host_name, extra_headers=headers)
  File "/root/bot/python/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__  return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
File "/root/bot/python/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
  return fut.result()
  File "/root/bot/python/lib/python3.10/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
  _transport, _protocol = await self._create_connection()
File "/root/bot/python/lib/python3.10/asyncio/base_events.py", line 1078, in create_connection
raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 8080, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8080)
```

**Comment by RockChinQ** [comment]
检查mirai是否启动并且正确配置了mirai-api-http，同时检查防火墙未阻拦本地8080端口

**Comment by hmsjy2017** [comment]
已解决，是 `mirai-api-http`的问题

**Comment by ImuziSagirl** [comment]
我也遇到了同样的问题，在今天下午的时候还一切正常，查看issue解决方案，检查发现自己的8080端口正常打开，后来修改了两处的端口为2333，打开2333端口，还是同样的错误

**Comment by ImuziSagirl** [comment]
[root@VM-12-3-centos QChatGPT-Docker-Installer]# docker-compose run setup
Database initialized.
[2023-03-04 14:14:21.666] keymgr.py (52) - [INFO] : 使用api-key:default
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting dulwich
  Downloading dulwich-0.21.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (505 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.9/505.9 kB 1.2 MB/s eta 0:00:00
Requirement already satisfied: urllib3>=1.25 in /usr/local/lib/python3.9/site-packages (from dulwich) (1.26.14)
Installing collected packages: dulwich
Successfully installed dulwich-0.21.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[2023-03-04 14:14:25.676] manager.py (28) - [INFO] : 文字总使用量：187280
[2023-03-04 14:14:25.677] manager.py (78) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-03-04 14:14:25.677] host.py (88) - [INFO] : 加载插件
[2023-03-04 14:14:25.677] host.py (105) - [INFO] : 初始化插件
2023-03-04 14:14:25 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
WARNING: 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-03-04 14:14:25.678] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
2023-03-04 14:14:25 - ERROR    Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333)
ERROR: Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333)
[2023-03-04 14:14:25.680] base.py (43) - [ERROR] : Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333)
ERROR: 捕捉到未知异常:Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
[2023-03-04 14:14:25.682] main.py (221) - [ERROR] : 捕捉到未知异常:Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/bot/main.py", line 224, in run_bot_wrapper
    raise e
  File "/bot/main.py", line 186, in run_bot_wrapper
    qqbot.bot.run()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run
    asyncio.run(self._run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run
    await self.startup()
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1073, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333)

**Comment by RockChinQ** [comment]
> [root@VM-12-3-centos QChatGPT-Docker-Installer]# docker-compose run setup Database initialized. [2023-03-04 14:14:21.666] keymgr.py (52) - [INFO] : 使用api-key:default WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip. Please see [pypa/pip#5599](https://github.com/pypa/pip/issues/5599) for advice on fixing the underlying issue. To avoid this problem you can invoke Python with '-m pip' instead of running pip directly. Collecting dulwich Downloading dulwich-0.21.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (505 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.9/505.9 kB 1.2 MB/s eta 0:00:00 Requirement already satisfied: urllib3>=1.25 in /usr/local/lib/python3.9/site-packages (from dulwich) (1.26.14) Installing collected packages: dulwich Successfully installed dulwich-0.21.3 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv [2023-03-04 14:14:25.676] manager.py (28) - [INFO] : 文字总使用量：187280 [2023-03-04 14:14:25.677] manager.py (78) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829] [2023-03-04 14:14:25.677] host.py (88) - [INFO] : 加载插件 [2023-03-04 14:14:25.677] host.py (105) - [INFO] : 初始化插件 2023-03-04 14:14:25 - WARNING 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn WARNING: 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn [2023-03-04 14:14:25.678] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn 2023-03-04 14:14:25 - ERROR Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333) ERROR: Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333) [2023-03-04 14:14:25.680] base.py (43) - [ERROR] : Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333) ERROR: 捕捉到未知异常:Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue [2023-03-04 14:14:25.682] main.py (221) - [ERROR] : 捕捉到未知异常:Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue Exception in thread Thread-3: Traceback (most recent call last): File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner self.run() File "/usr/local/lib/python3.9/threading.py", line 917, in run self._target(*self._args, **self._kwargs) File "/bot/main.py", line 224, in run_bot_wrapper raise e File "/bot/main.py", line 186, in run_bot_wrapper qqbot.bot.run() File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run MiraiRunner(self).run(host, port, asgi_server, **kwargs) File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run asyncio.run(self._run()) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run await self.startup() File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup await asyncio.gather(*coros) File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup await self._adapter.login(self.qq) File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped return await func(self, *args, **kwargs) File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login self.connection = await connect(self.host_name, extra_headers=headers) File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in **await_impl_timeout** return await asyncio.wait_for(self.**await_impl**(), self.open_timeout) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for return fut.result() File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 663, in **await_impl** _transport, _protocol = await self._create_connection() File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1073, in create_connection raise OSError('Multiple exceptions: {}'.format( OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333)

按照文档所述的手动部署步骤重新部署mirai及mirai-api-http

**Comment by ImuziSagirl** [comment]
> > [root@VM-12-3-centos QChatGPT-Docker-Installer]# docker-compose run setup Database initialized. [2023-03-04 14:14:21.666] keymgr.py (52) - [INFO] : 使用api-key:default WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip. Please see [pypa/pip#5599](https://github.com/pypa/pip/issues/5599) for advice on fixing the underlying issue. To avoid this problem you can invoke Python with '-m pip' instead of running pip directly. Collecting dulwich Downloading dulwich-0.21.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (505 kB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.9/505.9 kB 1.2 MB/s eta 0:00:00 Requirement already satisfied: urllib3>=1.25 in /usr/local/lib/python3.9/site-packages (from dulwich) (1.26.14) Installing collected packages: dulwich Successfully installed dulwich-0.21.3 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv [2023-03-04 14:14:25.676] manager.py (28) - [INFO] : 文字总使用量：187280 [2023-03-04 14:14:25.677] manager.py (78) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829] [2023-03-04 14:14:25.677] host.py (88) - [INFO] : 加载插件 [2023-03-04 14:14:25.677] host.py (105) - [INFO] : 初始化插件 2023-03-04 14:14:25 - WARNING 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn WARNING: 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn [2023-03-04 14:14:25.678] bot.py (262) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。 仅 HTTP 轮询与正向 WebSocket 可用。 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。 在命令行键入： pip install uvicorn 或者 pip install hypercorn 2023-03-04 14:14:25 - ERROR Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333) ERROR: Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333) [2023-03-04 14:14:25.680] base.py (43) - [ERROR] : Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333) ERROR: 捕捉到未知异常:Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue [2023-03-04 14:14:25.682] main.py (221) - [ERROR] : 捕捉到未知异常:Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333), 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue Exception in thread Thread-3: Traceback (most recent call last): File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner self.run() File "/usr/local/lib/python3.9/threading.py", line 917, in run self._target(*self._args, **self._kwargs) File "/bot/main.py", line 224, in run_bot_wrapper raise e File "/bot/main.py", line 186, in run_bot_wrapper qqbot.bot.run() File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 199, in run MiraiRunner(self).run(host, port, asgi_server, **kwargs) File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 276, in run asyncio.run(self._run()) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run return loop.run_until_complete(main) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete return future.result() File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 240, in _run await self.startup() File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 228, in startup await asyncio.gather(*coros) File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 137, in startup await self._adapter.login(self.qq) File "/usr/local/lib/python3.9/site-packages/mirai/adapters/base.py", line 35, in wrapped return await func(self, *args, **kwargs) File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 187, in login self.connection = await connect(self.host_name, extra_headers=headers) File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 659, in **await_impl_timeout** return await asyncio.wait_for(self.**await_impl**(), self.open_timeout) File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for return fut.result() File "/usr/local/lib/python3.9/site-packages/websockets/legacy/client.py", line 663, in **await_impl** _transport, _protocol = await self._create_connection() File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1073, in create_connection raise OSError('Multiple exceptions: {}'.format( OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 2333, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 2333)
> 
> 按照文档所述的手动部署步骤重新部署mirai及mirai-api-http

手动部署又提示version `GLIBC_2.25' not found ，linux小白，去网上找了下解决方案，去试了下没有没能成功，除此之外没有其他解决方法了吗。。奇怪的是昨天下午第一次部署的时候是成功的，后来就这样

**Comment by RockChinQ** [comment]
> version `GLIBC_2.25' not found

或者去试试文档中提到的docker方式部署

**Comment by ImuziSagirl** [comment]
> 

用了docker方式部署就会报上述的错误
