### ISSUE TITLE
[Bug]: 不论是反代还是正向代理都出错

### ISSUE THREAD

**Issue by youyi0218** [RockChinQ/QChatGPT#682]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

win10专业版 位于大陆

### Python环境

3.10

### QChatGPT版本

2.6.10

### 异常情况

在config.py中，无论是用反向代理（oneapi，腾讯云函数）还是正向代理（clash）都报错SyntaxError: invalid syntax

### oneapi
D:\Program\QChatGPT>python main.py
Traceback (most recent call last):
  File "D:\Program\QChatGPT\main.py", line 57, in <module>
    from pkg.utils.log import init_runtime_log_file, reset_logging
  File "D:\Program\QChatGPT\pkg\utils\log.py", line 6, in <module>
    from . import context
  File "D:\Program\QChatGPT\pkg\utils\context.py", line 8, in <module>
    from ..qqbot import manager as qqbot_mgr
  File "D:\Program\QChatGPT\pkg\qqbot\manager.py", line 12, in <module>
    from ..qqbot import process as processor
  File "D:\Program\QChatGPT\pkg\qqbot\process.py", line 16, in <module>
    from ..qqbot import command, message
  File "D:\Program\QChatGPT\pkg\qqbot\command.py", line 4, in <module>
    from ..qqbot.cmds import aamgr as cmdmgr
  File "D:\Program\QChatGPT\pkg\qqbot\cmds\aamgr.py", line 7, in <module>
    import tips as tips_custom
  File "D:\Program\QChatGPT\tips.py", line 1, in <module>
    import config
  File "D:\Program\QChatGPT\config.py", line 73
    "reverse_proxy": https://one.caifree.com/v1
                          ^
SyntaxError: invalid syntax
### clash
D:\Program\QChatGPT>python main.py
Traceback (most recent call last):
  File "D:\Program\QChatGPT\main.py", line 57, in <module>
    from pkg.utils.log import init_runtime_log_file, reset_logging
  File "D:\Program\QChatGPT\pkg\utils\log.py", line 6, in <module>
    from . import context
  File "D:\Program\QChatGPT\pkg\utils\context.py", line 8, in <module>
    from ..qqbot import manager as qqbot_mgr
  File "D:\Program\QChatGPT\pkg\qqbot\manager.py", line 12, in <module>
    from ..qqbot import process as processor
  File "D:\Program\QChatGPT\pkg\qqbot\process.py", line 16, in <module>
    from ..qqbot import command, message
  File "D:\Program\QChatGPT\pkg\qqbot\command.py", line 4, in <module>
    from ..qqbot.cmds import aamgr as cmdmgr
  File "D:\Program\QChatGPT\pkg\qqbot\cmds\aamgr.py", line 7, in <module>
    import tips as tips_custom
  File "D:\Program\QChatGPT\tips.py", line 1, in <module>
    import config
  File "D:\Program\QChatGPT\config.py", line 72
    "http_proxy": http://127.0.0.1:7890,
                      ^
SyntaxError: invalid syntax
腾讯云函数
D:\Program\QChatGPT>python main.py
Traceback (most recent call last):
  File "D:\Program\QChatGPT\main.py", line 57, in <module>
    from pkg.utils.log import init_runtime_log_file, reset_logging
  File "D:\Program\QChatGPT\pkg\utils\log.py", line 6, in <module>
    from . import context
  File "D:\Program\QChatGPT\pkg\utils\context.py", line 8, in <module>
    from ..qqbot import manager as qqbot_mgr
  File "D:\Program\QChatGPT\pkg\qqbot\manager.py", line 12, in <module>
    from ..qqbot import process as processor
  File "D:\Program\QChatGPT\pkg\qqbot\process.py", line 16, in <module>
    from ..qqbot import command, message
  File "D:\Program\QChatGPT\pkg\qqbot\command.py", line 4, in <module>
    from ..qqbot.cmds import aamgr as cmdmgr
  File "D:\Program\QChatGPT\pkg\qqbot\cmds\aamgr.py", line 7, in <module>
    import tips as tips_custom
  File "D:\Program\QChatGPT\tips.py", line 1, in <module>
    import config
  File "D:\Program\QChatGPT\config.py", line 73
    "reverse_proxy": https://service-hgbpvnnu-1310799201.hk.tencentapigw.cn/v1
                                                        ^
SyntaxError: invalid decimal literal

### 启用的插件

无插件

**Comment by RockChinQ** [comment]
地址是字符串，需要用英文双引号包裹

**Comment by youyi0218** [comment]
> 地址是字符串，需要用英文双引号包裹

正向和反向都需要双引号吗

**Comment by RockChinQ** [comment]
这跟你什么代理没关系，这是Python语法

**Comment by youyi0218** [comment]
> 这跟你什么代理没关系，这是Python语法

懂了，加上双引号就跑起来了，谢谢大佬orz
