### ISSUE TITLE
[Bug]: 捕捉到未知异常 

### ISSUE THREAD

**Issue by Tudouuuuuu** [RockChinQ/QChatGPT#688]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

windows sever 2022

### Python环境

python 3.10.9

### QChatGPT版本

2.6.10

### 异常情况

运行main.py 报错

### 日志信息
```
[2024-02-16 00:22:37.495] manager.py (242) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2024-02-16 00:22:37.511] settings.py (98) - [INFO] : 已全局启用内容函数。
[2024-02-16 00:22:37.511] host.py (163) - [INFO] : 以下插件已初始化:
[2024-02-16 00:22:39.520] main.py (348) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
2024-02-16 00:22:39 - ERROR    Unsupported extension: name = frame-log, params = []
[2024-02-16 00:22:39.558] base.py (43) - [ERROR] : Unsupported extension: name = frame-log, params = []
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QchatGPT\QChatGPT-2.6.10\QChatGPT-2.6.10\main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "C:\Users\Administrator\Desktop\QchatGPT\QChatGPT-2.6.10\QChatGPT-2.6.10\pkg\qqbot\sources\yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\bot.py", line 240, in _run
    await self.startup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 329, in handshake
    self.extensions = self.process_extensions(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 218, in process_extensions
    raise NegotiationError(
websockets.exceptions.NegotiationError: Unsupported extension: name = frame-log, params = []
[2024-02-16 00:22:39.558] main.py (324) - [ERROR] : 捕捉到未知异常:Unsupported extension: name = frame-log, params = [], 请前往 https://github.com/RockChinQ/QChatGPT/issues 查找或提issue
Exception in thread Thread-2 (run_bot_wrapper):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\QchatGPT\QChatGPT-2.6.10\QChatGPT-2.6.10\main.py", line 327, in run_bot_wrapper
    raise e
  File "C:\Users\Administrator\Desktop\QchatGPT\QChatGPT-2.6.10\QChatGPT-2.6.10\main.py", line 287, in run_bot_wrapper
    qqbot.adapter.run_sync()
  File "C:\Users\Administrator\Desktop\QchatGPT\QChatGPT-2.6.10\QChatGPT-2.6.10\pkg\qqbot\sources\yirimirai.py", line 120, in run_sync
    loop.run_until_complete(MiraiRunner(self.bot)._run())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\bot.py", line 240, in _run
    await self.startup()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\bot.py", line 228, in startup
    await asyncio.gather(*coros)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\bot.py", line 137, in startup
    await self._adapter.login(self.qq)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 654, in __await_impl__
    await protocol.handshake(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 329, in handshake
    self.extensions = self.process_extensions(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\websockets\legacy\client.py", line 218, in process_extensions
    raise NegotiationError(
websockets.exceptions.NegotiationError: Unsupported extension: name = frame-log, params = []
```

**Comment by mettenchen** [comment]
看一下有没有装Microsoft Virtual C++

**Comment by Tudouuuuuu** [comment]
装了

**Comment by Tudouuuuuu** [comment]
aiofiles==23.2.1
aiohttp==3.9.3
aiosignal==1.3.1
anyio==4.2.0
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
CallingGPT==0.0.1.0
certifi==2024.2.2
charset-normalizer==3.3.2
colorama==0.4.6
colorlog==6.6.0
distro==1.9.0
dulwich==0.21.7
exceptiongroup==1.2.0
frozenlist==1.4.1
func-timeout==4.3.5
h11==0.14.0
httpcore==1.0.3
httpx==0.26.0
idna==3.6
Logbook==1.7.0.post0
multidict==6.0.5
nakuru-project-idk==0.0.2.1
openai==1.12.0
pillow==10.2.0
pydantic==1.10.14
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
sniffio==1.3.0
starlette==0.37.1
tiktoken==0.6.0
tqdm==4.66.2
typing_extensions==4.9.0
urllib3==2.2.0
websockets==12.0
yarl==1.9.4
yiri-mirai-rc==0.2.7.3

**Comment by RockChinQ** [comment]
试一下3.x的新版本
