### ISSUE TITLE
[Bug]: 安装时候报错: TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType'

### ISSUE THREAD

**Issue by yxn4065** [RockChinQ/QChatGPT#692]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

Centos7 中国大陆 阿里云服务器

### Python环境

python 3.9.13

### QChatGPT版本

无

### 异常情况

安装时候运行python3 main.py报错:unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType',经过检查是typing的原因

### 日志信息

服务器报错:
Traceback (most recent call last):
  File "/root/QChatGPT/main.py", line 17, in <module>
    from pkg.core import boot
  File "/root/QChatGPT/pkg/core/boot.py", line 11, in <module>
    from . import app
  File "/root/QChatGPT/pkg/core/app.py", line 9, in <module>
    from ..platform import manager as im_mgr
  File "/root/QChatGPT/pkg/platform/manager.py", line 15, in <module>
    from ..plugin import events
  File "/root/QChatGPT/pkg/plugin/events.py", line 12, in <module>
    class BaseEventModel(pydantic.BaseModel):
  File "pydantic/main.py", line 178, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 400, in pydantic.typing.resolve_annotations
    
  File "/usr/local/python3/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/python3/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType'

个人pc报错:
Traceback (most recent call last):
  File "C:\Users\yxn\Downloads\QChatGPT-master\main.py", line 17, in <module>
    from pkg.core import boot
  File "C:\Users\yxn\Downloads\QChatGPT-master\pkg\core\boot.py", line 11, in <module>
    from . import app
  File "C:\Users\yxn\Downloads\QChatGPT-master\pkg\core\app.py", line 9, in <module>
    from ..platform import manager as im_mgr
  File "C:\Users\yxn\Downloads\QChatGPT-master\pkg\platform\manager.py", line 15, in <module>
    from ..plugin import events
  File "C:\Users\yxn\Downloads\QChatGPT-master\pkg\plugin\events.py", line 12, in <module>
    class BaseEventModel(pydantic.BaseModel):
  File "pydantic\main.py", line 178, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\typing.py", line 400, in pydantic.typing.resolve_annotations
  File "D:\Python39\lib\typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "D:\Python39\lib\typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'ModelMetaclass' and 'NoneType'

### 启用的插件

无

**Comment by RockChinQ** [comment]
执行 `pip freeze` 发上来看看你环境都有什么包

**Comment by yxn4065** [comment]
> pip freeze

3==0.0.0
aioconsole==0.7.0
aiocqhttp==1.4.4
aiofiles==23.2.1
aiohttp==3.9.3
aiosignal==1.3.1
anyio==4.3.0
APScheduler==3.10.4
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.2.0
blinker==1.7.0
CallingGPT==0.0.1.0
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
colorlog==6.6.0
distro==1.9.0
exceptiongroup==1.2.0
Flask==3.0.2
frozenlist==1.4.1
h11==0.14.0
h2==4.1.0
hpack==4.0.0
httpcore==1.0.3
httpx==0.26.0
Hypercorn==0.16.0
hyperframe==6.0.1
idna==3.6
importlib-metadata==7.0.1
itsdangerous==2.1.2
Jinja2==3.1.3
Logbook==1.7.0.post0
MarkupSafe==2.1.5
multidict==6.0.5
nakuru-project-idk==0.0.2.1
openai==1.12.0
pillow==10.2.0
priority==2.0.0
pydantic==1.10.14
pytz==2024.1
PyYAML==6.0.1
qq-botpy==1.2.0
Quart==0.19.4
regex==2023.12.25
requests==2.31.0
six==1.16.0
sniffio==1.3.0
starlette==0.37.1
taskgroup==0.0.0a4
tiktoken==0.6.0
tomli==2.0.1
tqdm==4.66.2
typing_extensions==4.9.0
tzdata==2024.1
tzlocal==5.2
urllib3==2.2.1
websockets==12.0
Werkzeug==3.0.1
wsproto==1.2.0
yarl==1.9.4
yiri-mirai-rc==0.2.7.3
zipp==3.17.0

**Comment by RockChinQ** [comment]
3.0.1 修了
