### ISSUE TITLE
[Bug]: aiocqhttp的兼容性问题

### ISSUE THREAD

**Issue by hhhhhge** [RockChinQ/QChatGPT#702]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

win10

### Python环境

py3.11

### QChatGPT版本

v3.0.1.3

### 异常情况

每次@都会遇到，使用的是liteloaderqqnt的liteloaderqqnt-onebotapi插件 https://github.com/linyuchen/LiteLoaderQQNT-OneBotApi 是什么情况

### 日志信息

[2024-02-25 20:55:41.875] C:\Users\hhhge\Desktop\QChatGPT\pkg\platform\manager.py (108) - [INFO] :
    初始化平台适配器 0: aiocqhttp
[2024-02-25 20:55:41 +0800] [9864] [INFO] Running on http://0.0.0.0:6700 (CTRL + C to quit)
[2024-02-25 20:55:42 +0800] [9864] [INFO] 127.0.0.1:64603 GET /ws 1.1 101 - 3963
Traceback (most recent call last):
  File "C:\Users\hhhge\Desktop\QChatGPT\pkg\platform\sources\aiocqhttp.py", line 255, in on_message
    return await callback(self.event_converter.target2yiri(event), self)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhhge\Desktop\QChatGPT\pkg\platform\sources\aiocqhttp.py", line 173, in target2yiri
    special_title=event.sender["title"],
                  ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'title'
Traceback (most recent call last):
  File "C:\Users\hhhge\Desktop\QChatGPT\pkg\platform\sources\aiocqhttp.py", line 255, in on_message
    return await callback(self.event_converter.target2yiri(event), self)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhhge\Desktop\QChatGPT\pkg\platform\sources\aiocqhttp.py", line 173, in target2yiri
    special_title=event.sender["title"],
                  ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'title'
Traceback (most recent call last):
  File "C:\Users\hhhge\Desktop\QChatGPT\pkg\platform\sources\aiocqhttp.py", line 255, in on_message
    return await callback(self.event_converter.target2yiri(event), self)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hhhge\Desktop\QChatGPT\pkg\platform\sources\aiocqhttp.py", line 173, in target2yiri
    special_title=event.sender["title"],
                  ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'title'


### 启用的插件

无

**Comment by hhhhhge** [comment]
![屏幕截图(1)](https://github.com/RockChinQ/QChatGPT/assets/102860110/c792ad5d-b03f-401b-8dc0-c644c85d8aaa)

**Comment by hhhhhge** [comment]
![捕获](https://github.com/RockChinQ/QChatGPT/assets/102860110/674227d1-ee8a-426c-86be-1a56208cf73a)

**Comment by RockChinQ** [comment]
最近没有太多时间测试，欢迎修改后提pr

**Comment by RockChinQ** [comment]
这个title这一行可以做一个存在性检查，以`""`作为缺省值

**Comment by hhhhhge** [comment]
行我试试

**Comment by hhhhhge** [comment]
为什么会报这个错呢？

**Comment by hhhhhge** [comment]
title干什么用的？

**Comment by hhhhhge** [comment]
能不能提供代码修改，不知道从哪里改比较合适

**Comment by hhhhhge** [comment]
或者作者你改好我更新

**Comment by RockChinQ** [comment]
就你截图那里，检查一下有没有title这个key，实在不太清楚的话等我有空测试完再更新吧。

**Comment by hhhhhge** [comment]
其实只是我看了其他几个代码都有这个问题，再想他获取的时候就可以把他检测一下，但是我找不到哪来的

**Comment by hhhhhge** [comment]
什么时候能修好啊大佬

**Comment by RockChinQ** [comment]
已修复
