### ISSUE TITLE
[Bug]: 模型请求失败

### ISSUE THREAD

**Issue by shecong** [RockChinQ/QChatGPT#704]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

windowsserver

### Python环境

python9.x

### QChatGPT版本

最新版本

### 异常情况

发送信息后，在qqchatgpt这个超时，然后报错

### 日志信息

[2024-02-27 10:12:58.437] C:\sc\qqchatgpt\QChatGPT-master\pkg\pipeline\process\handlers\chat.py (92) - [ERROR] :
    对话(0)请求失败: 模型请求失败: 请求错误: Connection error.
[2024-02-27 10:12:58.437] C:\sc\qqchatgpt\QChatGPT-master\pkg\core\controller.py (152) - [ERROR] :
    处理请求时出错 query_id=0: Unknown message type: 请求失败<class 'str'>

### 启用的插件

[2024-02-27 10:16:22.987] C:\sc\qqchatgpt\QChatGPT-master\pkg\platform\manager.py (108) - [INFO] :
    初始化平台适配器 0: nakuru
[2024-02-27 10:16:23.000] C:\sc\qqchatgpt\QChatGPT-master\pkg\platform\sources\nakuru.py (328) - [INFO] :
    运行 Nakuru 适配器

**Comment by RockChinQ** [comment]
境内主机无法直接访问 OpenAI 接口。看文档，到 `data/config/provider.json` 加一下反向代理，或者去 `data/config/system.json` 加一下正向代理。

**Comment by shecong** [comment]
代理地址需要怎么填写
自己有梯子

**Comment by shecong** [comment]
添加文档提示的正向代理后
Traceback (most recent call last):
  File "C:\sc\qqchatgpt\QChatGPT-master\main.py", line 18, in <module>
    asyncio.run(boot.main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\sc\qqchatgpt\QChatGPT-master\pkg\core\boot.py", line 148, in main
    app_inst = await make_app()
  File "C:\sc\qqchatgpt\QChatGPT-master\pkg\core\boot.py", line 61, in make_app
    system_cfg = await config.load_json_config("data/config/system.json", "templates/system.json")
  File "C:\sc\qqchatgpt\QChatGPT-master\pkg\config\manager.py", line 51, in load_json_config
    await cfg_mgr.load_config()
  File "C:\sc\qqchatgpt\QChatGPT-master\pkg\config\manager.py", line 24, in load_config
    self.data = await self.file.load()
  File "C:\sc\qqchatgpt\QChatGPT-master\pkg\config\impls\json.py", line 33, in load
    cfg = json.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 17 (char 69)

**Comment by shecong** [comment]
ok，已经成功了，感谢大佬
