### ISSUE TITLE
[Bug]: 模型改成gpt-3.5-turbo-0125后报错

### ISSUE THREAD

**Issue by Phi-2X** [RockChinQ/QChatGPT#721]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

Windows11 中国大陆

### Python环境

3.10.9

### QChatGPT版本

v3.0.2

### 异常情况

似乎不支持openai最新的gpt-3.5-turbo-0125模型。

### 日志信息

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

[2024-03-12 22:21:08.705] E:\QChatGPT\pkg\platform\manager.py (108) - [INFO] :
    初始化平台适配器 0: aiocqhttp
[2024-03-12 22:21:08.845] E:\QChatGPT\pkg\plugin\loaders\legacy.py (147) - [ERROR] :
    加载插件模块 chat_voice.main 时发生错误
Traceback (most recent call last):
  File "E:\QChatGPT\pkg\plugin\loaders\legacy.py", line 141, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\QChatGPT\plugins\chat_voice\main.py", line 6, in <module>
    from plugins.chat_voice.config.mapper import voice_type_mapping, method_mapping
  File "E:\QChatGPT\plugins\chat_voice\config\mapper.py", line 3, in <module>
    from plugins.chat_voice.config.voice_config import SoVitsConfig
ModuleNotFoundError: No module named 'plugins.chat_voice.config.voice_config'
[2024-03-12 22:21:09.701] E:\QChatGPT\pkg\plugin\loaders\legacy.py (147) - [ERROR] :
    加载插件模块 revLibs.main 时发生错误
Traceback (most recent call last):
  File "E:\QChatGPT\pkg\plugin\loaders\legacy.py", line 141, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\QChatGPT\plugins\revLibs\main.py", line 11, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "E:\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 9, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai'
[2024-03-12 22:21:09.703] E:\QChatGPT\pkg\plugin\loaders\legacy.py (147) - [ERROR] :
    加载插件模块 revLibs.pkg.process.impls.gpt4free 时发生错误
Traceback (most recent call last):
  File "E:\QChatGPT\pkg\plugin\loaders\legacy.py", line 141, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\QChatGPT\plugins\revLibs\pkg\process\impls\gpt4free.py", line 6, in <module>
    import g4f
ModuleNotFoundError: No module named 'g4f'
[2024-03-12 22:21:09.703] E:\QChatGPT\pkg\plugin\loaders\legacy.py (147) - [ERROR] :
    加载插件模块 revLibs.pkg.process.proccmd 时发生错误
Traceback (most recent call last):
  File "E:\QChatGPT\pkg\plugin\loaders\legacy.py", line 141, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\QChatGPT\plugins\revLibs\pkg\process\proccmd.py", line 1, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "E:\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 9, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai'
[2024-03-12 22:21:09.716] E:\QChatGPT\pkg\plugin\loaders\legacy.py (147) - [ERROR] :
    加载插件模块 revLibs.pkg.process.procmsg 时发生错误
Traceback (most recent call last):
  File "E:\QChatGPT\pkg\plugin\loaders\legacy.py", line 141, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\QChatGPT\plugins\revLibs\pkg\process\procmsg.py", line 2, in <module>
    import plugins.revLibs.pkg.process.revss as revss
  File "E:\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 9, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai'
[2024-03-12 22:21:09.720] E:\QChatGPT\pkg\plugin\loaders\legacy.py (147) - [ERROR] :
    加载插件模块 revLibs.pkg.process.revss 时发生错误
Traceback (most recent call last):
  File "E:\QChatGPT\pkg\plugin\loaders\legacy.py", line 141, in _walk_plugin_path
    importlib.import_module(module.__name__ + "." + item.name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\QChatGPT\plugins\revLibs\pkg\process\revss.py", line 9, in <module>
    import pkg.openai.dprompt as dprompt
ModuleNotFoundError: No module named 'pkg.openai'
[2024-03-12 22:21:09 +0800] [17300] [INFO] Running on http://127.0.0.1:8181 (CTRL + C to quit)
[2024-03-12 22:21:09 +0800] [17300] [INFO] 127.0.0.1:52378 GET /ws 1.1 101 - 0
[2024-03-12 22:21:12.478] E:\QChatGPT\pkg\pipeline\controller.py (152) - [ERROR] :
    处理请求时出错 query_id=0: 不支持模型: gpt-3.5-turbo-0125 , 请检查配置文件

### 启用的插件

{
    "plugins": [
        {
            "name": "Switcher",
            "description": "快捷切换使用的模型",
            "version": "0.2.0",
            "author": "RockChinQ",
            "source": "https://github.com/RockChinQ/Switcher",
            "main_file": "plugins/Switcher/main.py",
            "pkg_path": "plugins/Switcher/",
            "priority": 0,
            "enabled": true
        },
        {
            "name": "Webwlkr",
            "description": "基于GPT的函数调用能力，为QChatGPT提供联网功能",
            "version": "0.1.1",
            "author": "RockChinQ",
            "source": "https://github.com/RockChinQ/WebwlkrPlugin",
            "main_file": "plugins/WebwlkrPlugin/main.py",
            "pkg_path": "plugins/WebwlkrPlugin/",
            "priority": 0,
            "enabled": true
        },
        {
            "pkg_path": "plugins/revLibs/",
            "source": "https://github.com/RockChinQ/revLibs"
        },
        {
            "pkg_path": "plugins/chat_voice/",
            "source": "https://github.com/oliverkirk-sudo/chat_voice.git"
        }
    ]
}

**Comment by Muyi58317** [comment]
日志里插件的那几个报错确认不是这个bug的原因，但是好像这个版本下好多插件都失效了呀，有点麻烦

**Comment by RockChinQ** [comment]
0125似乎还没有被支持，你可以看看其他的已支持的模型：https://github.com/RockChinQ/QChatGPT/blob/0ee383be2773eb000bab45a016d217b5d6bb772f/pkg/provider/requester/modelmgr.py#L37-L241

另外，预计在下一个版本中会支持 在线模型信息分发 和 模型信息自定义，插件的 API 和兼容性也将进行重新设计。
