### ISSUE TITLE
[Bug]:  无法使用full-scenario模式

### ISSUE THREAD

**Issue by buildin1** [RockChinQ/QChatGPT#731]
### 部署方式

手动部署

### 消息平台适配器

Nakuru（go-cqhttp）

### 系统环境

windows server 2019

### Python环境

python3

### QChatGPT版本

v3.0

### 异常情况

在provider设置为full-scenario模式时会提示未知的 Prompt 加载器: {mode_name}')
ValueError: 未知的 Prompt 加载器: full-scenario

### 日志信息

Traceback (most recent call last):
  File "E:\备胎计划\机器人\Chatgpt\QChatgpt\main.py", line 54, in <module>
    asyncio.run(main_entry())
  File "D:\Data\python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Data\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Data\python\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\备胎计划\机器人\Chatgpt\QChatgpt\main.py", line 48, in main_entry
    await boot.main()
  File "E:\备胎计划\机器人\Chatgpt\QChatgpt\pkg\core\boot.py", line 37, in main
    app_inst = await make_app()
               ^^^^^^^^^^^^^^^^
  File "E:\备胎计划\机器人\Chatgpt\QChatgpt\pkg\core\boot.py", line 29, in make_app
    await stage_inst.run(ap)
  File "E:\备胎计划\机器人\Chatgpt\QChatgpt\pkg\core\stages\build_app.py", line 79, in run
    await llm_prompt_mgr_inst.initialize()
  File "E:\备胎计划\机器人\Chatgpt\QChatgpt\pkg\provider\sysprompt\sysprompt.py", line 32, in initialize
    raise ValueError(f'未知的 Prompt 加载器: {mode_name}')
ValueError: 未知的 Prompt 加载器: full-scenario

### 启用的插件

WebwlkrPlugin

**Comment by RockChinQ** [comment]
确认是bug，将在 3.1 版本修复
