### ISSUE TITLE
[BUG]更新后私聊不可用

### ISSUE THREAD

**Issue by Beyond121** [RockChinQ/QChatGPT#74]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    win11

**描述漏洞**  
更新后私聊报错，并且不会回复。

**完整报错信息**  
```
Exception in thread Thread-37 (on_person_message):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "D:\qcg\QChatGPT\.\pkg\qqbot\manager.py", line 133, in on_person_message
    reply = processor.process_message('person', event.sender.id, str(event.message_chain),
  File "D:\qcg\python\lib\site-packages\func_timeout\dafunc.py", line 185, in <lambda>
    return wraps(func)(lambda *args, **kwargs : func_timeout(defaultTimeout, func, args=args, kwargs=kwargs))
  File "D:\qcg\python\lib\site-packages\func_timeout\dafunc.py", line 108, in func_timeout
    raise_exception(exception)
  File "D:\qcg\python\lib\site-packages\func_timeout\py3_raise.py", line 7, in raise_exception
    raise exception[0] from None
  File "D:\qcg\QChatGPT\.\pkg\qqbot\process.py", line 33, in process_message
    result = asyncio.run(result)
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "D:\qcg\python\lib\site-packages\mirai\models\api.py", line 451, in get
    return await self._call_api(
  File "D:\qcg\python\lib\site-packages\mirai\models\api.py", line 373, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "D:\qcg\python\lib\site-packages\mirai\models\api.py", line 304, in call
    raw_response = await api_provider.call_api(
  File "D:\qcg\python\lib\site-packages\mirai\bot.py", line 91, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "D:\qcg\python\lib\site-packages\mirai\adapters\websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "D:\qcg\python\lib\site-packages\mirai\adapters\websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (5, '[ERROR 5]发送消息目标不存在，或指定对象不存在。', '指定对象不存在')
```

**Comment by Beyond121** [comment]
群聊可以正常回复并且引用原文
