### ISSUE TITLE
[Bug]: mirai启动正常，QChatGPT启动时缺少库？

### ISSUE THREAD

**Issue by lueluelue2006** [RockChinQ/QChatGPT#751]
### 部署方式

手动部署

### 消息平台适配器

yiri-mirai（Mirai）

### 系统环境

win10

### Python环境

3.11

### QChatGPT版本

3.1.0.3

### 异常情况

详见日志

### 日志信息

E:\QQ_Robot\QChatGPT-3.1.0.3\QChatGPT-3.1.0.3>python main.py

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

Traceback (most recent call last):
  File "E:\QQ_Robot\QChatGPT-3.1.0.3\QChatGPT-3.1.0.3\main.py", line 86, in <module>
    asyncio.run(main_entry())
  File "E:\Anaconda\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\QQ_Robot\QChatGPT-3.1.0.3\QChatGPT-3.1.0.3\main.py", line 25, in main_entry
    missing_deps = await deps.check_deps()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\QQ_Robot\QChatGPT-3.1.0.3\QChatGPT-3.1.0.3\pkg\core\bootutils\deps.py", line 26, in check_deps
    __import__(dep)
  File "E:\Anaconda\Lib\site-packages\mirai\__init__.py", line 22, in <module>
    from mirai.bot import (
  File "E:\Anaconda\Lib\site-packages\mirai\bot.py", line 13, in <module>
    import mirai.models.api
  File "E:\Anaconda\Lib\site-packages\mirai\models\__init__.py", line 10, in <module>
    from mirai.models.bus import ModelEventBus
  File "E:\Anaconda\Lib\site-packages\mirai\models\bus.py", line 12, in <module>
    from mirai.models.events import Event
  File "E:\Anaconda\Lib\site-packages\mirai\models\events.py", line 17, in <module>
    from mirai.models.base import MiraiIndexedModel
  File "E:\Anaconda\Lib\site-packages\mirai\models\base.py", line 11, in <module>
    class MiraiMetaclass(pdm.ModelMetaclass):
                         ^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\site-packages\pydantic\_migration.py", line 304, in wrapper
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'pydantic._migration' has no attribute 'ModelMetaclass'

**Comment by RockChinQ** [comment]
pydantic 的问题，显式指定一下装以下依赖：

```
pydantic==1.10.14
pydantic_core==2.16.3
```

**Comment by lueluelue2006** [comment]
我安装了这两个库，但他还是报错，好像是mirai库的问题？
```
E:\QQ_Robot\QChatGPT3.0\QChatGPT>python main.py

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

Traceback (most recent call last):
  File "E:\QQ_Robot\QChatGPT3.0\QChatGPT\main.py", line 17, in <module>
    from pkg.core import boot
  File "E:\QQ_Robot\QChatGPT3.0\QChatGPT\pkg\core\boot.py", line 11, in <module>
    from . import app
  File "E:\QQ_Robot\QChatGPT3.0\QChatGPT\pkg\core\app.py", line 9, in <module>
    from ..platform import manager as im_mgr
  File "E:\QQ_Robot\QChatGPT3.0\QChatGPT\pkg\platform\manager.py", line 9, in <module>
    from mirai import At, GroupMessage, MessageEvent, StrangerMessage, \
  File "E:\Anaconda\Lib\site-packages\mirai\__init__.py", line 22, in <module>
    from mirai.bot import (
  File "E:\Anaconda\Lib\site-packages\mirai\bot.py", line 13, in <module>
    import mirai.models.api
  File "E:\Anaconda\Lib\site-packages\mirai\models\__init__.py", line 10, in <module>
    from mirai.models.bus import ModelEventBus
  File "E:\Anaconda\Lib\site-packages\mirai\models\bus.py", line 12, in <module>
    from mirai.models.events import Event
  File "E:\Anaconda\Lib\site-packages\mirai\models\events.py", line 168, in <module>
    class FriendNickChangedEvent(FriendEvent):
  File "E:\Anaconda\Lib\site-packages\mirai\models\base.py", line 52, in __new__
    new_cls = super().__new__(cls, name, bases, attrs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\site-packages\pydantic\main.py", line 369, in __new__
    cls.__signature__ = ClassAttribute('__signature__', generate_model_signature(cls.__init__, fields, config))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\site-packages\pydantic\utils.py", line 231, in generate_model_signature
    merged_params[param_name] = Parameter(
                                ^^^^^^^^^^
  File "E:\Anaconda\Lib\inspect.py", line 2725, in __init__
    raise ValueError('{!r} is not a valid parameter name'.format(name))
ValueError: 'from' is not a valid parameter name
```

**Comment by RockChinQ** [comment]
pip freeze 看看

**Comment by lueluelue2006** [comment]
已解决，非常感谢！！！！！
