### ISSUE TITLE
[Bug]: 无法开启

### ISSUE THREAD

**Issue by bobandbrony** [RockChinQ/QChatGPT#784]
### 部署方式

手动部署

### 消息平台适配器

Nakuru（go-cqhttp）

### 系统环境

Windows10 ltsc 中国四川

### Python环境

python 3.10.9

### QChatGPT版本

v3.2.0

### 异常情况

原因未知，platform.json的内容是这样的
{
    "access-control":{
        "mode": "blacklist",
        "blacklist": [],
        "whitelist": []
    },
    "respond-rules": {
        "default": {
            "at": true,
            "prefix": [
                ""
            ],
            "regexp": [],
            "random": 0.0
        }
    },
    "income-msg-check": false,
    "ignore-rules": {
        "prefix": ["/"],
        "regexp": []
    },
    "check-sensitive-words": false,
    "baidu-cloud-examine": {
        "enable": false,
        "api-key": "",
        "api-secret": ""
    },
    "rate-limit": {
        "strategy": "drop",
        "algo": "fixwin",
        "fixwin": {
            "default": 60
        }
    },
	"submit-messages-tokens": 4096,
}

### 日志信息

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
�文档地址: https://q.rkcn.top

Traceback (most recent call last):
  File "D:\chatbot\3175216623\QChatGPT-3.2.0\main.py", line 72, in <module>
    asyncio.run(main_entry())
  File "C:\Users\Admin\miniconda3\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\miniconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\miniconda3\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\chatbot\3175216623\QChatGPT-3.2.0\main.py", line 49, in main_entry
    await boot.main()
  File "D:\chatbot\3175216623\QChatGPT-3.2.0\pkg\core\boot.py", line 38, in main
    app_inst = await make_app()
               ^^^^^^^^^^^^^^^^
  File "D:\chatbot\3175216623\QChatGPT-3.2.0\pkg\core\boot.py", line 30, in make_app
    await stage_inst.run(ap)
  File "D:\chatbot\3175216623\QChatGPT-3.2.0\pkg\core\stages\load_config.py", line 16, in run
    ap.pipeline_cfg = await config.load_json_config("data/config/pipeline.json", "templates/pipeline.json", completion=False)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatbot\3175216623\QChatGPT-3.2.0\pkg\config\manager.py", line 55, in load_json_config
    await cfg_mgr.load_config(completion=completion)
  File "D:\chatbot\3175216623\QChatGPT-3.2.0\pkg\config\manager.py", line 24, in load_config
    self.data = await self.file.load(completion=completion)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\chatbot\3175216623\QChatGPT-3.2.0\pkg\config\impls\json.py", line 40, in load
    cfg = json.load(f)
          ^^^^^^^^^^^^
  File "C:\Users\Admin\miniconda3\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\miniconda3\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\miniconda3\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\miniconda3\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 36 column 1 (char 726)

**Comment by RockChinQ** [comment]
你配置文件语法问题哈，去网上搜一下json语法教程

**Comment by bobandbrony** [comment]
> 你配置文件语法问题哈，去网上搜一下json语法教程

啊？那我还是用老版本吧。。。这个json看得我一脸懵逼
老版本我不到10分钟就配置好了

**Comment by RockChinQ** [comment]
json不难的啊，甚至你把配置文件发给ChatGPT问一下他都能给你修复

**Comment by bobandbrony** [comment]
> json不难的啊，甚至你把配置文件发给ChatGPT问一下他都能给你修复

gpt也解决不了，最后我把""submit-messages-tokens": 4096,"末尾的逗号删了就过了
然后platform.json又报错了
![image](https://github.com/RockChinQ/QChatGPT/assets/129247570/2fb0e43f-40c7-4992-94af-9f837d1caf50)
但是gpt说是对的
![image](https://github.com/RockChinQ/QChatGPT/assets/129247570/93fde9bd-b100-48a5-9c38-238bd9aae8c8)
![image](https://github.com/RockChinQ/QChatGPT/assets/129247570/0a4a344f-fe12-490f-9514-2b17ed882091)
这个我真不明白了
