### ISSUE TITLE
[Bug]: 使用指令!help报错

### ISSUE THREAD

**Issue by Chun-QiuCC** [RockChinQ/QChatGPT#801]
### 部署方式

手动部署

### 消息平台适配器

qq-botpy（QQ官方API）

### 系统环境

Windows Server 2019

### Python环境

Python 3.12.3

### QChatGPT版本

v3.2.2

### 异常情况

使用指令!help报错

### 日志信息

```

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

[2024-06-01 18:32:34.841] C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\platform\manager.py (108) - [INFO] :
    初始化平台适配器 0: qq-botpy
[2024-06-01 18:32:34.841] C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\platform\sources\qqbotpy.py (528) - [INFO] :
    运行 QQ 官方适配器
[2024-06-01 18:32:54.503] C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\pipeline\process\process.py (42) - [INFO] :
    处理 person_17198369178661219439 的请求(0): !help
[2024-06-01 18:32:54.506] C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\pipeline\process\handlers\command.py (112) - [INFO] :
    命令返回: QChatGPT - 😎高稳定性、🧩支持...
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Administrator\Miniconda3\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f60e' in position 157: illegal multibyte sequence
Call stack:
  File "C:\Users\Administrator\Desktop\qchat\QChatGPT\main.py", line 72, in <module>
    asyncio.run(main_entry())
  File "C:\Users\Administrator\Miniconda3\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\Administrator\Miniconda3\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\Administrator\Miniconda3\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\Miniconda3\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\Miniconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\Administrator\Miniconda3\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\Administrator\Miniconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\pipeline\controller.py", line 54, in _process_query
    await self.process_query(selected_query)
  File "C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\pipeline\controller.py", line 150, in process_query
    await self._execute_from_stage(0, query)
  File "C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\pipeline\controller.py", line 130, in _execute_from_stage
    async for sub_result in result:
  File "C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\pipeline\process\process.py", line 46, in generator
    async for result in self.cmd_handler.handle(query):
  File "C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\pipeline\process\handlers\command.py", line 112, in handle
    self.ap.logger.info(f'命令返回: {self.cut_str(str(content[0]))}')
Message: '命令返回: QChatGPT - 😎高稳定性、🧩支持...'
Arguments: ()
[2024-06-01 18:32:56.090] C:\Users\Administrator\Desktop\qchat\QChatGPT\pkg\pipeline\controller.py (152) - [ERROR] :
    处理请求时出错 query_id=0: {{reqparam|q.rkcn.top}}
```

### 启用的插件

无插件

**Comment by RockChinQ** [comment]
感觉像是你系统的编码问题，试一下去system.json把帮助信息内容给删了看看
