### ISSUE TITLE
[Bug]: 启动后报错退出

### ISSUE THREAD

**Issue by Mooshed88-a** [RockChinQ/QChatGPT#808]
### 部署方式

手动部署

### 消息平台适配器

yiri-mirai（Mirai）

### 系统环境

Windows 10 企业版 LTSC 1809 中国大陆

### Python环境

Python 3.12.4

### QChatGPT版本

3.2.2

### 异常情况

如标题

### 日志信息

.\QChatGPT-3.2.2>python main.py

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

Traceback (most recent call last):
  File "D:\qq机器人\QChatGPT-3.2.2\main.py", line 72, in <module>
    asyncio.run(main_entry())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\qq机器人\QChatGPT-3.2.2\main.py", line 25, in main_entry
    missing_deps = await deps.check_deps()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\qq机器人\QChatGPT-3.2.2\pkg\core\bootutils\deps.py", line 27, in check_deps
    __import__(dep)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mirai\__init__.py", line 22, in <module>
    from mirai.bot import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mirai\bot.py", line 13, in <module>
    import mirai.models.api
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\mirai\models\api.py", line 68, in <module>
    class SessionInfoResponse(Response):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 286, in __new__
    cls.__try_update_forward_refs__()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 807, in __try_update_forward_refs__
    update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\typing.py", line 554, in update_model_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\typing.py", line 520, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\typing.py", line 66, in evaluate_forwardref
    return cast(Any, type_)._evaluate(globalns, localns, set())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

.\QChatGPT-3.2.2>pause
请按任意键继续. . .

**Comment by RockChinQ** [comment]
尝试换一下pydantic的版本，我这正常的版本是：

pydantic==1.10.15

**Comment by Mooshed88-a** [comment]
> 尝试换一下pydantic的版本，我这正常的版本是：
> 
> pydantic==1.10.15

更换版本后，依然存在问题，报错内容和之前一样

**Comment by RockChinQ** [comment]
相关 issue：https://github.com/pydantic/pydantic/issues/9609
Pydantic 最新版修复了这个问题，但 YiriMirai 与 Pydantic 最新版不兼容，可以尝试把 Python 降至 3.12.3以下，继续使用上述的 Pydantic 版本。

**Comment by Mooshed88-a** [comment]
降级python后解决了，非常感谢！
