### ISSUE TITLE
[Bug]: 无法启动

### ISSUE THREAD

**Issue by bobandbrony** [RockChinQ/QChatGPT#815]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

Windows10 ltsc 中国四川

### Python环境

python 3.10.9

### QChatGPT版本

v3.2.2

### 异常情况

无法启动，配置文件都是填好了的

### 日志信息

PS D:\chatbot\44940****\QChatGPT-3.2.2> python main.py

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

Traceback (most recent call last):
  File "D:\chatbot\44940****\QChatGPT-3.2.2\pkg\core\boot.py", line 42, in main
    app_inst = await make_app()
  File "D:\chatbot\44940****\QChatGPT-3.2.2\pkg\core\boot.py", line 33, in make_app
    await stage_inst.run(ap)
  File "D:\chatbot\44940****\QChatGPT-3.2.2\pkg\core\stages\build_app.py", line 35, in run
    center_v2_api = center_v2.V2CenterAPI(
  File "D:\chatbot\44940****\QChatGPT-3.2.2\pkg\audit\center\v2.py", line 32, in __init__
    self.main = main.V2MainDataAPI(backend_url, ap)
  File "D:\chatbot\44940****\QChatGPT-3.2.2\pkg\audit\center\groups\main.py", line 12, in __init__
    super().__init__(prefix+"/main", ap)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### 启用的插件

无

**Comment by bobandbrony** [comment]
已解决，原因是我把遥测数据服务器删了
