### ISSUE TITLE
[BUG]启动后超时报错

### ISSUE THREAD

**Issue by zgswq** [RockChinQ/QChatGPT#83]
**运行环境**
- 部署方式：
    手动部署
- 系统环境：
    windows10 64位
- Python环境（仅手动部署填写）：
    conda python3.10.8

**描述漏洞**  
mirai已启动且登录完成，主程序配置完成，在启动后超时报错
- 环境版本
```
aiofiles==0.7.0
anyio==3.6.2
certifi==2022.12.7
charset-normalizer==2.1.1
colorama==0.4.6
colorlog==6.7.0
dulwich==0.20.50
et-xmlfile==1.1.0
func-timeout==4.3.5
h11==0.12.0
httpcore==0.13.7
httpx==0.18.2
idna==3.4
numpy==1.24.1
openai==0.25.0
openpyxl==3.0.10
pandas==1.5.2
pandas-stubs==1.5.2.221213
pip==22.3.1
pydantic==1.10.4
python-dateutil==2.8.2
pytz==2022.7
requests==2.28.1
rfc3986==1.5.0
setuptools==65.5.0
six==1.16.0
sniffio==1.3.0
starlette==0.23.1
tqdm==4.64.1
types-pytz==2022.7.0.0
typing_extensions==4.4.0
urllib3==1.26.13
websockets==10.4
wheel==0.37.1
wincertstore==0.2
yiri-mirai==0.2.6.1
```

**完整报错信息**  
```
[2023-01-03 20:37:30.090] main.py (90) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-01-03 20:37:30.091] main.py (91) - [INFO] : 如报错 "TypeError: run() got an ... argument 'debug'" ,请查看 https://github.com/RockChinQ/QChatGPT/issues/82
[2023-01-03 20:37:30.091] main.py (93) - [INFO] : 如报错 "TypeError: As of 3.10, the *loop* parameter ... it is no longer necessary" ,请查看 https://github.com/RockChinQ/QChatGPT/issues/5
[2023-01-03 20:37:30.092] main.py (95) - [INFO] : 如报错 "server rejected WebSocket connection: HTTP 404" ,请查看 https://github.com/RockChinQ/QChatGPT/issues/22
[2023-01-03 20:37:30.092] main.py (97) - [INFO] : 其他异常请前往仓库issue搜索或提issue
2023-01-03 20:37:38 - ERROR
[2023-01-03 20:37:38.100] base.py (43) - [ERROR] :
Exception in thread Thread-1 (run):
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\websockets\legacy\client.py", line 666, in __await_impl__
    await protocol.handshake(
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\websockets\legacy\client.py", line 332, in handshake
    raise InvalidStatusCode(status_code, response_headers)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\websockets\legacy\client.py", line 680, in __await_impl__
    await protocol.wait_closed()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\openai\lib\asyncio\tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\openai\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Miniconda3\envs\openai\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\mirai\bot.py", line 197, in run
    MiraiRunner(self).run(host, port, asgi_server, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\mirai\bot.py", line 274, in run
    asyncio.run(self._run())
  File "C:\ProgramData\Miniconda3\envs\openai\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\ProgramData\Miniconda3\envs\openai\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\mirai\bot.py", line 238, in _run
    await self.startup()
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\mirai\bot.py", line 226, in startup
    await asyncio.gather(*coros)
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\mirai\bot.py", line 135, in startup
    await self._adapter.login(self.qq)
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\mirai\adapters\base.py", line 35, in wrapped
    return await func(self, *args, **kwargs)
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\mirai\adapters\websocket.py", line 187, in login
    self.connection = await connect(self.host_name, extra_headers=headers)
  File "C:\ProgramData\Miniconda3\envs\openai\lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "C:\ProgramData\Miniconda3\envs\openai\lib\asyncio\tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by RockChinQ** [comment]
看 #22
