### ISSUE TITLE
[Bug]: python3.14启动报错

### ISSUE THREAD

**Issue by yunnis** [RockChinQ/QChatGPT#903]
### 消息平台适配器

None

### 运行环境

CentOS 7.6 64位

### QChatGPT版本

v3.3.1.1

### 异常情况

2024.10.16 刚pull的版本, 其实之前也有
启动时报错, 无法启动

python3 main.py 

  ___   ___ _         _    ___ ___ _____ 
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |  
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|  

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

Traceback (most recent call last):
  File "/root/work/QChatGPT/main.py", line 72, in <module>
    asyncio.run(main_entry())
    ~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/python/lib/python3.14/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/python/lib/python3.14/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/python/lib/python3.14/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/root/work/QChatGPT/main.py", line 25, in main_entry
    missing_deps = await deps.check_deps()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/work/QChatGPT/pkg/core/bootutils/deps.py", line 28, in check_deps
    __import__(dep)
    ~~~~~~~~~~^^^^^
  File "/usr/python/lib/python3.14/site-packages/mirai/__init__.py", line 22, in <module>
    from mirai.bot import (
        LifeSpan, Mirai, MiraiRunner, Shutdown, SimpleMirai, Startup
    )
  File "/usr/python/lib/python3.14/site-packages/mirai/bot.py", line 13, in <module>
    import mirai.models.api
  File "/usr/python/lib/python3.14/site-packages/mirai/models/__init__.py", line 10, in <module>
    from mirai.models.bus import ModelEventBus
  File "/usr/python/lib/python3.14/site-packages/mirai/models/bus.py", line 12, in <module>
    from mirai.models.events import Event
  File "/usr/python/lib/python3.14/site-packages/mirai/models/events.py", line 21, in <module>
    from mirai.models.message import MessageChain
  File "/usr/python/lib/python3.14/site-packages/mirai/models/message.py", line 116, in <module>
    class MessageChain(MiraiBaseModel):
    ...<549 lines>...
            return source.id if source else -1
  File "/usr/python/lib/python3.14/site-packages/pydantic/main.py", line 241, in __new__
    vg.check_for_unused()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/python/lib/python3.14/site-packages/pydantic/class_validators.py", line 189, in check_for_unused
    raise ConfigError(
    ...<2 lines>...
    )
pydantic.errors.ConfigError: Validators defined with incorrect fields: _parse_component (use check_fields=False if you're inheriting from the model and intended this)

### 启用的插件

_No response_

**Comment by RockChinQ** [comment]
换成Python 3.12

**Comment by yunnis** [comment]
收到, 好快的回
