### ISSUE TITLE
[BUG]回复正常出现在了cmd窗口，但并未在qq中回复

### ISSUE THREAD

**Issue by guyangliu** [RockChinQ/QChatGPT#97]
请认真按照实际情况填写以下信息！！！！

- 部署方式：
   按照B站up thelazy 视频部署
- 系统环境：
    例如： Windows10 x64
- Python环境（仅手动部署填写）：
    例如： Python 3.9

**描述漏洞**  
主程序。在收到消息后黄字提示超时，然后回复正常出现在了cmd窗口中，但并未在qq中回复。

**完整报错信息**  
```
[2023-01-12 12:45:38.830] process.py (285) - [INFO] : [group_625336068]发送消息:你好
[2023-01-12 12:45:38.831] util.py (67) - [INFO] : message='Request to OpenAI API' method=post path=https://api.openai.com/v1/completions
[2023-01-12 12:45:43.119] util.py (67) - [INFO] : message='OpenAI API response' path=https://api.openai.com/v1/completions processing_ms=3063 request_id=7120530f26f0ff86f407cd9596c39c50 response_code=200
[2023-01-12 12:46:08.833] manager.py (209) - [WARNING] : group_625336068: 超时，重试中
Exception in thread Thread-32 (on_group_message):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "E:\computer tools\chatgpt\QChatGPT\.\pkg\qqbot\manager.py", line 221, in on_group_message
    if Image in event.message_chain:
AttributeError: 'Event' object has no attribute 'message_chain'
[2023-01-12 12:47:04.815] process.py (328) - [INFO] : 回复[group_625336068]文字消息:你好！我可以为您提供帮助。有什么我可以帮助您的吗？
```

**Comment by RockChinQ** [comment]
mirai控制台有显示回复内容吗

**Comment by guyangliu** [comment]
> mirai控制台有显示回复内容吗

有的，就是我贴出来的：
[2023-01-12 12:47:04.815] process.py (328) - [INFO] : 回复[group_625336068]文字消息:你好！我可以为您提供帮助。有什么我可以帮助您的吗？
这一行，回复的挺正常。

**Comment by guyangliu** [comment]
昨天晚上12点左右还是正常了一小会的，今天早上就提示api超限，但是我检查了账户是有余额的，配置好了api也没有再动过。现在又开始出我在这个issue里提到的问题，倒是不提示api超限了。

**Comment by RockChinQ** [comment]
> 昨天晚上12点左右还是正常了一小会的，今天早上就提示api超限，但是我检查了账户是有余额的，配置好了api也没有再动过。现在又开始出我在这个issue里提到的问题，倒是不提示api超限了。

api超限也有可能是因为其他的问题，由于OpenAI的异常将其归为一类，故产生误报。  
目前这个问题估计是mirai的问题，因为在mirai控制台可以看到回复，说明主程序能正常处理消息，而QQ界面无法收到消息。  
建议先尝试重新登录mirai、更换QQ号、切换网络或者重新手动安装mirai。

**Comment by guyangliu** [comment]
重装了一下mirai，好了，谢谢。
真够玄学的。
